### ISSUE TITLE
Variable replacer does not take dotenv variables into account

### ISSUE THREAD

**Issue by fredrikhr** [AnWeber/httpyac#103]
```
GET {{Url}}
```

The line above errors when `Url` is a dotenv variable. I added a breakpoint to the `javascriptVariableReplacer` function and inspected the `context` parameter. Sure enough, config-file variables were present in `context.variables`, but dotenv variables were not.

https://github.com/AnWeber/httpyac/blob/6616ca198ef0c5b4f0c544fcbb29f1acb1c70698/src/variables/replacer/javascriptVariableReplacer.ts#L7-L38

**Comment by AnWeber** [comment]
In fact, he should already be using them. I could not reproduce the error with my example.
![variable](https://user-images.githubusercontent.com/13434739/140899652-579f8c66-6c40-4302-bc6d-64cfe0baca15.gif)
```
Url=https://httpbin.org/json
```
The variables are already loaded initially and should be present in the `context.variables` (https://github.com/AnWeber/httpyac/blob/main/src/httpYacApi.ts#L86-L99)
https://github.com/AnWeber/httpyac/blob/main/src/variables/provider/initHooks.ts#L16-L25

**Comment by fredrikhr** [comment]
Ah, the error comes from me having my dotenv files in a different directory than the default. The `rootDir` of the `httpFile` is correct. That directory does contain a file `.httpyac.json` and within that file there is a line: 
``` json
{
  "envDirName": ".env"
}
```

BUT, the `config` property on the `context` shows: `enDirName` to be `env`, thus resulting in the error.

**Comment by fredrikhr** [comment]
AH! The error occurs in `getEnviromentConfig`! If the `config` argument is specified it is merged in **after** the loaded config from the found `rootDir` of the `httpFile`.

https://github.com/AnWeber/httpyac/blob/7f887587d4a882ce74f840778d1aae7d20e7b526/src/store/httpFileStore.ts#L196-L204

Because of the following config initialize for the CLI, the `envDirName` get a value of `env`.
https://github.com/AnWeber/httpyac/blob/7f887587d4a882ce74f840778d1aae7d20e7b526/src/cli/cli.ts#L103-L114

**Comment by AnWeber** [comment]
But is probably not the only place. In VS code I could also reprod the error.

**Comment by fredrikhr** [comment]
Hmm... is there an issue with moving the `if (config)` block up a notch?

https://github.com/AnWeber/httpyac/blob/7f887587d4a882ce74f840778d1aae7d20e7b526/src/store/httpFileStore.ts#L202-L204 

For example up to before L196?

https://github.com/AnWeber/httpyac/blob/7f887587d4a882ce74f840778d1aae7d20e7b526/src/store/httpFileStore.ts#L194-L217

**Comment by fredrikhr** [comment]
Moving it up would make more sense, since the `config` argument comes **before** the `rootDir` argument....

**Comment by AnWeber** [comment]
Moving up is wrong for CLI Arguments and for VSCode settings. These should already overwrite the configuration

**Comment by AnWeber** [comment]
Just remove envDirName in Cli.ts. it is also defined in httpFileStore as default

**Comment by fredrikhr** [comment]
Yeah, totally right. Okay PR coming up :)
