### ISSUE TITLE
Removing Bearer from openid implicit

### ISSUE THREAD

**Issue by staff0rd-client** [AnWeber/httpyac#108]
[AppSync doesn't support `Authentication: Bearer <token>` syntax](https://github.com/aws/aws-appsync-community/issues/96), and instead expects `Authentication: <token>` - what is the best way to remove `Bearer` from the requests generated by the following syntax?

```
POST http://some/appsync/graphql
Authorization: openid implicit myPrefix
Content-Type: application/json

query...
```

**Comment by AnWeber** [comment]
Just remove it with a script.

```
{{@request
 request.headers.Authorization = request.headers.Authorization.slice('Bearer '.length);
}} 
POST http://some/appsync/graphql
Authorization: openid implicit myPrefix
Content-Type: application/json

query...
```

The important thing here is to specify `@request`. This defines the time at which the script is executed and at this time the authorization header is already replaced.

**Comment by staff0rd-client** [comment]
works great, thank-you.
