### ISSUE TITLE
Enhance formatting

### ISSUE THREAD

**Issue by staff0rd** [AnWeber/httpyac#116]
I see some eslint coverage on the project but ponder whether you'd be open to something with wider coverage, for example [prettier](https://prettier.io/) or [standardjs](https://standardjs.com/).

I'd also like to propose save on format either in place of, or in addition to the pre-commit hook. eslint, prettier and standardjs all have options to enable format on save in vscode and help contributors know while inside the IDE that they don't need to worry about formatting.

**Comment by AnWeber** [comment]
What are the advantages of using Prettier support?

I have tested Prettier in a separate feature branch. I don't care much about the formatting rules, as long as semicolon stays. I find the formattings via `eslint -- fix` sufficient.

**Comment by staff0rd** [comment]
The advantage of prettier is to apply formatting across all files, not just typescript/javascript - so json, markdown, yaml etc... It removes ambiguity from all formatting, cleans up whitespace and removes the need (or opportunity) for contributors to be concerned in any way with formatting during the PR process. I would further your feature branch to include [all files like this](https://github.com/AnWeber/httpyac/compare/feature/prettier...staff0rd:prettier?expand=1), specifically via [settings.json](https://github.com/staff0rd/httpyac/blob/f7888052b5c801eada3762b90d30302d49eb81c3/.vscode/settings.json).

Another advantage is to accept its opinion (or [standardjs](https://standardjs.com/)) and apply its formatting across multiple/all repos without without customising the style. This means custom rules don't need to be synchronised across repos and the codebase feels familiar to contributors that use other formatted repos with few/no customisations. This however may be a disadvantage depending on your attachment to your own opinions :)

eslint requires further plugins to format other files, but if rich customisation of formatting is needed then it's a fine choice. I would argue for something [like this](https://github.com/staff0rd/httpyac/blob/main/.vscode/settings.json#L8-L12) to make it not conflict with global `formatOnSave` options.

**Comment by AnWeber** [comment]
I'll have to find out if prettier is better once I use it. The auto-formatting currently works well. So try something new from time to time. Thanks.
