### ISSUE TITLE
Feature: Configure callback

### ISSUE THREAD

**Issue by staff0rd** [AnWeber/httpyac#118]
I'd like to attempt to make the hardcoded callback url (http://localhost:3000) for openid implicit to be configurable. Is this a feature you'd be interested in merging were I to open a PR?

At the very least, I'd expect to be able to use something like `--callback http://localhost:8653/whatever/path` or similar via CLI option and the http server to respect this.

**Comment by AnWeber** [comment]
The change would also affect the VSCode extension. Therefore, when starting the server, it would be necessary to check whether a server has already been opened on this port and to reuse it if necessary. This makes it necessary [to manage the servers that have been started](https://github.com/AnWeber/httpyac/blob/main/src/variables/replacer/oauth/openIdHttpserver.ts#L13-L15).
To customize the path, the logic for recognizing the [callback call](https://github.com/AnWeber/httpyac/blob/main/src/variables/replacer/oauth/openIdHttpserver.ts#L79) must be adjusted.

I actually don't mind features that extend functionality. However, backwards compatibility should always be taken into account (if possible).

**Comment by AnWeber** [comment]
The pull request I have just published with the new version
