### ISSUE TITLE
Support the special character '.' in header names

### ISSUE THREAD

**Issue by attilagyongyosi** [AnWeber/httpyac#128]
## Background
HTTP header field names can contain the character `.` according to [this RFC](https://greenbytes.de/tech/webdav/rfc7230.html#header.fields) and the definition of a `token` within.  
However, httpyac fails to properly parse an `.http` file with such a header name.

Although commonly used header names have dashes, certain web services can require custom header names.
`httpyac` should fully support the RFC, especially for proper interoperability with the IntelliJ REST Client plugin.

## Example http File
```http
GET https://google.com
header.name: xyz
```

Executing `httpyac` with such a file, the following error report can be observed:
```javascript
ExecuteHook: httpClient failed
RequestError: The `GET` method cannot be used with a body
    at Request._destroy (D:\projects\sandboxes\httpyac-test\node_modules\got\dist\source\core\index.js:1378:21)
    at _destroy (node:internal/streams/destroy:102:25)
    at Request.destroy (node:internal/streams/destroy:64:5)
    at D:\projects\sandboxes\httpyac-test\node_modules\got\dist\source\core\index.js:354:26
    at Request._finalizeBody (D:\projects\sandboxes\httpyac-test\node_modules\got\dist\source\core\index.js:716:23)
    at D:\projects\sandboxes\httpyac-test\node_modules\got\dist\source\core\index.js:333:28
    at new Request (D:\projects\sandboxes\httpyac-test\node_modules\got\dist\source\core\index.js:357:11)
    at makeRequest (D:\projects\sandboxes\httpyac-test\node_modules\got\dist\source\as-promise\index.js:35:29)
    at D:\projects\sandboxes\httpyac-test\node_modules\got\dist\source\as-promise\index.js:147:9
    at D:\projects\sandboxes\httpyac-test\node_modules\p-cancelable\index.js:63:11
    at new Promise (<anonymous>)
    at new PCancelable (D:\projects\sandboxes\httpyac-test\node_modules\p-cancelable\index.js:31:19)
    at Object.asPromise [as default] (D:\projects\sandboxes\httpyac-test\node_modules\got\dist\source\as-promise\index.js:33:21)
    at getPromiseOrStream (D:\projects\sandboxes\httpyac-test\node_modules\got\dist\source\create.js:43:121) {
  code: 'ERR_GOT_REQUEST_ERROR',
  timings: undefined
}
```
as the parsing of the file breaks and `header.name: xyz` is now considered as the request body.

**Comment by AnWeber** [comment]
This regex is the culprit: https://github.com/AnWeber/httpyac/blob/main/src/parser/parserRegex.ts#L62. I will extend according to the RFC.

**Comment by attilagyongyosi** [comment]
Hey @AnWeber, thanks for the very quick reply!
I am planning on introducing your VSCode plugin at work, but some of our services require header names with dots in them.
It would be super cool if support would be there.

**Comment by AnWeber** [comment]
Workaround is possible using Javascript

```
{{
request.header['header.name'] = 'xyz';
}}
GET https://google.com
header.name: xyz
```

**Comment by attilagyongyosi** [comment]
That is true.
That unfortunately wouldn't suffice for my situation though: as some of our engineers use WebStorm and others use VSCode, I am trying to find an interoperable solution of consuming `.http` files within IDEs. The syntax above is unfortunately not supported by the IntelliJ REST Client.

**Comment by AnWeber** [comment]
Unfortunately Intellij does not support script or OAuth2. Otherwise the extension would not exist. I am still looking for the right regex and will then implement it.

**Comment by attilagyongyosi** [comment]
Thank you, much appreciated!

**Comment by AnWeber** [comment]
Here is the fieldValueRegExp used by JSDOM: https://github.com/jsdom/jsdom/blob/master/lib/jsdom/living/xhr/XMLHttpRequest-impl.js#L34.

**Comment by AnWeber** [comment]
@attilagyongyosi I'm sorry it took so long now after all. There was unexpectedly much movement in this project the last few days. With the new version the regex was updated and headers with `.` are now allowed.

**Comment by attilagyongyosi** [comment]
@AnWeber, I am used to depending on enterprise teams, so no worries, this was quite a swift fix and release :)
Thank you very much!
I have updated the VSCode extension as well and I can verify that the issue is indeed no longer present.
You just made the life of a bunch of Hungarian engineers a bit better.
