### ISSUE TITLE
Can you provide a plugin example please?

### ISSUE THREAD

**Issue by rngtng** [AnWeber/httpyac#130]
You lost me a bit in the Plugin Development section, especially as I'm not an experienced JS developer. Could you provider a small example please, maybe as a dedicated repo or examples? I'm interested in setting a default environment and updating the parsing to support more/custom http methods (or better a custom request handler, like grpc is)

```
CUSTOM custom.domain:9000/hello.HelloService/sayHello
...
```

I already got hs2019 http-request-signing working with `{{+request ...}}` hook, but would be great to ship this as a plugin too.

**Comment by AnWeber** [comment]
Just a teaser. I will add more and better examples: https://github.com/httpyac/httpyac.github.io/blob/main/examples/project/httpyac.config.js#L12,L17

**Comment by rngtng** [comment]
ok thanks I got this working. But I understood it can be provided as an extra npm package? This I didn't got working..

**Comment by AnWeber** [comment]
I will create an example, but just short description. 
- package.json with name httpyac-plugin-...
-  package.json contains field `main` referencing index.js
- create index.js with same content as `.httpyac.js`
- this package must be referenced in your package.json where the http files are stored.

The Plugin API is a copy of Vue cli plugin API. Here is a example for such a plugin: https://github.com/AnWeber/vue-cli-plugin-compression

**Comment by rngtng** [comment]
ah I missed some of that, let my try again tomorrow, thx

**Comment by rngtng** [comment]
Uh yes, I got plugin detection & loading  working now! I didn't reference the plugin in package.json (facepalm).  For reference this example `index.js` adds a hook:

```
module.exports = (api) => {
  api.hooks.onRequest.addHook('customHook', function (request, context) {
    // code to execute
  });
}
```

**Comment by AnWeber** [comment]
For GRPC parsing the following files are important.
- https://github.com/AnWeber/httpyac/blob/main/src/parser/grpcHttpRegionParser.ts
- https://github.com/AnWeber/httpyac/blob/main/src/actions/grpcClientAction.ts
It is important to add this hook before `parseRequestLine` Parser. `parseRequestLine` accepts all input. 

```js
module.exports = (api) => {
  api.hooks.parse.addHook('customHook', function (...) { }, { before: ['request']});
}
```

**Comment by AnWeber** [comment]
I have now published an example for each hook in my documentation page. I will still integrate it on the website. Let's see how.

**Comment by rngtng** [comment]
wow nice. exactly what I was looking for.. Thanks!

**Comment by AnWeber** [comment]
If you have suggestions for improving the API, we can talk. I intentionally used it myself to test it, but there are still places that need improvement.

**Comment by rngtng** [comment]
Thanks examples helped me a lot. Ironically, the missing one, `parseEndRegion`, does what I'm looking for. Goal was to add syntactic sugar for repetitive httprequest pattern. Simplified example:


```
GIVEME coffee
```

gets translated to

```
POST /v1/giveme/{{globalvar}}/coffee
```

This works with the following hook:

```
api.hooks.parseEndRegion.addHook('prepareRequest', function (context) {
    const request = context.httpRegion.request;

    if (request) {
      const match = request.url.match(/^\s*(?<method>GIVEME) (?<url>[^ ]+)$/ui)?.groups;
      if (match) {
        request.method = 'POST';
        request.url = '/v1/' + match.method.toLowerCase() + '/{{globalvar}}/' + match.url;
      };
    }
  });
```

THANKS!

**Comment by AnWeber** [comment]
For simple replacements of the URL, the `replaceVariable` hook is also useful. Just have a quick look at my [hostVariableReplacer](https://github.com/AnWeber/httpyac/blob/main/src/variables/replacer/hostVariableReplacer.ts). This is the trick how I simplify my urls. However, in some cases, I need to change the variable using `@host` in global scope to override my default from the environment.
```
@host=http://127.0.0.1/taskmanager/api/v1
###
GET /tasks


POST /tasks
...
```
equals
```
GET http://127.0.0.1/taskmanager/api/v1/tasks


POST http://127.0.0.1/taskmanager/api/v1/tasks
...
```

**Comment by rngtng** [comment]
yes, I tried this first, but somehow it had issues with the custom http method..

**Comment by AnWeber** [comment]
Yes, I don't redefine the method on purpose. The parser does not recognize them then. You have to use explicit `###` and correct the URL that contains the method. Too much trouble for me. I like the [kibana style](https://www.elastic.co/guide/en/kibana/current/console-kibana.html) formatting of the http files.

**Comment by rngtng** [comment]
Ah stupid me - *now* I found the right solution. The one earlier was a hack and didn't work for any parsing related hooks. BUT this works: Create at `.httpyac.js` in test folder and init plugin with:

```js
const plugin = require("..path to plugin index...");

module.exports = {
  configureHooks: function (api) {
    plugin(api);
  }
}
``
