### ISSUE TITLE
Outputting token

### ISSUE THREAD

**Issue by staff0rd** [AnWeber/httpyac#138]
GraphQL code generation has a [configuration](https://www.graphql-code-generator.com/docs/config-reference/schema-field#headers) where you supply the URL and a valid JWT token - it will use introspection to generate results.

In my scenario, I have client applications that need to generate against multiple endpoints and as such need multiple JWTs. This means getting valid tokens and pasting them into the config before generation, which is super annoying.

I've since determined I can use `httpyac`'s auth mechanism to get the tokens. I have an .http file like the following:
```bash
# myrequest.http
{{@response
  console.log(request.headers.Authorization.replace("Bearer ", ""));
}}
POST /
Authorization: openid implicit
```

I can then call `httpyac myrequest.http --all -o none --vars <oauth2 vars> > .token` and the token appears in `.token`.

I also have other reasons to get a token, for example when needing to use [Apollo Studio Explorer](https://studio.apollographql.com/sandbox/explorer/).

I wonder whether there is appetite to include a feature in `httpyac` that outputs the token without the need to specify or configure an .http file?

**Comment by AnWeber** [comment]
I love open source. I haven't thought about such a thing, but the code allows it.. I could already build a separate command for it, that you can use it directly without http file, but would be special, but practical. Improvement for the future:-)

**Comment by rngtng** [comment]
@staff0rd btw. this works for me too w/o the `{{@response .. ` block:

```
httpyac myrequest.http --all -o body | grep access_token | jq -r '.access_token'
```

**Comment by staff0rd** [comment]
@rngtng nice - in my case i had to use:

```bash
httpyac myrequest.http --all --json -o headers | jq -r .requests[0].response.request.headers.authorization
```

That said, my usecase turns out to be in node, rather than as a separate process, so I prefer the api approach - I'll make some nice wrapper instead of needing to call the depths of the api like [this snippet](https://github.com/AnWeber/httpyac/pull/141).

**Comment by AnWeber** [comment]
I have added a separate sub command to simplify things.

```sh
httpyac oauth2 --flow implicit
```
I was going to switch to commander anyway, so it was a good opportunity.
