### ISSUE TITLE
How to set a default environment?

### ISSUE THREAD

**Issue by rngtng** [AnWeber/httpyac#142]
I've trouble setting a default environment. I tried your example hook (https://httpyac.github.io/plugins/plugin-api.html#provideenvironmentshook) but this seems to just return a list of possible envs? I thought with that running `httpyac test.http -e dev,prev` could be simplified to just `httpyac test.http`. Any advice how else this could be achieved?

As I could see this could be a feature demanded quite often, what about 'native' support with sth like:

```
{
  "$shared": {
    "host": "https://mydoman"
  },
  "$default": "dev",
  "dev": {
    "user": "mario",
    "password": "123456"
  },
  "prod": {
    "user": "mario",
    "password": "password$ecure123"
  }
}

**Comment by rngtng** [comment]
Ah quick fix: I moved all configs of default env into `$shared`. works, but maybe a bit confusing as the env name is gone and  another env may not overwrite all shared values..

**Comment by AnWeber** [comment]
`provideEnvironments` is needed to allow selection of environments in VSCode. `provideVariables` is the hook you need. You get current environment selection and can fill your defaults if no env is selected (undefined or empty array)

**Comment by rngtng** [comment]
Ah this looks way more promising, somehow must have overlooked it. will try tomorrow. thx

**Comment by AnWeber** [comment]
The solution would probably be to provide a `$default` environment in addition to `$shared` that is loaded when no environment is present.

**Comment by rngtng** [comment]
happy to implement this :)

**Comment by AnWeber** [comment]
would be an adjustment in [configVariableProvider.ts](https://github.com/AnWeber/httpyac/blob/main/src/variables/provider/configVariableProvider.ts#L21-L24). To consider would be whether one integrates the feature also in [dotenvVariableProvider](https://github.com/AnWeber/httpyac/blob/main/src/variables/provider/dotenvVariableProvider.ts#L75-L81). [Here](https://github.com/AnWeber/httpyac/blob/main/src/variables/provider/dotenvVariableProvider.ts#L34) you would have to filter out the `default.env` or `.env.default` file.

**Comment by AnWeber** [comment]
With the new version it is also possible to set variables using the key `$default`, which are only used if no environment is set.

**Comment by rngtng** [comment]
thanks!!
