### ISSUE TITLE
Feature request:  variable replacement - render object as JSON

### ISSUE THREAD

**Issue by rngtng** [AnWeber/httpyac#146]
See the example below. If the variable is an object, it's gets rendered as `[object Object]` which isn't helpful at all. What about to json-ify it instead?

```
{{
  module.exports = {
    body: {
      id: 1
    }
  }
}}

POST http://httpbin.org/anything
{{body}}
```

Current response:
```
...
  "data": "[object Object]",
  "json": null
...
```

Suggestion:
```
  "data": "{\n  \"id\": 1\n}",
  "json": {
    "id": 1
  },
```

**Comment by AnWeber** [comment]
I have added the feature with the new version.

**Comment by rngtng** [comment]
yes it works great! thanks!
