### ISSUE TITLE
Tests broken on main

### ISSUE THREAD

**Issue by staff0rd** [AnWeber/httpyac#148]
`npm run test` fails on `main`.

Oddly it appears they are failing in the build too, but the build is not bailing out, see the [test step here](https://github.com/AnWeber/httpyac/runs/4430763957?check_suite_focus=true)

**Comment by AnWeber** [comment]
Ok. I must confess, I was relying on that now. I had problems (timeout) locally that they take so long and blamed it on my 10 year old computer.

**Comment by staff0rd** [comment]
Ya it was because commander calls process.exit during --version. Fixed in #149

**Comment by AnWeber** [comment]
Thanks for fixing it. I plan to spend more time with the unit tests in the near future. The whole project currently has a little imbalance that I don't like. For example, imports with `@/...` only work in the unit test section. Babel understands the notation, esbuild does not yet. And I need to build in a meaningful `watch` that I can run while developing.
