### ISSUE TITLE
Feature request: import with variable

### ISSUE THREAD

**Issue by lantian** [AnWeber/httpyac#151]
Hello,

Currently @import not allows to import using variable but it would be nice to have this abillity coz hierarchy of folders can be huge:

```
# @import ./../../../../../../some-folder/auth.http
``` 

It will be much easier to read and maintain this line:

```
# @import {{PATH_ROOT}}/some-folder/auth.http
```

**Comment by AnWeber** [comment]
Yes, good idea. I use the same mechanism as for loading proto files. It will be delivered with the next version.

**Comment by AnWeber** [comment]
I have just released the new version. The feature is included.
