### ISSUE TITLE
Can you write one test and just change the environment variable?

### ISSUE THREAD

**Issue by FrankRua** [AnWeber/httpyac#152]
Is it possible that you can have one test in your *.http file and just simply just the variable on one iteration, and then another iteration have it change?

I have a use case for this as I want to run tests against a CDN and the Load Balancer behind the CDN. An example would be like:

```
// Iteration 1&2
GET {{cdnDns}}/healthcheck
GET {{lbDns}}/healthcheck

// Assertions should be the same, since response should be the same.

// Assert Result on both iterations
```

**Comment by AnWeber** [comment]
This code should do the trick
```
### health_cdn
GET {{cdnDns}}/healthcheck
### health_lb
# @ref health_cdn
GET {{lbDns}}/healthcheck

{{
  const { equal } = require('assert');
  test('should be same response', () => {
    equal(JSON.stringify(health_lb),JSON.stringify(health_cdn));
  });
}}

```

**Comment by FrankRua** [comment]
@AnWeber How would I extract the status codes out of `health_lb` and `health_cdn`  so I can do something like

```
    equal(health_lb.status, 200);
    equal(health_cdn.status, 200);
```

**Comment by AnWeber** [comment]
@FrankRua  not directly. My main use case is that I want to share the response body between requests. status is no longer important to me. For this reason you have to define a variable with the response of first request yourself

```
### health_cdn
GET https://httpbin.org/json

{{
  exports.health_cdn_response = response
}}

### health_lb
# @ref health_cdn
GET https://httpbin.org/json

{{
  const { equal } = require('assert');
  test('should be same response', () => {
    equal(JSON.stringify(health_lb),JSON.stringify(health_cdn));
  });
  test('should be same status', () => {
    equal(response.statusCode, health_cdn_response.statusCode);
  });
}}
```

Here is the interface for a [httpResponse](https://github.com/AnWeber/httpyac/blob/main/src/models/httpResponse.ts)

**Comment by AnWeber** [comment]
I would meanwhile already set the response as a variable, but initially overlooked it and now I don't want to change the api.

**Comment by AnWeber** [comment]
I have just released the new version. The feature is included.

**Comment by AnWeber** [comment]
:-) sorry I closed the wrong issue.

**Comment by FrankRua** [comment]
@AnWeber Is there a way to see if the body of a response contains a string? I see the `assert` library has a "match" but I don't think I can use it with our library as it gives me `match is not defined`.

**Comment by AnWeber** [comment]
Jest is another test runner. httpyac is also used here as a test runner. I have also already tested the assertion with [chai](https://www.npmjs.com/package/chai), [here is a example](https://github.com/httpyac/httpyac.github.io/blob/main/examples/script/chai.http). Maybe you can also use jest for this, But does not feel right.
If I were you, I would rather look at debugging the tests. You would have to install `httpyac` as CLI tool and start the call in VSCode in the javascript debug terminal (`httpyac test.http`). Add a [`debugger;`](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Statements/debugger) to your Code and view response. [Here are the steps documented in more detail](https://httpyac.github.io/guide/scripting.html#how-to-debug-scripts)

**Comment by FrankRua** [comment]
Is it possible to do a "contains" on on the response with HttpYac?

**Comment by AnWeber** [comment]
Yeah, the script Context is a real NodeJS Context. You can use all functionality of JavaScript, I prefer using [`indexOf`](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/String/indexOf) but NodeJS should also support [`includes`](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/String/includes) (not sure). You could `JSON.stringify` the complete response and use `indexOf`

**Comment by AnWeber** [comment]
If there are any questions just contact me again:-)
