### ISSUE TITLE
Bug: JS warning when multiples spaces in title

### ISSUE THREAD

**Issue by rngtng** [AnWeber/httpyac#154]
Another tiny one: I figured I get a js warning (in vscode) when request title has more than one space:

```
### Foo Bar Baz
GET http://httpbin.org
```

Warning: `Javascript Keyword Foo_Bar Baz not allowed as name`. Haven't test it, but probably this breaks even the @ref option for following requests..

On a side node: I'd expect the name conversion into lower camelcase: `fooBarBaz` !?

**Comment by AnWeber** [comment]
I love javascript, but how javascript implemented `String.replace` is fucking stupid. 

```js
// wrong
"foo foo bar".replace(' ', '_');
// wrong
"foo foo bar".replace(/\s/u, '_');
//right
"foo foo bar".replace(/\s/gu, '_')
```

**Comment by rngtng** [comment]
Wow! Indeed WTF:

> If pattern is a string, only the first occurrence will be replaced.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace

thanks the fix

**Comment by AnWeber** [comment]
Exactly. I know the peculiarity of replace actually well, but would have remembered that regex solves my problem. I forgot about the `/g` flag. I switch programming languages too often lately.
