### ISSUE TITLE
Ability to turn off self-signed-certs via environment

### ISSUE THREAD

**Issue by FrankRua** [AnWeber/httpyac#159]
Not sure if this is already possible in the current state (if not I can re-submit as a feature request). I would like the ability to turn off self-signed cert errors when testing an API against localhost. I see you can do it here at a global level: https://httpyac.github.io/guide/troubleshooting.html#turn-off-verification-of-self-signed-certificate

Is it possible you can have this option configured just for a *specific* environment?

**Comment by AnWeber** [comment]
create a `.httpyac.js` (or `httpyac.config.js`) file in the root of your project with this content

```
module.exports = {
  configureHooks: function (api) {
    api.hooks.replaceVariable.addHook('rejectUnauthorizedLocalhost', function (text, type, context) {
      if (type === 'Url' && typeof text === 'string' && request?.url) {
        if (text.indexOf('localhost') >= 0) {
          request.https = request.https || {};
          request.https.rejectUnauthorized = false;
        }
      }
      return text;
    });
  }
}
```
If it is important to set it only in a certain environment, you can determine it by `context.httpFile.activeEnvironments?.indexOf?.('dev') >= 0`.
I'm not sure if I'll include it as a feature, as it makes the api and possibilities even more complicated.

**Comment by AnWeber** [comment]
@FrankRua If the change only affects setting rejectUnauthorized, then a special configuration entry to the environment could solve the problem, like `$request.rejectUnauthorized=true`. Extending the RequestOptions to specify environments would be overkill in my opinion. Do you have another suggestion?
I will look at what other options might be useful.

**Comment by FrankRua** [comment]
@AnWeber Yes, I think you hit the nail on the head. Having the ability to do something like `$request.rejectUnauthorized=true` via your environment object in the config would be perfect.

Like so:
```
dev: { 
$request.rejectUnauthorized=true
}
```

**Comment by AnWeber** [comment]
I had to change the name of the setting to `request_rejectUnauthorized` so that it can also be set via dotenv (does not support $ or @ prefix).

**Comment by FrankRua** [comment]
@AnWeber So in my `httpyac.js` can I now (or when released) just do:

```
localHost: {
request_rejectUnauthorized: true
}

dev: {
request_rejectUnauthorized: false
}
```

Or will it default to false?

**Comment by AnWeber** [comment]
From the [documentation of NodeJS](https://nodejs.org/api/tls.html#tlsconnectoptions-callback):
>  If not false, the server certificate is verified against the list of supplied CAs

I would only configure the value for localHost and use the default for all other systems.

```
localHost: {
request_rejectUnauthorized: false
}
```

**Comment by FrankRua** [comment]
Thank you! 👍
