### ISSUE TITLE
CLI fails to handle Windows directory separators in command-line arguments

### ISSUE THREAD

**Issue by fredrikhr** [AnWeber/httpyac#175]
When running the `httpyac` CLI on Windows, if you specify a path to a file that contains windows directory separators, i.e. `\`, the CLI fails to locate the http file even if it exists and exits with an error message that states that the specified file could not be found.

```
> npx httpyac "path\to\file.http"
httpYac cannot find the specified file path\\to\\file.http.
```

*Whether the path argument is quoted or not does not change the behaviour if quoting is not necessary by the shell.*

This happens in all cases where the path contains a directory separator, i.e.:
- `.\file-in-current-dir.http`
- `subdir\file-in-subdir-relative-to-current-dir.http`
- `C:\absolute-path-dir\file-in-absolute-dir.http`

If you replace the windows-directory separator with a *NIX-like `/` the CLI finds the file and executes it as expected.

If you execute the CLI from the directory the file is located in and specify only the file name, the path specified to the CLI no longer contains directory separators, and thus the CLI also find the file and executes it as expected.

**Comment by AnWeber** [comment]
Error is triggered by globby/fast-glob (see https://github.com/sindresorhus/globby/issues/130). The [syntax](https://github.com/mrmlnc/fast-glob#pattern-syntax) only allows `/` and no `\`. I will replace the `\` with correct `/` if no files were found.

**Comment by fredrikhr** [comment]
But is that better? AFAIK, `\` is a legal escaping character in *NIX-like systems?

**Comment by AnWeber** [comment]
That's why the search for the files first. If no file was found, it was not an escape attempt. I could only add a restriction to Windows systems. That would probably be even better.

**Comment by fredrikhr** [comment]
I would do

```js
const path = require('path');

if (path.sep !== '/') {
  glob_path = original_path.replaceAll(path.sep, '/');
} else {
  glob_path = original_path;
}
```

**Comment by AnWeber** [comment]
And replaceAll is only available from [NodeJS v15](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll#browser_compatibility). But otherwise I use your suggestion

**Comment by AnWeber** [comment]
Update with this change is published. thx
