### ISSUE TITLE
how to return information(variables) from (responseLogging)hooks

### ISSUE THREAD

**Issue by IvoLeist** [AnWeber/httpyac#194]
Dear AnWeber,

I have difficulties to understand the concepts of hooks.
We need some information from the decoded jwt token (e.g. the assignend Keycloak groups)
Of course we can just access the token directly from `response.request.headers["authorization"]`
and add the decode logic to every endpoint call.

However, since we need to get that information in almost every endpoint call
it would be much more convenient if we could just add a hook for that (see below)

```
configureHooks: function (api) {
       api.hooks.responseLogging.addHook('removeSensitiveDataButPreserveKeycloakGroup', function (response) {
       var jwt_decode = require("jwt-decode")
	if (response.request) {
          var decoded = jwt_decode(response.request.headers['authorization'])
          var group = decoded.group[0].replace("/","");
          
          response.meta["kc_group"] = group;
          response.request.headers["kc_group"] = group;

          console.log("response.meta.kc_group >>",response.meta["kc_group"]) 
          // response.meta.kc_group >> group1
          console.log("response.request.headers >>",response.request.headers)
          // response.request.headers.group >> group1
          
          delete response.request.headers['authorization'];
          return response
	  }
	});
}
```
But unfortunately the changes neither in any of objects in the response (e.g. response.meta)
nor the the changes in response.request.headers are preserved outside the hook.

> test.http response.request.headers.kc_group undefined
> test.http response.meta { ip: '127.0.0.1', redirectUrls: [], size: '153 B' }

Is this an expected behavior? If so do you know any workarounds
how we could access variables etc. created by a (responseLogging)hook?

Best,
Ivo

**Comment by AnWeber** [comment]
Is the data only to be displayed or will it be used for a follow-up call?

**Comment by IvoLeist** [comment]
The data (keycloak group) will be used in a following chai.expect in test.http.
e.g. `chai.expect(res).to.include(keycloak_group)`

So this is the work around for now:
```
# test.http
GET {{host}}/grouplist

var jwt_decode = require("jwt-decode")
var chai = require('chai');

var decoded = jwt_decode(response.request.headers['authorization'])
var keycloak_group = decoded.group[0].replace("/","");

chai.expect(res).to.include(keycloak_group);
```

But it would be more convenient to hide the token decode logic within a hook.
*if that is possible?

**Comment by AnWeber** [comment]
simple access to Keycloak is the reason why I started this whole thing:-) If you use my OAuth logic for this, you can simply access the token using variable [`oauth2Session`](https://httpyac.github.io/guide/scripting.html#access-to-variables). I also support a decodeJWT method. 
For the implementation of the test you can use the response hook. In the zip is a simple implementation with `assert`. I noticed that in this case you do not have access to the test method. I will add it.
```
# test.http
GET /actuator/info
Authorization: openid
```

```
//.httpyac.js
const { ok } = require('assert');
module.exports = {
  configureHooks: (api) => {
    api.hooks.onResponse.addHook('kcgroup', function (response, { variables }) {
      const accessToken = api.utils.decodeJWT(variables.oauth2Session.accessToken);
      ok(response.body.indexOf(accessToken.kc_group) > 0);
    });
  }
}
```

```
#.env
host=...
realm=dev
profile=dev
keycloakHost=https://keycloak.int.de
oauth2_authorizationEndpoint={{keycloakHost}}/auth/realms/{{realm}}/protocol/openid-connect/auth
oauth2_tokenEndpoint={{keycloakHost}}/auth/realms/{{realm}}/protocol/openid-connect/token
oauth2_clientId=httpyac
oauth2_clientSecret=aaaaaaaa-bbbb-cccc-dddd-eeeeeeeee
oauth2_scope=openid profile
```

[test.zip](https://github.com/AnWeber/httpyac/files/7981623/test.zip)

> bonus: I assume that you also maintain several services, the plugin and the environments can also be referenced as system variables([`HTTPYAC_ENV`](https://httpyac.github.io/guide/environments.html#dotenv) = dir of env files, HTTPYAC_PLUGIN = location of js file).

use httpyac CLI to debug your script with VSCode Javascript Debug Terminal. VSCode Extension does not allow to reload changes in .httpyac.js. NodeJS caches all require calls.

**Comment by AnWeber** [comment]
It would also be possible with the current version 4.10.2 to also use the TestFactory for better output. If you have any questions just contact me.

**Comment by IvoLeist** [comment]
Dear AnWeber,

I finally found again some time to play with your nifty little tool :)

First thanks for pointing out that there is a decodeJWT in app.utils and how 
easily this can be used to get the keycloak groups from the token.

However, I am afraid I have to reopen that issue again because I am still puzzled
how to get now the group information back to test.http so I can use it there in a test?
(it is not possible to do this test inside the hook because it differs for each endpoint)

Bonus question: I was curious about the mentioned testFactory available in utils
but I somehow fail to find it? A console.log (api.utils) does not include it (v.4.10.2), see below:
```
{
  ENVIRONMENT_NONE: [Getter],
  JAVASCRIPT_KEYWORDS: [Getter],
  assertHasNoResponseBody: [Getter],
  assertHasResponseBody: [Getter],
  assertHeaderContains: [Getter],
  assertHeaderEquals: [Getter],
  assertMaxTotalTime: [Getter],
  assertResponseBodyEquals: [Getter],
  assertResponsetimeLower: [Getter],
  assertStatusEquals: [Getter],
  clearModule: [Getter],
  cloneResponse: [Getter],
  decodeJWT: [Getter],
  defaultConfigFiles: [Getter],
  deleteHeader: [Getter],
  deleteVariableInContext: [Getter],
  evalExpression: [Getter],
  executeGlobalScripts: [Getter],
  expandVariable: [Getter],
  extensionName: [Getter],
  findRootDir: [Getter],
  findRootDirOfFile: [Getter],
  getDisplayName: [Getter],
  getHeader: [Getter],
  getHeaderArray: [Getter],
  getHttpyacConfig: [Getter],
  getMarkdownSyntax: [Getter],
  getPlugins: [Getter],
  getRegionDescription: [Getter],
  gotHttpClientFactory: [Getter],
  initHttpClient: [Getter],
  isError: [Getter],
  isEventSourceRequest: [Getter],
  isGlobalHttpRegion: [Getter],
  isGrpcRequest: [Getter],
  isHttpRegionSendContext: [Getter],
  isHttpRegionsSendContext: [Getter],
  isHttpRequest: [Getter],
  isHttpRequestMethod: [Getter],
  isMQTTRequest: [Getter],
  isMimeTypeCSS: [Getter],
  isMimeTypeFormUrlEncoded: [Getter],
  isMimeTypeHtml: [Getter],
  isMimeTypeImage: [Getter],
  isMimeTypeJSON: [Getter],
  isMimeTypeJavascript: [Getter],
  isMimeTypeMarkdown: [Getter],
  isMimeTypeMultiPartFormData: [Getter],
  isMimeTypeNewlineDelimitedJSON: [Getter],
  isMimeTypePdf: [Getter],
  isMimeTypeXml: [Getter],
  isProcessorContext: [Getter],
  isPromise: [Getter],
  isString: [Getter],
  isStringEmpty: [Getter],
  isWebsocketRequest: [Getter],
  joinMarkdown: [Getter],
  loadModule: [Getter],
  logResponse: [Getter],
  mergeRawHttpHeaders: [Getter],
  parseContentType: [Getter],
  parseError: [Getter],
  parseJson: [Getter],
  parseMimeType: [Getter],
  processHttpRegionActions: [Getter],
  replaceFilePath: [Getter],
  replaceInvalidChars: [Getter],
  replaceVariables: [Getter],
  report: [Getter],
  requestLoggerFactory: [Getter],
  resolveClientCertificates: [Getter],
  resolveModule: [Getter],
  runScript: [Getter],
  setAdditionalResponseBody: [Getter],
  setVariableInContext: [Getter],
  shortenFileName: [Getter],
  sleep: [Getter],
  stateGenerator: [Getter],
  toAbsoluteFilename: [Getter],
  toEnvironmentKey: [Getter],
  toHttpString: [Getter],
  toHttpStringHeader: [Getter],
  toHttpStringRequest: [Getter],
  toHttpStringResponse: [Getter],
  toMarkdown: [Getter],
  toMarkdownHeader: [Getter],
  toMarkdownMeta: [Getter],
  toMarkdownRequest: [Getter],
  toMarkdownResponse: [Getter],
  toMarkdownTestResults: [Getter],
  toMarkdownTimings: [Getter],
  toMultiLineArray: [Getter],
  toMultiLineString: [Getter],
  toNumber: [Getter],
  toProcessedHttpRegion: [Getter],
  toQueryParams: [Getter],
  toString: [Getter],
  triggerRequestResponseHooks: [Getter],
  unsetVariableInContext: [Getter]
}
```

**Comment by AnWeber** [comment]
If the group information is only needed in the same request, then you can simply set it directly to the variables.

```
api.hooks.onResponse.addHook('kcgroup', function (response, { variables }) {
      const accessToken = api.utils.decodeJWT(variables.oauth2Session.accessToken);
      variables.group = accessToken.group
});
```
If it should be available for one of the next requests, the variable must be set by using [setVariableInContext](https://github.com/AnWeber/httpyac/blob/main/src/utils/variableUtils.ts#L58). The reason is that I can respect the scope of variables ([useRegionScopedVariables](https://github.com/AnWeber/httpyac/blob/main/src/models/environmentConfig.ts#L29)). For this to work, I needed an explicit set method.
```
api.hooks.onResponse.addHook('kcgroup', function (response, context) {
      const accessToken = api.utils.decodeJWT(context.variables.oauth2Session.accessToken);
      api.utils.setVariableInContext({group: accessToken.group}, context);
});
```

The [testfactory](https://github.com/AnWeber/httpyac/blob/4.10.2/src/utils/testUtils.ts#L5) should actually already be available in the version. However, I have not tested it. The only advantage would be that it would generate the logs for the CLI output correctly.

**Comment by IvoLeist** [comment]
Thank you for the quick follow up :)
I can confirm that your first snippet works, I have not found any use case to verify the 2nd as well.

One remark for someone else maybe stumbling about this:
If you want to use the variable in your .http file you have to call it w/o the "variables." in front.

Here an example:
```
//httpyac.config.js
api.hooks.onResponse.addHook('kcgroups', function (response, { variables }) {
      const accessToken = api.utils.decodeJWT(variables.oauth2Session.accessToken);
      variables.kcgroups = accessToken.group
});
```
```
#test.http
GET {{host}}/test
Authorization: openid password
{{
  console.log(kcgroups)
}}
```
