### ISSUE TITLE
add --color option 

### ISSUE THREAD

**Issue by jupegarnica** [AnWeber/httpyac#201]
I am having problems with the color output of the cli runnnig it with docker-compose.   

Would be posible to force the color output in the same way it is posible to disabled it with --no-color?

![image](https://user-images.githubusercontent.com/3143445/154460480-1aeb908f-03ca-4db9-99cc-522d53e82f3e.png)

**Comment by AnWeber** [comment]
For color support I currently use `chalk`. This library supports forced colors if the environment variable FORCE_COLOR=2 is set (see https://www.npmjs.com/package/chalk#supportsColor)

> docker-compose.yml
```
....
  environment:
      FORCE_COLOR: 2
...
```

**Comment by AnWeber** [comment]
Test with the following Dockerfile would produce colored output: (added in root of httpyac repo)
```
# syntax=docker/dockerfile:1

FROM node:16.14.0-alpine3.14
COPY . ./app
WORKDIR app

RUN pwd && npm install && \
 npm run compile

ENV FORCE_COLOR=2
VOLUME /app/http
```

```
docker run -v /home/weber/src/httpyac/httpyac.github.io/examples/request:/app/http anweber/httpyac:0.0.1 -- "**/*.http"
```

**Comment by jupegarnica** [comment]
Thank you, i will try it.

By the way, i am loving the project :D

**Comment by AnWeber** [comment]
For me it worked with FORCE_COLOR. But in my use case I don't need the color support. 
I will deploy a managed Docker image and keep that update to date. Only my first attempt with `pack` had failed. But maybe until then I will just use a Dockerfile.

**Comment by jupegarnica** [comment]
It worked perfectly! 

```dockerfile
FROM node:17-alpine
RUN npm i -g httpyac
WORKDIR /test
ENV NODE_ENV=production
ENV FORCE_COLOR=2
COPY . .
CMD ["httpyac","send", "**/*.http", "--all","-e", "production", "-o", "exchange"]

```

**Comment by AnWeber** [comment]
thx for sharing your Dockerfile.
