### ISSUE TITLE
How to use variables inside node script

### ISSUE THREAD

**Issue by itizarsa** [AnWeber/httpyac#215]
I was trying to use a response from an HTTP file inside another HTTP file's node script, but I don't know how to use the response inside the node script.

``` shell
## token.http

@name token
POST http://localhost:7777/abc
Content-Type: application/json

mutation Token($cred: String!) {
  token(cred: $cred) {
    access
  }
}

{
    "cred":"cred-001"
}
```

``` shell
## header.http

# @import ./token.http

{{
   console.log("token---> ", token)

    exports.defaultHeaders = {
        'Content-Type': 'application/json'
    }
}}
```

If I try to use the response name inside the node script, I am getting a `ReferenceError: token is not defined` error.

Could you please help me find out how to use the response named `token` from `token.http` inside `header.http` node script?

**Comment by AnWeber** [comment]
you need to add `# @ref token` or `# @forceRef' . See example: https://httpyac.github.io/guide/metaData.html#import

**Comment by itizarsa** [comment]
Thanks, @AnWeber. Can I add a few httpyac examples? It will be helpful for others

**Comment by AnWeber** [comment]
@itizarsa Gladly. Just submit pull requests to the project [httpyac/httpyac.github.io](https://github.com/httpyac/httpyac.github.io)
