### ISSUE TITLE
Question: how to transform response variables nicely?

### ISSUE THREAD

**Issue by rngtng** [AnWeber/httpyac#235]
I'm looking for a nice way (one-liner?) how to transform/extract data from a response into a variable. Example

```
### Foos
# @name foos
GET /v1/foos
```

returns:

```json
{
 "items": [
    { 
       "id": 1
    }
  ]
}
```

Now I want to continue with the first object in the array:

```
### Foo
# @name foo
GET /v1/foos/{{foos.items[0].id}}
```      

This is ok, but I want to apply `foo` in multiple requests and, given a larger array switch to another array index.  So I have in mind that AFTER the response I store the object in `foo` and can continue:

```
### Foos
# @name foo
GET /v1/foos

{{exports.foo =  foos.items[0].id}}
```

But this doesn't work as it's taken a request body. Any idea how to solve this nicely?

**Comment by AnWeber** [comment]
After the request line I have the problem that the script could be used either for the template in the response body (single line scripts), or as a script to be executed after the response (multi-line scripts). 
Just use the variable notation directly.

```
GET https://httpbin.org/json

@foo={{response.parsedBody.slideshow.author}}

````

**Comment by rngtng** [comment]
oh nice, this indeed works! Wasn't aware of this by just reading the docs. So an inline variable after the request is available in the following one. Done!

**Comment by rngtng** [comment]
sorry need to re-open. just discovered why this didn't work for me before. Your example indeed works nicely, but adopting this to mine (with array/object variable) doesn't:

```
GET https://httpbin.org/json

@slideshow={{response.parsedBody.slideshow}}

###
GET https://httpbin.org/anything?title={{slideshow.author}}
```

Looks like the variable assignment isn't working for objects / array, but string only...

**Comment by AnWeber** [comment]
This is the mistake. This makes no sense in this case: https://github.com/AnWeber/httpyac/blob/main/src/plugins/javascript/javascriptVariableReplacer.ts#L23

**Comment by rngtng** [comment]
Ah I see, thx. So the `toString` cast need just to be removed? or what's the reason to cast here?

**Comment by rngtng** [comment]
ok i'm at least I could reproduce it in this e2e test, see https://github.com/rngtng/httpyac/pull/1/files but my naive approach to remove just the cast failed (of course) ;).

**Comment by AnWeber** [comment]
My test looks similar to this. Actually I encountered a second error, that the variable lazy is replaced and therefore the "response" is possibly no longer present. I am just thinking if I should add another notation `@var:=foo` which does the replacement directly. But I still don't understand why my initial example worked, but it fails in the UnitTest.

**Comment by AnWeber** [comment]
Yes, I had the same thought. Probably `:=` is better or simply `:`.

**Comment by rngtng** [comment]
And why does it have to be a new syntax? Because i do replacement *before* the request?

**Comment by AnWeber** [comment]
I love how when you answer a question, you realize you missed something. Good question:-)

The variables are replaced lazy. But to execute the javascript for url templating, the used variable `slideshow` must have the correct value, but this one was still `{{response.parsedBody.slideshow}}`. The Interceptor for the replacement was only added if a variable is declared in the current httpRegion. 
However, I still left the direct replacement of the variable in, but by using `:`.

**Comment by rngtng** [comment]
Oh cool, so it works even with just single = now? What’s the : notation then good for? 
thanks again for your great and fast efforts

**Comment by rngtng** [comment]
Morning. Good news, it now works as  expected, if string is returned. BUT, if the actual return value is integer it somehow still fails:

WORKS - returning string `"1"`: 
```
const mockedEndpoints = await localServer.forGet('/get')
        .thenReply(200, JSON.stringify({ foo: { test: '1' }}), { 'content-type': 'application/json' });
```

FAILS - returning integer `1`: 
```
const mockedEndpoints = await localServer.forGet('/get')
        .thenReply(200, JSON.stringify({ foo: { test: 1 }}), { 'content-type': 'application/json' });
```

Sorry to keep you busy with that :(

**Comment by AnWeber** [comment]
The difference between `=` and `:=` is because [Postman deal with variables](https://learning.postman.com/docs/sending-requests/variables/) in a different way and I tried to emulate it (https://github.com/httpyac/httpyac.github.io/issues/7).
Postman allows overriding existing variables. The replacement in variable urlWithFoo only occurs on request execution
```
@foo=bar
@urlWithFoo=https://example.org/{{foo}}/test
@foo=notbar
```
On execution urlWithFoo would be `https//example.org/notbar/test`. Instead using `:=` the result would be `https//example.org/bar/test`

**Comment by AnWeber** [comment]
when using `it.only` the test works. Maybe some kind of threading issue with the userSessionStore while test execution. presumably the response between the two requests is changed. 
![strange](https://user-images.githubusercontent.com/13434739/161396804-b21009ae-c304-4387-8a0f-347e47e88742.gif)

**Comment by rngtng** [comment]
ok you're right. It's somehow related to test setup/environment. That's super weird (and not quite trustworthy against the tests). but glad it's fixed.

Understood the difference of `=` and `:=` now. As you mentioned before lazy vs. direct evaluation. I expect direct evaluation as default, good to know it's the other. Lets make sure this gets clear from the docs..

**Comment by rngtng** [comment]
Another finding: My test passes fine if executed before `describe('http')` or with `describe.skip('http')`. So there's somewhere some leakage. Sure this won't happen in 'real' too?

**Comment by AnWeber** [comment]
I suspect not at present. The correct execution is always sequential. Nevertheless, I would also like to understand it in more detail. In principle, there is a bug in the design of the application or test.

**Comment by rngtng** [comment]
Here another confusion. Based on your `=` vs `:=`, I copied the direct replace test for a lazy one. But it fails. What did I get wrong? https://github.com/rngtng/httpyac/pull/2/files

**Comment by AnWeber** [comment]
>Here another confusion. Based on your = vs :=, I copied the direct replace test for a lazy one. But it fails. What did I get wrong? https://github.com/rngtng/httpyac/pull/2/files

Now it gets tricky. The following example explains the current behaviour.

```
@resource=tasks
@host=https://someservice.de/{{resource}}
###
@resource=jobs
GET {{host}}
###
GET {{host}}
```
In the first request the resource `jobs` is to be queried. In the second request the resource `tasks` is to be addressed. So that both are executed one after the other, the variables are currently scoped per area, otherwise @path in the first request would change the second url. To make current httpyac easier to use, newly created variables are automatically shared.
This is exactly what happens in your test. The first response is still automatically shared, because it was newly created. But the second response is suppressed, because it would overwrite previous response variable. response variable remains the first response.

I have the feeling that the system with the lazy variables is somehow broken. I don't use the lazy variables myself because it's not what I would expect. And I have not discovered the behavior in >6 years of postman use.
I'm just leaning towards swinging back to direct replacement and making the lazy variables optional (swap `=` and `:=`).

**Comment by rngtng** [comment]
Correct. you example aligns how I understood it. But check this example. It still doesn't align to it:

```
@host = https://httpbin.org
@traceId={{response.parsedBody.headers}}
# or @traceId={{response.parsedBody.headers}}
###
GET /anything?traceId1={{traceId["X-Amzn-Trace-Id"]}}

###
GET /anything?traceId2={{traceId["X-Amzn-Trace-Id"]}}

###
GET /anything?traceId3={{traceId["X-Amzn-Trace-Id"]}}
```

traceId2 & traceId3 are always the same, as I'd expected that with `=` they'd differ.

I agree. Keep it simple and intuitive. Direct replace is IMHO what's expected and should be `=`. if lazy is required, then `:=` could be an option..

**Comment by rngtng** [comment]
btw. I've in mind to adapt  the e2e to work fully on httpbin.org too. so one could run them even w/o the mock to ensure the test or framework doesn't influence the execution..

**Comment by AnWeber** [comment]
@rngtng seems to be a good idea. But please only optional.

**Comment by AnWeber** [comment]
> traceId2 & traceId3 are always the same, as I'd expected that with = they'd differ.

why should the traceIds change? I always get the same header.

**Comment by AnWeber** [comment]
I have released the current state with v5.3.0.

**Comment by rngtng** [comment]
cool, thanks for the release.

> why should the traceIds change?
with current state they do always change. Both lazy and direct, as `@traceId={{response.parsedBody.headers}}` is only defined global. But adding `@traceId={{response.parsedBody.headers}}` AFTER request 1, ensure that the value is same for request2 & request3:

```
@host = https://httpbin.org
@traceId={{response.parsedBody.headers}}
###
GET /anything?traceId1={{traceId["X-Amzn-Trace-Id"]}}

@traceId={{response.parsedBody.headers}}
###
GET /anything?traceId2={{traceId["X-Amzn-Trace-Id"]}}

###
GET /anything?traceId3={{traceId["X-Amzn-Trace-Id"]}}
```

I'm closing this issue, as we're quite OT anyway and my initial problem is fixed. I'll open another one in case I see bugs/issues with the test cases.

Again, thanks a lot for your efforts

**Comment by rngtng** [comment]
btw. just bump my files & plugins to latest version. It a looks good now, the response var transform makes it soooo nice! thx
