### ISSUE TITLE
Dynamically disabling a request does not seem to work

### ISSUE THREAD

**Issue by gerukin** [AnWeber/httpyac#240]
I think I found another issue... or maybe the [manual](https://httpyac.github.io/guide/metaData.html#disabled) needs to be updated... or maybe I'm missing something. 🤔

Here's the code:
```
### Don't want me to? I'll run anyway!
{{
  // This line would raise an error because `metaParams` is undefined
  // httpRegion.metaParams.disabled = true

  // This raises no error but doesn't stop execution
  httpRegion.metaParams = { disabled: true }
}}

https://httpbin.org/bin/status/200

### Fine, I won't run
# @disabled

https://httpbin.org/bin/status/200
```

Tried each request manually in vs-code and both together using the CLI. Same results.
🙏

**Comment by AnWeber** [comment]
The error was in the documentation and has been corrected. This is a correct example.
```
{{
  httpRegion.metaData.disabled = true
}}

https://httpbin.org/bin/status/200
```
