### ISSUE TITLE
Different dynamic variable behavior in vscode vs CLI

### ISSUE THREAD

**Issue by gerukin** [AnWeber/httpyac#241]
Given this test file:
```
{{
  const body = { id: '{{$guid}}', hello: 'world' }
  module.exports._testBody = body
}}

### Test 2
POST https://httpbin.org/post
Content-Type: application/json

{{_testBody}}
```

Vscode sends this json body:
```json
{
  "hello": "world",
  "id": "e1748ac8-017c-46c1-8941-f40d2acd9ddf"
}
```

Whereas the CLI sends:
```json
{
  "id": "{{$guid}}",
  "hello": "world"
}
```

Now of course, looking at the [manual](https://httpyac.github.io/guide/variables.html#rest-client-dynamic-variables) I wasn't really expecting it to work in scripts at all (I know it works fine in the http part), but I was surprised to see it work in in vscode.

In some of my use cases I need to generate the body dynamically and while I could find a uuid library to generate that part, perhaps it might make sense to expose the dynamic variables as a set of utility functions. Any plans to make these dynamic variables available in the scripts in some form?

**Comment by AnWeber** [comment]
For me it works the same in both applications

![241](https://user-images.githubusercontent.com/13434739/161606327-5cf3536b-0a01-462e-9612-3884a6761a5f.gif)

I can only imagine that it only works if the variable is already a string. But then this works in both applications. The reason for the difference is the data type of `_testBody` as soon as this is a string, a substitution takes place. In your example the object is [converted to a string only after the replacement](https://github.com/AnWeber/httpyac/blob/main/src/plugins/core/request/requestVariableReplacer.ts#L41).

```
{{
  const body = { id: '{{$guid}}', hello: 'world' }
  module.exports._testBody = JSON.stringify(body)
}}

### Test 2
POST https://httpbin.org/post
Content-Type: application/json

{{_testBody}}
```
.

**Comment by gerukin** [comment]
Ah, my bad!

There is a version mismatch between my CLI (`v5.3.0`):
<img width="466" alt="Screen Shot 2022-04-05 at 8 08 47" src="https://user-images.githubusercontent.com/36127103/161647182-ce7987f3-d5ac-4221-8576-201e9eaac34d.png">

... and the vscode extension (`v5.2.3`):
<img width="1129" alt="Screen Shot 2022-04-05 at 8 05 04" src="https://user-images.githubusercontent.com/36127103/161647214-523ab5e3-6544-4d71-b4e6-e55118adb4c6.png">

I haven't tested the CLI on `v5.2.3` so I'm not sure if the automatic replacement works there. This might be an extra [breaking change for 5.3.0](https://github.com/AnWeber/httpyac/releases/tag/5.3.0).

So just to recap, your intended behavior is that:
1. it should work the same in both the CLI and extension -> makes the most sense to me
2. variable replacement only happens once in the http section, but not inside the replaced variable value itself -> makes the most sense to me
3. utils are available for some dynamic variables in scripts (currently `uuid` and `dayjs`) -> also makes sense to me

---

As far as I can tell vscode doesn't see the latest httpyac extension version yet so I haven't upgraded to that yet.

**Comment by AnWeber** [comment]
I'm surprised, though, because there has been a new version since 03.04. Both in the [Marketplace](https://marketplace.visualstudio.com/items?itemName=anweber.vscode-httpyac) and in [openvsx](https://open-vsx.org/extension/anweber/vscode-httpyac)


<img width="927" alt="image" src="https://user-images.githubusercontent.com/13434739/164072632-f1f40cb9-5aa9-42bb-8fd1-d24e51bc5dd7.png">
