### ISSUE TITLE
--bail cli option got accidentally removed

### ISSUE THREAD

**Issue by JanAhrens** [AnWeber/httpyac#269]
In httpyac cli 5.4.0 the `--bail` option isn't working. ~~While checking all the options, I also noticed that `--editor` also got removed~~

It seems that ~~both options weren't~~ bail wasn't migrated during the refactoring that introduced the `commander` library: https://github.com/AnWeber/httpyac/commit/e7e4459e9744ff5375b1775a463a0c4414ad81bb

**Comment by JanAhrens** [comment]
The fix seems to be easy. Can I try to provide a PR @AnWeber?

**Comment by JanAhrens** [comment]
It looks like `--editor` got removed on purpose. So I wouldn't introduce that again in my PR. I was able to successfully test the `--bail` option by adding it to the list again on my local machine.  https://github.com/AnWeber/httpyac/blob/679423af7cc7eaa139d68d90a5285d415eb217e3/src/cli/send/send.ts#L17-L43

**Comment by JanAhrens** [comment]
I'll be opening a pull request for this in the next days (hopefully). Just wanted to ask before I start working on this.

**Comment by AnWeber** [comment]
@JanAhrens I think your commit to your fork would already fix the bug. I would have just tested it successfully. I would also leave out the `--editor` option. It was an idea, but didn`t really work well and only introduced complexity.

**Comment by JanAhrens** [comment]
Thanks for already trying it out. Since I did the change from the webui, I at least wanted to run the tests and see if I break anything before submitting the PR. Seems to look good. I've just opened #271
