### ISSUE TITLE
console log of cli with error is missing current httpRegion title/ name

### ISSUE THREAD

**Issue by AnWeber** [AnWeber/httpyac#275]
Behavior is noticed in Bug: #245

Running this (same as before):
```
# @import ./common.http
{{
  module.exports = require('../../tests/')
}}

### Test 1
# @ref common
https://httpbin.org/status/200

{{
  tests.status.is(test, response, { val: 200 })
}}

### Test 2
POST https://httpbin.org/post
Content-Type: application/json

{{_undefinedStuff}}

{{
  tests.status.is(test, response, { val: 200 })
}}
```

I get this:
```
---------------------

=== Test common ===

GET https://httpbin.org/status/200
=> 200 (751 ms, 184 B)
✓ Status is valid

---------------------

=== Test 1 ===

GET https://httpbin.org/status/200
=> 200 (555 ms, 184 B)
✓ Status is valid
expression _undefinedStuff throws error
https://httpbin.org/post {
  protocol: 'HTTP',
  url: 'https://httpbin.org/post',
  method: 'POST',
...
```

1. Run `test 1`:
    1. Run @ref (`common`) => `common` header + result (ok)
    2. Run `test 1` => `test 1` header + result (ok)
2. Running test 2 => no header + result (error)

The order now seems fine, but the throw may prevent the proper logging of the test info.

**Comment by rngtng** [comment]
Yes I figure the same problem. Even with your new Assert API I'm testing `?? status == 200` - but I can't see form the output  on which line / region this fails.
<img width="775" alt="Screenshot 2023-06-20 at 23 29 16" src="https://github.com/AnWeber/httpyac/assets/23027/668c1177-6cb0-4813-863e-e1ec83be1ffb">

**Comment by AnWeber** [comment]
@rngtng Should be fixed with this release

**Comment by rngtng** [comment]
Super! Thanks
