### ISSUE TITLE
How to reference all instances created in a @loop statement?

### ISSUE THREAD

**Issue by JanAhrens** [AnWeber/httpyac#279]
I'm trying to create a test-script that calls a (POST) endpoint multiple times and then uses the results of each call in subsequence calls.

This is what I've tried: 
```
# @name uuid
# @loop for 2
GET https://httpbin.org/uuid

###

# @ref uuid
# @loop for item of uuidList
POST https://httpbin.org/post
Content-Type: application/json

{
    "item": "{{item.uuid}}"
}
```

Unfortunately this fails with:

```
ERROR: ReferenceError - uuidList is not defined
ReferenceError: uuidList is not defined
	at Object.<anonymous> (demo.http:9:20)
	at t9 ($HOME/.vscode/extensions/anweber.vscode-httpyac-5.4.1/dist/extension.js:151:40879)
	at Object.nSe [as evalExpression] ($HOME/.vscode/extensions/anweber.vscode-httpyac-5.4.1/dist/extension.js:151:41428)
	at bIt.iterateForOfLoop ($HOME/.vscode/extensions/anweber.vscode-httpyac-5.4.1/dist/extension.js:150:45758)
	at iterateForOfLoop.next (<anonymous>)
	at bIt.iterate ($HOME/.vscode/extensions/anweber.vscode-httpyac-5.4.1/dist/extension.js:150:45540)
	at iterate.next (<anonymous>)
	at bIt.beforeLoop ($HOME/.vscode/extensions/anweber.vscode-httpyac-5.4.1/dist/extension.js:150:45010)
	at OW.<anonymous> ($HOME/.vscode/extensions/anweber.vscode-httpyac-5.4.1/dist/extension.js:1:4989)
	at Generator.next (<anonymous>)
```

I know that using the `<variableName>List` variable is an undocumented feature that I found while reviewing the code:

https://github.com/AnWeber/httpyac/blob/a6559fca27509aa35fd4427b4866ab496633cff9/src/plugins/core/metaData/loopMetaDataHandler.ts#L90

Is there maybe a better way of referencing all results of a `@loop for n` statement?

**Comment by AnWeber** [comment]
> I know that using the <variableName>List variable is an undocumented feature that I found while reviewing the code:

I just forgot to mention it, but should work.

> What's weird is that there are 8 requests while it should only be 4 requests.

Spontaneously I would say it's a bug related to the recent refMetaHandler adjustments. I will have a look at it soon, but I would create an extra ticket for this

**Comment by AnWeber** [comment]
To the original problem. It is because of how loopMetaHandler is currently implemented. This is not executed directly at the expected position, but wraps around all statements in the scope (using [interceptor beforeLoop](https://github.com/AnWeber/httpyac/blob/main/src/plugins/core/metaData/loopMetaDataHandler.ts#L63)). In short `# @ref uuid` is not yet executed when already the result is expected.
As a workaround I could now offer to create an extra region that encapsulates both calls
```
# @name uuid
# @loop for 2
GET https://httpbin.org/uuid

###
# @name postUuid
# @loop for item of uuidList
POST https://httpbin.org/post
Content-Type: application/json

{
    "item": "{{item.uuid}}"
}

###
# @name moreLoops
# @ref uuid
# @ref postUuid
```
If you manually execute the `uuid` request and only then the post request it works correctly too. I'm wondering if it wouldn't make sense to execute all `# @ref ...` already during `beforeLoop`. I wonder if it would make sense to execute all `# @ref ...` already during `beforeLoop`, or it would be better to see this as a restriction of `# loop ` (but with documentation)

**Comment by JanAhrens** [comment]
Thanks for taking a look and getting back.

> If you manually execute the uuid request and only then the post request it works correctly too

What I found out is that it works in the httpyac cli version and it *doesn't* work in the vscode plugin. Could it be that the refMetaHandler adjustment you mentioned only affected the vscode plugin? 

I wasn't able to confirm that the workaround that you posted works. Isn't the problem that a `@loop` statement isn't able to reference any value created by an httpRegion? 

>  I wonder if it would make sense to execute all # @ref ... already during beforeLoop, or it would be better to see this as a restriction of # loop (but with documentation)

I believe it would be quite powerful to be able to loop over data that other http endpoints return. If that's not technically feasible then it should be documented.

**Comment by AnWeber** [comment]
I have adjusted the execution of the loop. This starts the loop process now only, at the position in the HttpRegion. That means scripts and statements before the loop are executed once. Everything after loop statement inside the loop.

**Comment by AnWeber** [comment]
With v5.4.2 the fix for the bugs is released. Thanks for reporting.

**Comment by JanAhrens** [comment]
Thanks for fixing this. I really appreciate it.
