### ISSUE TITLE
httpyac not recognizing http-client.env.json files on WSL

### ISSUE THREAD

**Issue by garywoodfine** [AnWeber/httpyac#281]
I've run into an issue that only seems to happen on Windows Subsystem for Linux (WSL).  Which is quite irritating and I'm hoping you could end my frustration :-)

I have a project set up where I have my project set up as follows:
```shell
.
├── Asserts
│   ├── Should_be_200_OK.js
│   └── Should_be_201.js
├── http-client.env.json
├── .httpyac.json
├── Integration.Tests.csproj
└── Tests
    └── post-tests.http
```

When I run the command  the command below on Linux or Mac it works as expected and is great

`httpyac ./tests/Integration.Tests/Tests/*  --all  -e dev --json`  or `httpyac ./tests/Integration.Tests/Tests/*  --all  -e dev -o short`

However, when it comes to Windows and even though I am using Windows Subsystem for Linux (ubuntu)  the command fails 

`ReferenceError: host is not defined`   which seems to indicate HttpYac can't find the `http-client.env.json` where all environment variables have been defined.

This only seems to happen on WSL though!

Feel free to check out the sample project https://github.com/Geek-I-Am/post-service

The really annoying things is when I run the tests in Rider on Windows they work as expected!  So I know the tests work. and if I run the tests on any other OS using the HttpYac they work.  It's only Windows that is the issue.

 I predominantly use Jetbrains IDE's i.e. Webstorm, Rider, IntelliJ etc. so tend write and run the tests in during development using  the built in runners of the IDE's.

So our use case here, its to be able to use **httpYac CLI** tool to run the integration tests on an environment i.e. staging etc to execute tests etc. 

So our `http-client.env.json` would have environment settings for each environment .

We have stumbled onto a Workaround  where we can create a `dev.env` file which replicates the settings but in a `.env` which works but unfortunately means we have to maintain two settings files :-(

**Comment by garywoodfine** [comment]
@AnWeber  I mistakenly raised this issue in https://github.com/AnWeber/vscode-httpyac/issues/124,  but I was actually refering to the httpyac cli.  I thought I'd bring the issue here for completeness

**Comment by AnWeber** [comment]
I transfered issue #282 from vscode-httpyac repo to httpyac repo:-)
