### ISSUE TITLE
Variables have different interpretation depending on their area of usage

### ISSUE THREAD

**Issue by rngtng** [AnWeber/httpyac#285]
Tickets targets an issue found in https://github.com/AnWeber/httpyac/issues/284. 

Variables have different interpretation/replacement depending on their area of usage.  Depending if its used in query, header or body the value is different and as of that confusing. I'd expect they are everywhere the same. See this example:

```
{{
module.exports = {
  baz: "works",
  foo: {
    bar: "{{baz}}"
  },
}
}}
POST https://httpbin.org/anything?{{foo}}
Test: {{foo}}

{{foo}}
```

Results in:

```
{
  "args": {
    "{\"bar\":\"works\"}": ""
  },
  "data": "{\"bar\":\"{{baz}}\"}",
  "headers": {
    "Test": "[object Object]",
     ...
  },
...
}
```

As you already mentioned in https://github.com/AnWeber/httpyac/issues/284#issuecomment-1133249257 I understood one reason is due to the nameVariableReplacer vs javascriptVariableReplacer. This makes sense, but what about to keep is consistant?

**Comment by AnWeber** [comment]
The difference in that the header can also have other data types except string and here no automatic data type conversion takes place. Request body can always be string and buffer only. Here automatic conversion after replacement has been included as a feature. You could achieve an identical behavior if you already use the correct target data type and do not depend on the automatic conversion. 

One idea would be to introduce a different automatic conversion depending on the request type (HTTP, WS, GRPC, ...), which knows the expected data type. This will probably work well for the request body. For the request headers there are pitfalls.
- What conversion should happen if a http request header is a array of number, to string or to array of string
- The conversion must be different per request type (HTTP, GRPC, RabbitMQ). This complicates an extension by means of plugins.

**Comment by rngtng** [comment]
Thanks for you explanation. It's understood. (and more a feature than a bug ;). Closing the ticket..
