### ISSUE TITLE
[ feature request ] curl support?

### ISSUE THREAD

**Issue by zuisong** [AnWeber/httpyac#301]
just like https://github.com/Huachao/vscode-restclient/blob/master/src/utils/curlRequestParser.ts

**Comment by AnWeber** [comment]
I must confess that I have not yet understood the purpose of the implementation in vscode-restclient. One can easily execute the `curl` call directly in the terminal. What is the advantage of replacing this with an incomplete implementation (not all arguments are supported by vscode-restclient, not all protocols)? 
An implementation of the parser would be possible similar to [requestHttpRegionParser](https://github.com/AnWeber/httpyac/blob/main/src/plugins/core/parse/requestHttpRegionParser.ts) (also as a standalone plugin like [httpyac-plugin-yaml-body](https://github.com/rngtng/httpyac-plugin-yaml-body)). A PR is welcome for that.

**Comment by zuisong** [comment]
support HTTP protocols   should be enough. 

for example , I can copy a request as curl from browser ,  then copy to httpyac script, then change some parameters  

PR...  I would  like to try it.    Emmmm , May be It's hard to me...

**Comment by zuisong** [comment]
In other words, Can we import curl command as request in `vscode-httpyac` ?
