### ISSUE TITLE
[gRPC] Error: illegal name ';'

### ISSUE THREAD

**Issue by gianlucaparadise** [AnWeber/httpyac#303]
I get a parse error when I use a protofile with root-level annotations.

The error I get is:
```
Error: illegal name ';' (/Users/user.name/dev/my-service/my-service.proto, line 18) 
 at b (/Users/user.name/.vscode/extensions/anweber.vscode-httpyac-5.5.2/dist/extension.js:26:1546)
 at Ae (/Users/user.name/.vscode/extensions/anweber.vscode-httpyac-5.5.2/dist/extension.js:26:6030)
 at le (/Users/user.name/.vscode/extensions/anweber.vscode-httpyac-5.5.2/dist/extension.js:26:5923)
 at Hu (/Users/user.name/.vscode/extensions/anweber.vscode-httpyac-5.5.2/dist/extension.js:26:7440)
 at u (/Users/user.name/.vscode/extensions/anweber.vscode-httpyac-5.5.2/dist/extension.js:19:33274)
 at /Users/user.name/.vscode/extensions/anweber.vscode-httpyac-5.5.2/dist/extension.js:19:33844
 at /Users/user.name/.vscode/extensions/anweber.vscode-httpyac-5.5.2/dist/extension.js:19:303
 at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
```

And the protofile I'm using is something like this:
```proto
syntax = "proto3";
package myService;

import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";

option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
	host: "my-service.gianlucaparadise.com"; // This ';' makes the parser complain
	schemes: HTTPS;
};

service MyService {
  rpc GetUsers(GetUsersRequest) returns (Users) {
    option (google.api.http) = {
      get: "/users"
    };
  }
}
```

### About annotations

* I'm using [protoc-gen-openapiv2](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-openapiv2/options/annotations.proto) annotations to modify some properties in the auto-generated swagger
* [Here](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/examples/internal/proto/examplepb/a_bit_of_everything.proto#L19) you can find an example of usage of the `protoc-gen-openapiv2` annotations.

Thanks for your help!

**Comment by AnWeber** [comment]
I'm afraid I have some bad news. The error was already reported to me in httpyac/httpyac.github.io#31. The cause is an error that has already been reported in protobufjs/protobuf.js#1534. The best thing you can do is vote to fix the issue in the protobufjs/protobuf.js library. I always include updates in a very timely manner.

**Comment by AnWeber** [comment]
one more addition. [protobuf.js release v7.0.0](https://github.com/protobufjs/protobuf.js/blob/protobufjs-v7.0.0/src/parse.js#L637) 2 days ago contains the fix apparently. As soon as protoloader has been updated, I can test it.
