### ISSUE TITLE
Parse response body into a variable

### ISSUE THREAD

**Issue by anish749** [AnWeber/httpyac#313]
Thanks for writing this is an amazing client.

I am using this to create some seed data / tests for a project. We already had a bunch of `.http` files that we were running in VS Code, and I wanted to have them run via docker.

How do I access the response of the immediate previous request, and store that to a variable? For instance, my `.http` file when used in [vs code](https://github.com/Huachao/vscode-restclient/) looks as follows:

```http
# @name create
POST http://{{host}}/create
content-type: application/json
accept: application/json
authorization: {{auth_header}}

{
    "name": "Peter",
    "description": "Not Spiderman"
}

### Update 
# @name update
@id = {{create.response.body.$[0].uuid}}

PATCH http://{{host}}/update
content-type: application/json
accept: application/json
authorization: {{auth_header}}

{
    "uuid" : {{id}}
    "name": "Peter Parker"
}
```

The above works fine in vscode, but fails complaining `response` is not defined.

**Comment by AnWeber** [comment]
I have simplified the example for me that I can also run it. 
```
# @name create
POST https://httpbin.org/post
content-type: application/json
accept: application/json

{
    "name": "Peter",
    "description": "Not Spiderman"
}

### Update
# @name update
@id = {{create.json.description}}

PATCH https://httpbin.org/patch
content-type: application/json
accept: application/json

{
    "uuid" : "{{id}}"
    "name": "Peter Parker"
}
```

Actually vscode and cli behave identically here. However, it depends on the command used.

* `httpyac test.http --all` behaves identically, since here the variables from the first request are still present in the working memory and are also used.
* `httpyac test.http --interactive` does also keep the app open and and thus saves the variables. However, the requests must be used in the correct order
* only executing `httpyac send.http` stops the application after the first call and empties the RAM. So I actually always use [`# @ref` to mark dependencies between requests](https://httpyac.github.io/guide/metaData.html#ref-and-forceref). My program will then automatically call the other request.

```

### create
POST https://httpbin.org/post
content-type: application/json
accept: application/json

{
    "name": "Peter",
    "description": "Not Spiderman"
}

### update
# @ref create
@id = {{create.json.description}}
PATCH https://httpbin.org/patch
content-type: application/json
accept: application/json

{
    "uuid" : "{{id}}"
    "name": "Peter Parker"
}

### delete
DELETE https://httpbin.org/delete
content-type: application/json
accept: application/json

### crud
# @ref create
# @ref update
# @ref delete
```

**Comment by anish749** [comment]
Hello @AnWeber, thanks for taking a look at this. I tried using ref earlier, but probably had missed out somethings. Now, I tried to create a working example with httpbin to reproduce the problem..
My goal is come up with an identical script that can be used for vscode as well as httpyac.

The following works with VS Code, but not with httpyac:
```http
### create
# @name create_uuid

GET https://httpbin.org/uuid
content-type: application/json
accept: application/json


### use
# @name use_uuid
@created_uuid = {{create_uuid.response.body.uuid}}

POST https://httpbin.org/anything
content-type: application/json
accept: application/json

{
    "uuid": "{{created_uuid}}"
}
```

The following works with httpyac, but not with vscode:
```http

### create
# @name create_uuid

GET https://httpbin.org/uuid
content-type: application/json
accept: application/json


### use
# @name use_uuid
# @ref create_uuid
@created_uuid = {{create_uuid.uuid}}

POST https://httpbin.org/anything
content-type: application/json
accept: application/json

{
    "uuid": "{{created_uuid}}"
}

```
I am changing `@created_uuid = {{create_uuid.response.body.uuid}}` to `@created_uuid = {{create_uuid.uuid}}` for it to work with htppyac and adding the `@ref ..`


My expected output from both scripts for the second request should contain the following key (with any valid uuid):
```json
{
  "json": {
    "uuid": "e9a2a261-22fe-4d8f-acdd-0477d2baa46a"
  }
}
```
All of this works perfectly fine when I change `@created_uuid = {{create_uuid.response.body.uuid}}` to `@created_uuid = {{create_uuid.uuid}}`, but that means I have to write two different scirpts, one for vs code and one for httpyac.

My current output when I run version that works with VS code, with httpyac is `TypeError: Cannot read properties of undefined (reading 'body')`

**Comment by AnWeber** [comment]
I think in vscode you are not using [vscode-httpyac](https://marketplace.visualstudio.com/items?itemName=anweber.vscode-httpyac) but [vscode-restclient](https://marketplace.visualstudio.com/items?itemName=humao.rest-client). Do you start the call via the CodeLens `Send` or `Send Request`. `Send Request` is [vscode-restclient](https://github.com/Huachao/vscode-restclient). I tried to be API compliant with vscode-restclient, however, I unfortunately missed this spot initially and then found it more intuitive.

<img alt="image" src="https://user-images.githubusercontent.com/13434739/180701027-112bc3b9-8eff-47a1-8d4d-9daef4c722c5.png">

**Comment by anish749** [comment]
Ohh thanks, thats correct, didn't realise that they were different clients... I'll try out the `vscode-httpyac`
One more question, how to access the response headers in this syntax? I tried `created_uuid.headers`, it didn't through an error, but it wouldn't substitute.

**Comment by AnWeber** [comment]
For this use case I added a variable `{name}}Response` in your case `created_uuidResponse`. see https://github.com/httpyac/httpyac.github.io/blob/main/examples/metaData/name_header.http
