### ISSUE TITLE
Is there a way to suppress oauth token requests from log?

### ISSUE THREAD

**Issue by dinurp** [AnWeber/httpyac#322]
I am trying to remove sensitive information from the log. I was able to use example for plugin to suppress authorization header. But I was not able to suppress the oauth token request initiated automatically.  This request did not reach the plugin. Is there are way to completely suppress this request from the log when using CLI? 

for example
if I execute the following request 
```
###
# @name get_request_with_auth
GET /something
Authorization: oauth2 code
```
with
```
httpyac -n get_request_with_auth
```
the log shows 2 requests:
```
---------------------

POST https://oauth.server/oauth2/token
accept: */*
accept-encoding: gzip, deflate, br
content-length: 121
content-type: application/x-www-form-urlencoded
user-agent: httpyac

grant_type=authorization_code&code=0000&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fcallback

HTTP/1.1 200  - OK
cache-control: private,no-cache,no-store
connection: close
content-encoding: gzip
content-type: application/json;charset=UTF-8

{"access_token":"--","refresh_token":--","scope":"openid","id_token":"-","token_type":"Bearer","expires_in":3600}

---------------------

GET https://host/
accept: */*
accept-encoding: gzip, deflate, br
user-agent: httpyac

HTTP/1.1 200  - OK
connection: close
content-length: 975
content-type: application/json; charset=utf-8

{
..
}
```
I would like to suppress the first request from the log.

**Comment by AnWeber** [comment]
At some point I decided to log all the requests and responses I sent. The idea was that it would be easier to understand what was happening. You can suppress the logging with a hook. Just create a file `.httpyac.js` with the following content. But maybe adjust the conditions depending on the purpose. You can also exclude sensitive data from logging.

```js
module.exports = {
	configureHooks: function (api) {
		api.hooks.responseLogging.addHook('removeSensitiveData', function (response) {
			if (response.request) {
				delete response.request.headers['authorization'];
			}
		});

               api.hooks.responseLogging.addHook('no internal requests', function (response, context) {
			if (!context.httpRegion.response) {
				return api.getHookCancel();
			}
		});
	}
}
```

**Comment by dinurp** [comment]
Thanks. 
That did the trick.
