### ISSUE TITLE
Cookie header does not support variables

### ISSUE THREAD

**Issue by michal-kralik** [AnWeber/httpyac#352]
I may be doing something completely wrong, but can't figure out a way to accept variables in the cookie header.

```
@ck=random_id
PUT http://localhost/v1/api HTTP/1.1
Content-type: application/json; charset=utf8
Accept: application/json
Cookie: session={{ck}}
```

The request sent contains `Cookie: session={{ck}}` instead of `Cookie: session=random_id`

Is this expected behavior?

**Comment by AnWeber** [comment]
No, not expected. None of my services use cookies, and I just forgot to use the replace method. I will change it. Workaround would be to set cookie header in script notation.

```
{{
request.headers.cookie = Math.random()
}}

PUT ...

```

**Comment by AnWeber** [comment]
With v5.8.0, variables in the header are also replaced. thx

**Comment by michal-kralik** [comment]
Awesome, works great. Thank you for such a great extension.
