### ISSUE TITLE
$processEnv not working in versions 5+

### ISSUE THREAD

**Issue by dlmorais-13** [AnWeber/httpyac#370]
Hi,

After upgrading vscode extension to latest version (v5.8.3), variable substitution using `$processEnv` stopped working.
If I rollback to latest 4+ version (v4.10.2) the request works normally.

Here is the way I use the variable substitution.
```http
# @name *REDACTED*
GET *REDACTED*
Authorization: Basic {{$processEnv *REDACTED*}}:{{$processEnv *REDACTED*}}
```

And the error being displayed.
```
/test.http:237 exports.$result = ($processEnv *REDACTED*); ^^^^^^^^^^ 
SyntaxError: Unexpected identifier at new Script (node:vm:100:7) at 
createScript (node:vm:257:10) at Object.runInContext (node:vm:288:10) at 
N$ (/home/daniel/.vscode-server/extensions/anweber.vscode-httpyac-5.8.3/dist/extension.js:191:43309) at 
zCe (/home/daniel/.vscode-server/extensions/anweber.vscode-httpyac-5.8.3/dist/extension.js:191:43961) at 
/home/daniel/.vscode-server/extensions/anweber.vscode-httpyac-5.8.3/dist/extension.js:191:47073 at 
Jh (/home/daniel/.vscode-server/extensions/anweber.vscode-httpyac-5.8.3/dist/extension.js:190:30551) at 
Object.V3t [as action] (/home/daniel/.vscode-server/extensions/anweber.vscode-httpyac-5.8.3/dist/extension.js:191:47038) at 
I2e.<anonymous> (/home/daniel/.vscode-server/extensions/anweber.vscode-httpyac-5.8.3/dist/extension.js:1:5641) at 
Generator.next (<anonymous>)
```

**HttpYac**: 5.8.3
**Node:** v16.18.1
**VsCode:** 1.74.1

**Comment by AnWeber** [comment]
@dlmorais-13 
1. Actually, I did not remove nor adjust the `$processEnv` support. I have now also secured the support by means of a unit test. And also tested it manually. It should actually fit. The usage is case sensitive, maybe this is the problem.
2. For the next version I have added a possibility to display the variables readable by my extension. For me the support looks good. I see variables from zsh environment via WSL remote development (IDE started with `code .` in zsh shell). In the Github Issues of vscode you often find the question how to start the IDE concretely. Maybe they are only not available in a certain startup method. Have you ever started the IDE from the bash shell using `code .`?

**Comment by dlmorais-13** [comment]
@AnWeber Thanks for the reply.

1. Good to know that this version still supports this syntax. Is it documented? I didn't find it anywhere in the [guide](https://httpyac.github.io/guide/).

1. I just tested and that's exactly the issue. When started from Windows (i.e.: start menu), my bash exported variables are not available, which is a reasonable behavior, since the connection to WSL is made after IDE initialization. And when started with `code .` from distro bash, then the variables are read successfully.

Now the only think bugging me is that, when started from Windows, if I use `{{$processEnv FOO}}` it's giving the syntax error and when I use `{{process.env.FOO}}` it also doesn't read the variable (expected, it's not available), but without any syntax error. The request is just sent with an empty string where the template is.
So looks like those two syntaxes are behaving differently when the variable is not available. One replaces with empty and the other one doesn't replace with anything at all, which then gives a syntax error.
Maybe it would be better if the syntax `$processEnv` had the same behavior as `process.env.`, if possible.
If you believe this difference in the behavior is not worth developing something to make then similar, you may close the issue, as the original problem is related to variables not being available.

BTW, this new feature you mentioned of displaying variables will be very useful indeed.

**Comment by AnWeber** [comment]
The syntax error is even a deviation from the behavior of rest-client. I correct this and output an empty string in this case.

> BTW, this new feature you mentioned of displaying variables will be very useful indeed.

Please do not expect to much. I only ever show the environment variables and process.env. Runtime variables are only shwon after execution. This feature is a serious performance killer of rest-client and I will not implement it.
