### ISSUE TITLE
Example of how to POST a file to an endpoint

### ISSUE THREAD

**Issue by FrankRua** [AnWeber/httpyac#376]
I am looking to test an endpoint that needs a file to be POST'd to it, how would I sent a request with a file in the form data (multipart/form-data). An example with cURL would be:

```
curl --location --request POST 'https://localhost:44342/ocr/api/v1/ExtractText' \
--form 'vinImage=@"/C:/Users/frank/xxxx.jpg"'
```

via Node `Request`

```
var request = require('request');
var fs = require('fs');
var options = {
  'method': 'POST',
  'url': 'https://localhost:44342/ocr/api/v1/ExtractText',
  'headers': {
  },
  formData: {
    'vinImage': {
      'value': fs.createReadStream('/C:/Users/frank/xxxx.jpg'),
      'options': {
        'filename': '/C:/Users/frank/xxxx.jpg',
        'contentType': null
      }
    }
  }
};
request(options, function (error, response) {
  if (error) throw new Error(error);
  console.log(response.body);
});
```

How would I do this with HttpYac, I was looking in the documentation but couldn't find anything.

Thank you!

**Comment by AnWeber** [comment]
See https://httpyac.github.io/guide/request.html#multipart-form-data for an example.

**Comment by FrankRua** [comment]
> See https://httpyac.github.io/guide/request.html#multipart-form-data for an example.

Oh man I must have completely missed this! Let me try and get back to you. Thank you 😄

**Comment by AnWeber** [comment]
If there are still problems, just report them. thx
