### ISSUE TITLE
Variable replacement in a file is broken in 5.9.10

### ISSUE THREAD

**Issue by mondhs** [AnWeber/httpyac#377]
Scenario:

1. create `request.http` and files `requestBodyImport.json`
2. `alias httpyac="docker run -it -v ${PWD}:/data ghcr.io/anweber/httpyac:5.10.0" `
3. run httpyac "**/*.http" -a

*Current*: variables are not replaces: `{"foo":"{{foo}}"}`
*Expected*: should work same as working with 5.9.0

**Comment by AnWeber** [comment]
All request body imports were now accidentally always imported as buffers. However, only for string the substitution is performed. I have corrected it and added a UnitTest for it

**Comment by mondhs** [comment]
Thank you for quick fix!
