### ISSUE TITLE
Plugin api object structure differs in VSCode and Cli

### ISSUE THREAD

**Issue by woolfas** [AnWeber/httpyac#387]
Steps to reproduce:
1. Create any http script
2. Create any Httpyac plugin
3. Run http script in VSCode (click send in the text editor)
4. Run the same http script in the Cli (I sue Windows 11 pro)
5. Inspect the api object (HttpyacHooksApi) provided as a plugin parameter for both http script execution cases

I suppose the expected result should be that in both execution cases attributes: `HttpyacHooksApi.rootDir`, `HttpyacHooksApi.httpFile.fileName` and `HttpyacHooksApi.httpFile.rootDir` are objects and has the same data structure. E.g.:

<pre>{
    "rootDir": {
        "$mid": 1,
        "fsPath": "c:\\Source\\tools\\project",
        "_sep": 1,
        "external": "file:///c%3A/Source/tools/project",
        "path": "/c:/Source/tools/project",
        "scheme": "file"
    },
    "httpFile": {
        "fileName": {
            "$mid": 1,
            "fsPath": "c:\\Source\\tools\\project\\http_scripts\\script.http",
            "_sep": 1,
            "external": "file:///c%3A/Source/tools/project/http_scripts/script.http",
            "path": "/c:/Source/tools/project/http_scripts/script.http",
            "scheme": "file"
        },
        "rootDir": {
            "$mid": 1,
            "fsPath": "c:\\Source\\tools\\project",
            "_sep": 1,
            "external": "file:///c%3A/Source/tools/project",
            "path": "/c:/Source/tools/project",
            "scheme": "file"
        }
    }
}</pre>

However, actual result is that execution in VSCode gives us the expected api structure (as shown above), but execution in Cli gives us different api structure. In case of Cli execution, all three mentioned attributes become Strings:

<pre>{
    "rootDir": "C:\\Source\\tools\\project",
     "httpFile": {
        "fileName": "C:\\Source\\tools\\project\\http_scripts\\script.http",
        "rootDir": "C:\\Source\\tools\\project",
    }
}</pre>

Not sure if this is expected behavior or not, but it is confusing.

**Comment by AnWeber** [comment]
Yes, it differs and this is the reason for the [PathLike interface](https://github.com/AnWeber/httpyac/blob/main/src/models/pathLike.ts). VSCode supports [Virtual Document}(https://code.visualstudio.com/api/extension-guides/virtual-documents). VSCode abstracts the different file access between local system and remote development systems (WSL, SSH) behind a [FileSystem Provider Api](https://code.visualstudio.com/api/references/vscode-api#FileSystemProvider).
I wanted to support this feature and implemented my own [fileProvider Api](https://github.com/AnWeber/httpyac/blob/main/src/models/fileProvider.ts). CLI directly uses [node:fs](https://github.com/AnWeber/httpyac/blob/main/src/cli/initCliProvider.ts#L21) and VSCode extension implements a [custom Provider using vscode.uri + vcode.workspace.fs](https://github.com/AnWeber/vscode-httpyac/blob/main/src/io/fileProvider.ts#L6).
If you want to cover both scenarios I would recommend you to also go through this interface ([`api.fileProvier`](https://github.com/AnWeber/httpyac/blob/main/src/models/httpHooksApi.ts#L21)). Additionally I implemented some helper methods in [fsUtils](https://github.com/AnWeber/httpyac/blob/main/src/utils/fsUtils.ts). The best way to see how the methods are used is to look at my code. I use basically the same [Hooks Api internally, for all processes](https://github.com/AnWeber/httpyac/tree/main/src/plugins).

**Comment by AnWeber** [comment]
If your plugin becomes more complex, I'll give you the tip to develop it using the httpyac CLI + [Javascript Debug Terminal](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_javascript-debug-terminal). Alternatively just set up my [vscode project setup and develop it that way](https://github.com/AnWeber/vscode-httpyac/blob/main/.github/CONTRIBUTING.md#debug-vs-code-extension--httpyac). So you can see better what happens. Also feel free to come to me with questions. I like to do that.

**Comment by woolfas** [comment]
Thanks a lot! That actually helped me to simplify my code.

By the way, I noticed a minor issue in your code. Looks like you have a misleading parameter names in the FileProvider APIs [joinPath method](https://github.com/AnWeber/httpyac/blob/5d734a334a5f4e9eb0e3b8dfb79fbda171f768cb/src/models/fileProvider.ts#L19).

Based on its implementation, parameter names should be switched: 
`joinPath(path: PathLike, fileName: string): PathLike;`
