### ISSUE TITLE
Reduce information produced in output by send command

### ISSUE THREAD

**Issue by snimavat** [AnWeber/httpyac#396]
The output generated by httpyac contains lots of information, which is useful when debugging, but distracting otherwise.

I tried with `-s` `--quiet` and `--silent` etcc but no luck

This is what i am using

` httpyac send -s -a ./file.http`

And it generates output with the request url, request headers, response headers and response json etc

isnt there a way to log some thing like just request url or name followed by output

**Comment by AnWeber** [comment]
Try `--output body`. This should only log out the body. 
`--output short` logs only status code.

**Comment by snimavat** [comment]
Great, thanks @AnWeber
