### ISSUE TITLE
http-client.env.json is not used

### ISSUE THREAD

**Issue by ckazimie** [AnWeber/httpyac#4]
I am using version v2.3.1 of the command line tool. In the same directory where my test.http file is placed I have http-client.env.json file with the following content:

{
  "dev": {
    "target_host": "http://test.com"
  }
}

When I run 
httpyac -v test.http -e dev

I get this error
ReferenceError: target_host is not defined

The same files work fine in VS Code with httpyac plug-in. I wonder if there is an error in CLI tool or I am doing something wrong calling httpyac

test.http references environment target_host as here:

###
GET {{target_host}}/{{uri}}

**Comment by AnWeber** [comment]
In vscode intellij settings are loaded [automatically](https://github.com/AnWeber/vscode-httpyac/blob/main/package.json#L183). In httpyac this is currently not enabled. I will adjust it with the next version. Until then it can be fixed using .httpyac.json in the root with the following content

**Comment by ckazimie** [comment]
Thank you it works very well after adding this.

**Comment by AnWeber** [comment]
I will adjust it anyway, because this behavior is surprising

**Comment by AnWeber** [comment]
thanks for using my extension:-)
