### ISSUE TITLE
how to use mqtt connect with clientID

### ISSUE THREAD

**Issue by lizhenwei** [AnWeber/httpyac#404]
HI ,I am a new user, I want use httpyac in vscode connect my mqtt server ,In mqtt.fx I can use the following parameters to connect,but in httpyac ,I don't know how to connect mqtt server.
ip :192.168.0.151
port:30611
clientId:abcd
username:"username"
passwrord:"1234"
![image](https://user-images.githubusercontent.com/13379136/221816561-809dee8a-33e8-46e2-a9c4-b14e54a786fe.png)

My httpyac use this code to connect mqtt server and pulish json data,but fail. Thank you for helping me answer

```shell
# @keepStreaming
MQTT tcp://192.168.0.151:30611
{{
   request.options = {
      username: "sfere-public;json;SFB2A-G1",
      password: "sfere-public",
      clientid: "liulaoshi-G1"
  };
}}
###
# @name test
{{
  mqttClient.publish('sdlink/dev/liulaoshi-G1/topic/edition', '{
       "seq": "1x3jkd",
       "version": "v2",
       "sys_init": 0
} ')
}}

```

**Comment by AnWeber** [comment]
The position of your script tag is important. All scripts after the request line is executed after the request. The request options will only set after the request ist executed. Additionally mqttClient was deprecated in the last major release (v6). use `$requestClient.send()` instead (https://httpyac.github.io/guide/request.html#mqtt)

```
# @keepStreaming
{{
   request.options = {
      username: "sfere-public;json;SFB2A-G1",
      password: "sfere-public",
      clientid: "liulaoshi-G1"
  };
}}
MQTT tcp://192.168.0.151:30611
topic: sdlink/dev/liulaoshi-G1/topic/edition

###
# @name test
{{
  $requestClient.send({
       "seq": "1x3jkd",
       "version": "v2",
       "sys_init": 0
  })
}}
```
