### ISSUE TITLE
Rich the document content

### ISSUE THREAD

**Issue by bodypumper** [AnWeber/httpyac#406]
Should need comment information for some variables

For example:
URL：https://httpyac.github.io/guide/request.html#grpc

<img width="1475" alt="image" src="https://user-images.githubusercontent.com/44149782/222343830-b9513ef2-8e26-4740-8abb-f5719337ff7c.png">

**Comment by AnWeber** [comment]
See https://www.npmjs.com/package/@grpc/proto-loader. Will add link for docs in my documentation. You can try grpc requests., but functionality seems to be broken in versions >6.0. will try.to fix it the next days.

**Comment by bodypumper** [comment]
OK, thanks发自我的 iPhone在 2023年3月2日，18:14，Andreas Weber ***@***.***> 写道：﻿
See ***@***.***/proto-loader. Will add link for docs in my documentation. You can try grpc requests., but functionality seems to be broken in versions >6.0. will try.to fix it the next days.
