### ISSUE TITLE
HttYac CLI gets stuck in the infinite loop when using -n option

### ISSUE THREAD

**Issue by woolfas** [AnWeber/httpyac#409]
Steps to reproduce:

Create any http script which has a named request. I used this one:
**simple.http**
```
### Send Fruit
# @name send_fruit
POST https://httpbin.org/anything
Content-Type: application/json

{
        "type": "fruit",
        "name": "Apple"
}
```

Execute: `httpyac -n send_fruit simple.http`

Expected result: `send_fruit` is executed 1 time
Actual result: `send_fruit` is executing forever - over and over again

By the way, command `httpyac -a simple.http` works as expected - executed only one time

**Comment by AnWeber** [comment]
The error also occurs if you do not use any parameter at all and use the selection by inquirer. I have fixed this now and is included in the next release.
