### ISSUE TITLE
Error: `input` must not start with a slash when using `prefixUrl`

### ISSUE THREAD

**Issue by woolfas** [AnWeber/httpyac#416]
Steps to reproduce

Create 2 http scripts: 
**first.http**
```
@host=https://httpbin.org/

### Apple
# @name send_apple
POST /anything
Content-Type: application/json

{
        "id": "0001",
        "type": "fruit",
        "name": "Apple"
}
```

**second.http**
```
# @import first.http

### All
# @forceRef send_apple

```

Invoke `second.http` and you will get error:
```
Error: `input` must not start with a slash when using `prefixUrl`
```

This error is appearing because of the `@host` variable in first.http. If you will add the full url in the request - `POST https://httpbin.org/anything`, then everything works as expected. Looks like that automatic host append functionality stopped working after recent changes. But this error appears only when I import the first.http file. If you will execute first.http directly without importing it, then it will also work.

**Comment by AnWeber** [comment]
seems same error as AnWeber/vscode-httpyac#184 I suspect a refactoring by me regarding HttpFile for `$httpyac` support

**Comment by AnWeber** [comment]
My guess was correct. It had the same cause. However, I included your example as a test just in case.
