### ISSUE TITLE
Await in Scripting Section

### ISSUE THREAD

**Issue by twwd** [AnWeber/httpyac#419]
Hi,

I've implemented a script that asynchronously fetches the OIDC client secret from an API to set it as the `oauth2_clientSecret` variable. When I try to use as follows it, I've got error `{}`.

```javascript
{{
    const { getClientSecret } = require('../../scripts/oidc.js');

    exports.oauth2_clientSecret = await getClientSecret(oidc_url, oauth2_clientId);
}}
```

Can you give me a hint how to get it to work?

**Comment by AnWeber** [comment]
See https://github.com/AnWeber/httpyac/pull/398. Maybe I change my opinion about the PR.

**Comment by twwd** [comment]
My script can also easily be rewritten as ESM if this makes any difference for your plans :)

**Comment by AnWeber** [comment]
ESM would not currently work. My problem is actually that I currently do not know what changes will be necessary and I do not want to block the way. You are the third person in the last 2 weeks who wants this feature. Probably I should merge the PR, and see where it leads.

**Comment by AnWeber** [comment]
I have released a version with async support. Now it should also be possible directly like your example.
