### ISSUE TITLE
How to import .rest file in httpyac to postman?

### ISSUE THREAD

**Issue by phpmaple** [AnWeber/httpyac#428]

**Comment by AnWeber** [comment]
I don't understand what the desire is right now? What is the best way to migrate from Postman JSON to *.http files? In #119 I once posted my script that I used to migrate from Postman. But it was rather optimized for my needs.

https://github.com/AnWeber/httpyac/files/7618943/postman.zip

**Comment by phpmaple** [comment]
It's like treating the rest file as openapi, and then you can import it into postman

**Comment by AnWeber** [comment]
You want an Open API Export?
