### ISSUE TITLE
question: is it possible to import multiple graphql files?

### ISSUE THREAD

**Issue by yanghua-ola** [AnWeber/httpyac#435]
Imagine a fragment `FooFragment` is defined in `fragment.gql` and it is used by both `query.gql` and `mutate.gql`. Now if I write my request like below:
```
POST https://api.github.com/graphql
gql AddItems < mutate.gql
```
It would complain `FooFragment` was not defined.

Is there a way to import multiple graphql files? in this case: `fragment.gql` and `mutate.gql`

**Comment by yanghua-ola** [comment]
I found a workaround, that's `cat fragment.gql mutate.gql > all.gql` and then
```
POST https://api.github.com/graphql
gql AddItems < mutate.gql
```
It works but feels a bit cumbersome

**Comment by AnWeber** [comment]
It should also work to import the individual files one by one. It is important to import the query in the body and to specify the fragments with the referenced name before the request.

```

gql ContinentParts < continentParts.gql

POST https://countries.trevorblades.com/graphql
Content-Type: application/json

gql Continents < continents.gql

{
    "code": "EU"
}
```
