### ISSUE TITLE
Help with `?? ...` syntax / option to test body content

### ISSUE THREAD

**Issue by rngtng** [AnWeber/httpyac#440]
Sorry another question/request. I just found this assertion examples https://github.com/httpyac/httpyac.github.io/tree/main/examples/assert with the for me unknown syntax `?? .... ` that's quite a nice idea and make my assertions way simpler. Unfortunately I could only get the status one work. All the others (xpath, header, etc.) are always successful!? pls see:

e.g.

```http
GET https://httpbin.org/xml

?? status == 201
?? header Content-Type == undefined
?? xpath /slideshow/slide/title == doesn't matter
```

I this something official, or sth. deprecated? What else could I use to test if a certain attribute of a response is set?

Thanks, Tobi

btw. the links to  test, chai etc. are broken here: https://httpyac.github.io/guide/scripting.html

**Comment by AnWeber** [comment]
Yes the api is relatively new. It was a trial to see if you can simplify testing. I'll see what goes wrong there.

**Comment by rngtng** [comment]
OK some more insight. I got the test failing with:

-  `?? header Content-Type isFalse`

and for Javascript it needs `js` directive:

passes
```
GET https://httpbin.org/json

?? response.parsedBody.slideshow.slides[0].title == FooBar
```

fails
```
GET https://httpbin.org/json

?? js response.parsedBody.slideshow.slides[0].title == FooBar
```

**Comment by rngtng** [comment]
@AnWeber I like the new API, it indeed makes my test way simpler. But test should oc fail if assertion isn't met ;)

**Comment by AnWeber** [comment]
Yes, I wanted to build it as generic and extensible as possible, and somewhere along the line the actual functionality went down the drain. I will be allowed to look at it again.

**Comment by AnWeber** [comment]
The problems with the tests should be solved.
