### ISSUE TITLE
metadata @jwt no longer seems to work starting with v6.4.0

### ISSUE THREAD

**Issue by wusawo** [AnWeber/httpyac#454]
Hi @AnWeber 

I just noticed that the metdata `@jwt` no longer seems to work.
I works till version 6.3.4, but fails starting with version 6.4.0

Similar: Starting with version 6.3.3 a script that ends with a comment fails with error
```
SyntaxError: Unexpected end of input
	at new Script (node:vm:100:7)
	at createScript (node:vm:257:10)
	at Object.runInContext (node:vm:288:10)
```

**Comment by AnWeber** [comment]
Now the body is filled again identically to the parsedBody. Unfortunately, I have built in a discrepancy during a small adjustment here, which was also not found by the test.
