### ISSUE TITLE
Special characters in request separator comment breaks script execution

### ISSUE THREAD

**Issue by wusawo** [AnWeber/httpyac#455]
Hi @AnWeber 

I have http regions defined by request separater with a comment containing special chars like ':' or '('.
If such a region doesn't have a `@name` defined, the script execution of that region fails on subsequent runs starting with version 6.4.2 with errors like
```
SyntaxError: Unexpected token '('
	at new Script (node:vm:100:7)
	at createScript (node:vm:257:10)
	at Object.runInThisContext (node:vm:305:10)
```

**Comment by AnWeber** [comment]
@wusawo Do you have some small example. Would be easier for me to fix it

**Comment by wusawo** [comment]
Sure. The following request/region fails on the second run
```
### test: (1)

{{
    let i=0;
}}
GET https://google.com
```

It seems that the response of the request is added as variable (`test:(1)` and `test:(1)Response`) although it has no `@name`. These variables are passed as param to the script function and cause trouble:
```
(async function userJS(exports, require, module, __filename, __dirname, response, $global, test:(1), test:(1)Response, console, httpFile, httpRegion, request, sleep, test, $httpyac, $random)
                                                                                               ^

SyntaxError: Unexpected token ':'
	at new Script (node:vm:100:7)
	at createScript (node:vm:257:10)
	at Object.runInThisContext (node:vm:305:10)
```

**Comment by AnWeber** [comment]
Since the region name is also used as a variable name, it should be a valid javascript variable name. I now work around this limitation with `with`, even though this might be slower.
And I could have understood it from the first description. But thanks for the detailed example.

**Comment by wusawo** [comment]
My understanding was that there is even no variable for the request response created if the request does not have a `@name`.
Anyways, I was able to update my httpyac extension now and works as expected. Thank you 🙂

**Comment by AnWeber** [comment]
@wusawo Yes, that's what I was thinking about at first. I would have had to check it via regex, which again could be flawed. This solution makes it safe and that's why I liked it. I think that performance problem should not be so crucial for this kind of scripts.
