### ISSUE TITLE
CookieJar isn't disabled when using a config file

### ISSUE THREAD

**Issue by klutzer** [AnWeber/httpyac#457]
First of all, thanks for this nice project! It's a great enhance of `rest-client`.

I'm facing a lot of "Cookie not in this host's domain" issues, so I'm trying to disable CookieJar by default. But when I disable it from `httpyac.config.js` it seems not being recognized.

Files structure:
```
- httpyac.config.js
- requests/
    - test.http
```

`httpyac.config.js`
```
module.exports = {
  cookieJarEnabled: false,
};

```

The strange thing is that when I use `# @no-cookie-jar` in the request, the cookie error doesn't occur, so I'm assuming the cookieJar isn't disabled globally (using config file).

**Comment by AnWeber** [comment]
@klutzer I have only been able to trigger the error in the VSCode extension. Did you have this in the command line?
In VSCode, the configuration of VSCode wins over the file configuration, since I unfortunately specified a default value. I have removed this now. Workaround would be to configure it additionally in VSCode.

**Comment by klutzer** [comment]
Yep, you're right, the error doesn't occur in the CLI, just VSCode extension. So I'll disable in the workspace `settings.json` file and commit it as well (until new extension's version is published).

**Comment by AnWeber** [comment]
Ok, then I will close the ticket. The fix will go with the next version. Thanks for reporting. Hava a nice day.

**Comment by klutzer** [comment]
For you too! Thank you for your fast reply man.

**Comment by tlunsfordCXP** [comment]
For anyone unclear on the solution, in the root of your project create file httpyac.config.js with the following content:

```
module.exports = {
  cookieJarEnabled: false,
}
```
