### ISSUE TITLE
redirect_uri in the authentication flow

### ISSUE THREAD

**Issue by sudipn** [AnWeber/httpyac#46]
The OpenID  _Authentication Flow_ requires that the client set the request parameter `redirect_uri` when sending an authentication request to the authorization end point.

Which variable can be used to set the `redirect_uri` in the basic flow? 

---
current configuration for an integration environment:
int_authorizationEndpoint=https://oauth-server-int/as/authorization.oauth2
int_tokenEndpoint=https://oauth-server-int/as/token.oauth2
int_clientId=...
int_clientSecret=...
int_scope=openid profile email
int_responseType=code

GET /secure-end-point
Authorization: openid authorization_code int

**Comment by AnWeber** [comment]
Httpyac opens a local http server and redirect uri is automatically set to localhost:3000. Your client Id needs to be enabled for this redirect uri.

https://github.com/AnWeber/httpyac/blob/main/src/variables/replacer/oauth/authorizationCodeFlow.ts#L25

**Comment by AnWeber** [comment]
I have tried to improve the documentation on which variables need to be set. In Keycloak, the specification of the Valid Redirect Uri would look like this:
![image](https://user-images.githubusercontent.com/13434739/124313907-d702bb80-db71-11eb-9a75-510d339bbe7d.png)
I deliberately chose a different implementation like Postman. This way my program never has the possibility to know the ClientId as well as username and password. Postman, on the other hand, controls the browser where the password is entered and thus has complete access to all data ([see](https://stackoverflow.com/questions/58156957/how-postman-complete-the-oauth-2-0-flow-without-actually-redirect-to-the-redirec)).
Did the authorization work or can I help you?

**Comment by AnWeber** [comment]
I'm closing the ticket for now. If you have any further questions, please contact me
