### ISSUE TITLE
output-failed didn't work?

### ISSUE THREAD

**Issue by yanghua-ola** [AnWeber/httpyac#460]
I am running some http requests from cli. Sometimes one of the requests fails; and I want to be able to check the response during troubleshooting. I thought `--output none --output-failed response` would enable that. However it didn't. Below is a minimal example.

Given /tmp/test.http
```
###
GET https://github.com/a9038fj203
{
  "hello": "world"
}
?? status == 200
```
When I run this from CLI, I expect to see the response being logged as the request should fail with an 404 error.
```
npx httpyac@latest send /tmp/test.http -a --output none --output-failed response
```
However only the error message was printed, not the response
```
✖ status == 200 (AssertionError [ERR_ASSERTION]: status (404) == 200 - /root/.npm/_npx/45b2c1b7cf00ff6e/node_modules/httpyac/dist/index.js:2:43950)
```

I tried both with and without `?? status == 200`. No response was printed in either case. Did I misunderstand the flag?

**Comment by AnWeber** [comment]
Thank you for the pr
