### ISSUE TITLE
`after` script executed one extra time for `while` loop

### ISSUE THREAD

**Issue by yanghua-ola** [AnWeber/httpyac#463]
Given below http file:
```
###
# get project items
# @name get_project_items

{{
  exports.pageInfo = {
    hasNextPage: true,
  };
}}

# @loop while pageInfo.hasNextPage

GET https://github.com/postsadf

?? status == 200
{{@after
    pageInfo.hasNextPage = false;
    console.log("triggered")
}}
```
I expected "triggered" to be printed once. In reality, it would be printed twice. Other hooks, e.g. "response", "responseLogging" don't have this problem.

**Comment by AnWeber** [comment]
It was important to me not to introduce any special logic for the loop logic in other plugins. For this reason `while` works similar to `ref` only that a copy of the current region is always called. When the loop is terminated, however, I have to cancel the current execution, but I must not use any cancellation in the process. For this reason I put the current [execution index at the last index}(https://github.com/AnWeber/httpyac/blob/53b995d07b0fdeb884bc8497aa4e1de4657c9ebb/src/plugins/core/metaData/loopMetaDataHandler.ts#L115). Unfortunately I did not think about the interceptor. I'll see how I can deactivate it correctly.

**Comment by AnWeber** [comment]
I have not been able to solve it completely without adjusting the logic on the outside. I have therefore extended my hook concept so that any interceptor can abort the execution without error. It will go with the next release.
