### ISSUE TITLE
Config logOutputChannelOptions seems to be available just in VSCode settings

### ISSUE THREAD

**Issue by klutzer** [AnWeber/httpyac#467]
I'm trying to find a way to configure de log output options in `httpyac.config.js` file so I can use just one config file for CLI and VSCode extension. But this options is only applied when I use the VSCode settings:

```json
  "httpyac.logOutputChannelOptions": {
    "requestBodyLength": 0,
    "responseBodyLength": 0
  }
```

Is there any way to apply those settings in `httpyac.config.js`?

**Comment by AnWeber** [comment]
@klutzer There is now a new options `log.options` with which the output for CLI and VScode can be configured.
