### ISSUE TITLE
Environment variable interpolation

### ISSUE THREAD

**Issue by klutzer** [AnWeber/httpyac#468]
I'm configuring a project containing the following file structure:

```
- src
    - httpyac.config.js
    - Authentication
        - auth.http
    - env
        - .env.hmg
        - .env.prod
```

.env.hmg
```
username=hmg
password=xxx
```

.env.prod
```
username=prod
password=xxx
```

I have also a validation pipeline where I run the httpyac CLI to execute the authentication process on hmg env. So the code is:
```
$ httpyac send --env hmg --all src/Authentication/auth.http
```

The problem here is the `password` is configured through a real environment variable with the same name (lowercase too), but when I use it in `auth.http` with `{{ password }}`, `httpyac`'s CLI always evaluate the `.env.hmg` file. When I comment or remove the variable from the file, the variable isn't populated with the environment variable as well (`ReferenceError: password is not defined`). The only solution that I found was forcing the variable as `password = {{ $processEnv password }}` in `.env.hmg`.

Is this a bug or should I take another approach to use real environment variables instead of normal `{{}}` interpolation?

**Comment by AnWeber** [comment]
If I understand you correctly, you are trying to access the environment variable with `password`. This is not possible in NodeJS, you have to access it with process.env.password (see https://nodejs.dev/en/learn/how-to-read-environment-variables-from-nodejs/). I have intentionally not provided any special mechanism to make them easily accessible. The way is either via `process.env.xxx` or via the rest-client replica `$processEnv`.

```
GET http://auth.secure.net
Authorization: Bearer {{process.env.password}}
```

**Comment by wray27** [comment]
Re-opening this as this is a feature that can be found in [http-rest-client](https://marketplace.visualstudio.com/items?itemName=humao.rest-client) throught the use of `%`. See example:
` {{$processEnv [%]envVarName}}`

> I  have intentionally not provided any special mechanism to make them easily accessible.
Is there any reason for this?

Doing this is quiet useful where auth requires different secrets in different environments that are accessed indirectly through environment variables. For example:

```json
{
  "prod": {
     "client_secret": "PROD_SECRET"
  },
  "uat": {
     "client_secret": "UAT_SECRET"
   }
}
```

**Comment by AnWeber** [comment]
@wray27 Access to environment variables is possible, only the syntax is different: `{{process.env.BLA}}` instead of `{{$processEnv BLA}}`. My statement is intended to mean that you cannot simply write `BLA? . Support for rest-client syntax is possible, I could also parse the syntax, but I would also welcome an MR for this feature (see [restClientVariableReplacer.ts](https://github.com/AnWeber/httpyac/blob/main/src/plugins/core/replacer/restClientVariableReplacer.ts)).
