### ISSUE TITLE
documentation / example extension for: server-sent-events-eventsource request.

### ISSUE THREAD

**Issue by beva-sdev** [AnWeber/httpyac#471]
At first, thanks for the tool (using the VS-Code extension).
I am not a Javascript programmer. I want to test APis with your Tool.
Presently, I am not able to test the SSE. There is no result / output visible after closing the session. 
For the test, I have used the example in: https://dev.to/dhiwise/how-to-implement-server-sent-events-in-nodejs-11d9

Thanks in advance.

**Comment by AnWeber** [comment]
@beva-sdev Hi all my documentation is hosted on [httpyac.github.io](https://httpyac.github.io/guide/request.html#server-sent-events-eventsource). I have updated the [SSE examples once with postman-echo](https://httpyac.github.io/guide/request.html#server-sent-events-eventsource). But here I get partial errors. I'm still trying to identify where they come from. Somewhere there are connection problems and I can't tell yet if the used dependency or the server is faulty.

**Comment by AnWeber** [comment]
using sse.dev works without error. Seems to be some issues with postman-echo

```
# @keepStreaming
SSE https://sse.dev/test
Event: message
```

**Comment by AnWeber** [comment]
If you can't get it to work, maybe you can send me the server code and I'll take a look.

**Comment by beva-sdev** [comment]
Thanks,
the  `Event: message` header is the solution, works as expected.

**Comment by AnWeber** [comment]
@beva-sdev I added it as default event with the next release.
