### ISSUE TITLE
Error: Cannot find module 'node:events'

### ISSUE THREAD

**Issue by FrankRua** [AnWeber/httpyac#476]
I have starting getting "Error: Cannot find module 'node:events'" today on my build servers. I have not changed versions in a few months. 

Have you seen this issue before or have others reported it?

**Comment by AnWeber** [comment]
I think Node 16 allows to import internal modules with `node:...` Did you downgrade your NodeJS environment?

**Comment by AnWeber** [comment]
@FrankRua How can I help you? Something must have changed to make the program behave differently. I would test the import once without `node:` and best also output the runtime version once.

**Comment by FrankRua** [comment]
@AnWeber I'm not sure what happened but it started working again. I think it was something with the build server not cleaning the directory before each build. Thank you anyways, I'll close this out.

**Comment by AnWeber** [comment]
@FrankRua thx for the response.
