### ISSUE TITLE
Passing {{test}} within the body of a request

### ISSUE THREAD

**Issue by dremekie** [AnWeber/httpyac#48]
I'd like to pass the following body in a `POST`

```json
{
  "template": "My {{someVerb}} template!!"
}
```
It, of course, complains that {{someVerb}} is not a variable.

 Is this possible?

**Comment by AnWeber** [comment]
My original plan in this case was to use an external file without variable substitution.

```
POST http://httpbin.org/anything
< body.json
```

body.json
```
{
  "template": "My {{someVerb}} template!!"
}
```

Possibly one should still include some kind of encoding
```
{
  "template": "My \{\{someVerb\}\} template!!"
}
```
Do you possibly have a suggestion, I find mine currently not good?

**Comment by AnWeber** [comment]
I have now implemented it with this escape logic. I don't think it looks any better with other characters.

**Comment by dremekie** [comment]
Thanks @AnWeber. Will you be releasing it soon?

**Comment by AnWeber** [comment]
Sorry for the delay. I was sent another feature request, but unfortunately that turned out to be more time-consuming than expected.

**Comment by AnWeber** [comment]
I published a new release.

**Comment by AnWeber** [comment]
thx for using my extension. Feel free to open issue again, if it is not working as expected.
