### ISSUE TITLE
Run httpyac in browser?

### ISSUE THREAD

**Issue by rngtng** [AnWeber/httpyac#483]
I wonder if its easily possible to run httpyac purely in a browser? Like the examples on http://httpyac.github.io would have a 'little' execution button and their result displayed in a dedicated view or such?

**Comment by AnWeber** [comment]
Yes, but ... :-) https://github.com/AnWeber/httpbook/issues/89

It's just a time issue. The Main pitfalls are solved.

**Comment by rngtng** [comment]
Nice! I’ll close this one then
