### ISSUE TITLE
Default assert?

### ISSUE THREAD

**Issue by tarioch** [AnWeber/httpyac#488]
It would be great if it were somehow possible to have a default assert (e.g. status == 200). So that this would be used for all requests, except for the ones where I explicitly specify a different assert.

**Comment by AnWeber** [comment]
My thought would be to implement it similar to the [global script blocks](https://httpyac.github.io/guide/scripting.html#global-scripts). This would mean that it is possible to define default asserts per file. But these are then always valid for all regions in this file.

```
?? status == 200
###
GET https://httpbin.org/status/200

GET https://httpbin.org/status/404
```

**Comment by tarioch** [comment]
I think that sounds good, would those also work with an import or would they have to be specified in each file?

**Comment by AnWeber** [comment]
@tarioch I will have to support the imports if you ask for them directly. I thought about whether I could get around it because it's more difficult, but it makes sense.

**Comment by AnWeber** [comment]
Global Asserts and also the import will be delivered with the next version. Thanks for the improvement idea.
