### ISSUE TITLE
Summary mode

### ISSUE THREAD

**Issue by gerukin** [AnWeber/httpyac#49]
Thanks again for the excellent work. Here's a suggestion to hopefully make the CLI more versatile.

### Goals
1. focus on only high level info
2. efficiently go through many requests
3. use in continuous monitoring and trigger alarms

## Proposal

There is a helpful `--verbose` mode, but there doesn't seem to be a way to make httpyac more concise.

For just one request being tested in the normal mode, with a **tiny body** response:
```
https://the.server.dev/checks/health => 200
GET https://the.server.dev/checks/health
accept: */*
accept-encoding: gzip, deflate, br
user-agent: httpyac

HTTP/1.1 200 OK
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400, h3=":443"; ma=86400
cf-ray: 66b9e0e55d873469-NRT
connection: close
content-length: 15
content-type: application/json
date: Thu, 08 Jul 2021 14:07:22 GMT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
nel: {"report_to":"cf-nel","max_age":604800}
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v2?s=u2dylFQnhzyetY8zUENOcv4l0%2FvmxRW8%2FmAKXfC0Kyna8uVZddEaWx6oSfQBJfM%2FwDfKchWeiwRdwhXSP7VykaQnTuM0mNTl0HCkd4%2BWhjtUB%2FcmtTroVQnfMEe%2Bs%2F8dw8Lh"}],"group":"cf-nel","max_age":604800}
server: cloudflare
vary: Accept-Encoding

{
  "status": "OK"
}
Tests for /checks/health
✓ Request succeeded
✖ Schema is valid (AssertionError [ERR_ASSERTION]: Response schema is incorrect: does not exactly match expected constant: ok - t.IntellijHttpClient.assert (/Users/name/.nvm/versions/node/v14.15.5/lib/node_modules/httpyac/dist/index.js:1:32228)
```

This is very helpful a lot of the time, but it is a bit difficult to use when running large collections of tests, or tests with large bodies, or if trying to use it in a continuous monitoring situation.

We could imagine something like this as an extra output mode:
<img width="789" alt="summary-ex" src="https://user-images.githubusercontent.com/36127103/125068104-0bd1be00-e0f0-11eb-871f-ee90f8be7109.png">

### Summary line

The summary line would be of some simple format like:
```
? requests tested (? succeeded, ? failed with ? CRITICAL)
```
So that an evaluation script may look at the last line and check that `0 failed` or `0 CRITICAL` is found, or do something if not (like trigger alerts, save or forward the full log...).

### Options

Perhaps something like:
```
--summary             summary as above, with all requests included
--summary --failed    same format but showing just requests involving at least one failed test
--summary --critical  same format but showing just requests which have CRITICAL failures
--summary --json      outputs everything in json format for easy parsing
```

**Comment by AnWeber** [comment]
good idea.

**Comment by AnWeber** [comment]
I recognize the following requirements
* Test summary after execution of all tests
* Leaner output in cli use case 
   * short-format (request => status), only response, only response + header => `--output short`
   * tests failed and critical => `--filter only-failed`
* new category for critical tests (not yet convinced about that)
* JSON output for simpler parsing in cli (Doesn't have to be short, but should possibly use a standard to get better support with Jenkins,...)

With the critical status, I'm not sure if that makes sense. I have not seen one of these on other TestRunners yet either (jest, junit, mstest). Maybe you have a good example?
Do you have any idea for the JSON output format? Junit xml I don't really want to build, jest json I also find difficult as I can't get all the data in.

**Comment by gerukin** [comment]
Thanks, that was quick, and the summary looks nice! 🙇‍♂️

I have a slight preference for counting requests, but maybe it's debatable whether we should count successful / failing _tests_ or _requests_. I suppose we could have it both ways too. 😇

### Upcoming changes / additions

I like the suggested options too (if you implement `--output short` you may want to switch to `--output verbose` instead of `--verbose` unless matching options for other tools is important to you).

#### Critical

Sure, perhaps the _critical_ or not distinction can be better left to a post script to evaluate (people can prefix their tests or requests accordingly), or even just based on the directory structure, and httpyac wouldn't need to worry about this at all. All of the use cases I have or can think about could be handled easily if we have a json output, and some just with the dir structure.

#### Formatting

I noticed a small thing which is a bit distracting for me. When I am purposely testing a _this shouldn't work_ case, a `404` might actually be a good thing. Right now I have this conflicting view:
<img width="386" alt="Screen Shot 2021-07-10 at 9 44 58" src="https://user-images.githubusercontent.com/36127103/125146928-87b91e00-e163-11eb-8052-fed5ad8d7c04.png">

From a response code perspective it makes sense (and perhaps it should remain in the default view). But from a testing perspective it may not.

At least in the `--output short` mode (or `--output tests`), I think it would make sense to not color the response code and URL:
<img width="539" alt="Screen Shot 2021-07-10 at 10 11 57" src="https://user-images.githubusercontent.com/36127103/125147597-4e82ad00-e167-11eb-81a9-5a6fc9b71ce0.png">

#### Json output

I don't think you should worry too much about compatibility for the output here if you output all the info you have to `json` in a format which makes sense for `httpyac`. People can then:
1. build simple adapters (you could even later add example scripts) to dynamically re-output to their tool's preferred format
2. modify their custom CI / alert scripts to use your format directly

Otherwise if you go for a specific third party format as a first pass, you'll have to produce an output which may not take advantage of the unique features of httpyac and be maladapted to the `dir` / `req` `res` `tests` structure which is so helpful to preserve IMO.

I think what would be nice for the json goals would be something like:
* extended summary (counting total / successes / failures, for both tests and requests)
* mirror directory structure in json nesting
* include all request and response info (without actual output however)
* include each test result

Something like:
```json
{
  "summary": "summary object { ... }",
  "requests": [{
    "type": "dir",
    "name": "name-of-directory",
    "summary": "summary object { ... }",
    "requests": [
      { "type": "req", "rest": "req properties, a response object, a tests array..." },
     "directory object { ... }"
    ]
  }],
  "rest": "format version..."
}
```

Note: one issue that I'm not sure is addressed by httpyac yet is redaction of confidential / sensitive / secret data in cookies, headers, query strings, req body and so on. If not saving the output, we avoid it there, but it's still potentially an issue with the request... and perhaps even with the response headers and so on. One short term way to deal with this would be to only include the summary info for now while you consider what to do (if anything) for data redaction. Another solution is to include everything, have no built-in redaction mechanism... and leave it to a post script or future adapter too.

### Quick question

I'm sorry I haven't looked deeply into it yet but... how is the execution order decided for requests in dir and sub dirs? Is it purely alphabetical? Something else?

Thanks!

**Comment by AnWeber** [comment]
First of all, I like your comments. I would like to possibly channel the ideas a bit so that they can be found again by third parties. May I suggest to treat your comment concerning sensitive data in a separate thread (=> #50)

**Comment by AnWeber** [comment]
I use [globby](https://www.npmjs.com/package/globby) for the [recognition](https://github.com/AnWeber/httpyac/blob/main/src/cli.ts#L64-L74). [Fast-glob](https://github.com/mrmlnc/fast-glob) is used internally, which does not ensure sorting (meanwhile results are returned in arbitrary order)

**Comment by AnWeber** [comment]
I once created a prerelease (v2.20-beta.0) and published it. Maybe you take a quick look at it. I made too many changes and want to test everything before a real release. In addition, I have created a few open sites in vscode-httpyac and httpbook.
![output](https://user-images.githubusercontent.com/13434739/125354414-109ea800-e364-11eb-92eb-4732efa9812b.gif)

**Comment by gerukin** [comment]
Awesome! That was pretty fast for quite a bit of refactoring + new features. 🙇‍♂️

Of course, I'll try to give it a go tonight (my tonight) and run some tests.

**Comment by AnWeber** [comment]
> I like the suggested options too (if you implement --output short you may want to switch to --output verbose instead of --verbose unless matching options for other tools is important to you).

I intentionally wanted to distinguish between request logging, script logging and application logging. `--output` controls formatting of request. `--verbose` and `--silent` controls the other two logging types

**Comment by gerukin** [comment]
Thank you! I ran a few tests....

### Manually running one query in json
```bash
httpyac --env dev requests/ --json
? please choose which region to use requests/system/health-check.http: GET {{BASE_URL}}/checks/health (line 2)
```
```json
{
  "_meta": {
    "version": "0.1"
  },
  "requests": [],
  "summary": {
    "totalRequests": 0,
    "failedRequests": 0,
    "successRequests": 0,
    "totalTests": 0,
    "failedTests": 0,
    "successTests": 0
  }
}
```
But:
```bash
httpyac --env dev requests/
? please choose which region to use requests/system/health-check.http: GET {{BASE_URL}}/checks/health (line 2)
```
```bash
GET http://127.0.0.1:8787/checks/health
accept: */*
accept-encoding: gzip, deflate, br
user-agent: httpyac

HTTP/1.1 200 OK
...

{
  "status": "ok"
}
✓ Request succeeded
✓ Schema is valid
```

Running all requests  with `--all` works:
```bash
httpyac --env dev requests/system/health-check.http --all --json
```
```json
{
  "_meta": {
    "version": "0.1"
  },
  "requests": [
    {
      "fileName": "requests/system/health-check.http",
      "rest": "of json looks ok, 🙇‍♂️"
    }
],
  "summary": {
    "totalRequests": 1,
    "failedRequests": 0,
    "successRequests": 1,
    "totalTests": 2,
    "failedTests": 0,
    "successTests": 2
  }
}
```

But not manually from the prompt (whether there is only one request or several in the file):
```bash
httpyac --env dev requests/system/ --json
? please choose which region to use requests/system/health-check.http: all
```
```json
{
  "_meta": {
    "version": "0.1"
  },
  "requests": [],
  "summary": {
    "totalRequests": 0,
    "failedRequests": 0,
    "successRequests": 0,
    "totalTests": 0,
    "failedTests": 0,
    "successTests": 0
  }
}
```

**Comment by gerukin** [comment]
I'm not sure if the following was intended:

```bash
httpyac --env dev requests/system/health-check.http --json --all --output body
```
```json
{
  "_meta": {
    "version": "0.1"
  },
  "requests": [
    {
      "fileName": "requests/system/health-check.http",
      "response": {
        "statusCode": 200,
        "statusMessage": "OK",
        "headers": {
          "date": "Tue, 13 Jul 2021 10:47:04 GMT",
          "content-type": "application/json",
          "content-length": "15",
          "expect-ct": "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"",
          "report-to": "{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v2?s=Bs85BfAcNRzQYkm5Vskmbddj%2FHOfXUqF784Q8BtO0vHzQWOZl3imdr58e9yL6V9s2PWjhLo9ZdLuXJuuujd0Ma2ZGOOv1G4uDgUE52cdSI8C9t0hH9OskBUpT1n6KCehCPT2er2cjMgtFJLx9cfak%2BbBr9GoGo4%3D\"}],\"group\":\"cf-nel\",\"max_age\":604800}",
          "nel": "{\"report_to\":\"cf-nel\",\"max_age\":604800}",
          "vary": "Accept-Encoding",
          "cf-ray": "66e1ee5d6e3ff8eb-NRT",
          "alt-svc": "h3-27=\":443\"; ma=86400, h3-28=\":443\"; ma=86400, h3-29=\":443\"; ma=86400, h3=\":443\"; ma=86400",
          "server": "cloudflare"
        },
        "body": "{\"status\":\"ok\"}",
        "rest": "of json not included"
      }
    }
  ]
}
```

Whereas:
```bash
httpyac --env dev requests/system/health-check.http --all --output body
```
```bash
{
  "status": "ok"
}
✓ Request succeeded
✓ Schema is valid
```

**Comment by AnWeber** [comment]
I was not sure myself what to do with body in the json case, so it is treated identically to [response](https://github.com/AnWeber/httpyac/blob/main/src/cli/cliJsonOutput.ts#L91-L92). I wanted to be able to use `--output` to modify the content of the JSON. but body doesn't make sense to me.

**Comment by gerukin** [comment]
Overall I think it's a really nice improvement!
```bash
# looks like it includes response headers but not the body in json
# and just the URL, timing, size, and tests in the console
httypyac --output short

# looks like it includes only the body in the console, but in my json tests
# it also includes the response headers
httypyac --output body

# looks like it logs only the response headers and body 👌
httpyac --output response

# looks like it includes only the request / response headers 👌
# and is the default for json (I know this is on purpose) but not the console as per your last commit,
# but in my test it looks more like `exchange`
httypyac --output headers

# looks like it includes request / response headers + body (everything)
# and is default in the console but not in json 🤔
httpyac --output exchange

# logs only the request url and tests 👌
httpyac --output none
```

> I was not sure myself what to do with body in the json case

I like the flexibility for the console... but I'm not sure you should worry too much for the json output. I would probably almost always run it through my own analysis script anyway... so I'm happy to have a lot of data.

However, one thing which might be good though, for logging in monitoring scenarios for instance (where saving on log size and indexing or parsing CPU might be a good idea).. is a mode json / console mode to:
1. use the short format (the console version is great, the json version is still rather verbose in comparison) when all tests are successful on a given request
2. use the exchange format when some of tests fail for a given request

**Comment by gerukin** [comment]
There is only one thing which is perhaps missing here to beat POSTMAN in logging (from my perspective anyway): the request name / title / description.

Consider this:
```bash
# in POSTMAN the name could be:
# Product (update the name as admin)
PATCH https://server.dev/products/1
✓ Action allowed

# in POSTMAN the name could be:
# Product (update the name as manager)
PATCH https://server.dev/products/1
✖ Action allowed # problem - but without a title, what about?

# in POSTMAN the name could be:
# Product (update the status as manager)
PATCH https://server.dev/products/1
✓ Action forbidden

# in POSTMAN the name could be:
# Product (update the name as client)
PATCH https://server.dev/products/1
✓ Action forbidden
```

It's generally nice to quickly see at a glance what the purpose of the request was and put the tests further in context, without having to go into the details of each request to see how they differ.

Of course, the tests can be more explicit. But it makes writing reusable tests harder. Having a generic `Action forbidden` which can be reused everywhere is nicer than having to write specific `Updating name as client is forbidden`.

I suggested keying in on the `### some title` request delimiter... but maybe that's tricky?
```bash
# from the ### request delimiter
=== Product (update the name as client) ===
PATCH https://server.dev/products/1 => 403 (102 ms, 320 B)
✓ Action forbidden
```

**Comment by AnWeber** [comment]
I updated the prerelease to 2.20.0-beta.1. Following is included
* output of name and description before each request (Name can be defined in the delimiter `### name of request`)
* different output of failed requests is possible with option `--output-failed exchange`
* fix json output with one request
* use exchange as default output for json and console
* `--filter=only-failed` is also used in json output

> I like the flexibility for the console... but I'm not sure you should worry too much for the json output. I would probably almost always run it through my own analysis script anyway... so I'm happy to have a lot of data.

I wanted to provide an easy way to minify the JSON without having to implement custom logic.

**Comment by AnWeber** [comment]
Thanks again for all the ideas. I think I currently have everything covered in this ticket. I will deal with anweber/vscode-httpyac#50 next

**Comment by gerukin** [comment]
Again, that was fast. Thank you!

I'm sorry I don't have time to properly test tonight... but I ran a quick test with `--all --output short` and only the first request went through.

Before getting to the second one it gave me a SyntaxError. I haven't made any changes to the code and it looks like perhaps the request title is causing the issue now.

I'll play with it more over the WE but here's the trace for now:
```
=== Request title ===
GET https://server.dev/path
=> 200 (895 ms, 10.83 KB)
✓ Request succeeded
✓ Schema is valid
✓ Response has the right number of items

js: exports.$result = (API_URL);
requests/test.http:9
(function userJS(exports, require, module, __filename, __dirname, REDACTED_VAR_NAME, BASE_URL, API_URL, response, Request title){exports.$result = (API_URL);})
                                                                                                                    ^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:101:7)
    at createScript (vm.js:262:10)
    at Object.runInThisContext (vm.js:310:10)
    at Object.<anonymous> (/Users/me/.nvm/versions/node/v14.15.5/lib/node_modules/httpyac/dist/index.js:1:37428)
    at Generator.next (<anonymous>)
    at /Users/me/.nvm/versions/node/v14.15.5/lib/node_modules/httpyac/dist/index.js:1:36507
    at new Promise (<anonymous>)
    at s (/Users/me/.nvm/versions/node/v14.15.5/lib/node_modules/httpyac/dist/index.js:1:36252)
    at Object.g (/Users/me/.nvm/versions/node/v14.15.5/lib/node_modules/httpyac/dist/index.js:1:36786)
    at t.JavascriptVariableReplacer.<anonymous> (/Users/me/.nvm/versions/node/v14.15.5/lib/node_modules/httpyac/dist/index.js:1:154775)
```

Looks like it's treating the title `Request title` as an exported variable name.

**Comment by AnWeber** [comment]
Yes, your guess is right. The Name of a request is used as variable name (used with `@ref`). I wanted to test, if I can reuse the title as name, but I guess not:-) I will change it to title.
You don't have to feel obligated to test. I think it's great, but it should be fun for us first and foremost.

**Comment by gerukin** [comment]
Thank you @AnWeber it works well now. I think you implemented everything on this ticket and made it even more flexible! I'm impressed by and thankful for your dedication to your project.

Hope you don't mind if I take the liberty to close this ticket.

**Comment by AnWeber** [comment]
Thx
