### ISSUE TITLE
Non interactive cli mode?

### ISSUE THREAD

**Issue by tarioch** [AnWeber/httpyac#492]
Is it somehow possible to not ask for values when running from cli?

e.g. I have a case like this

```
@asOfDate={{$input As of Date? $value: 2023-05-30}}
GET /foo/{{asOfDate}}
```

When manually calling it in vscode, it's great that it ask me and I can choose a different value, but if run from the automation, I would like it to just pick the default value and not ask. Is that somehow possible?

**Comment by AnWeber** [comment]
@tarioch I don't currently have that directly planned. I have two ideas. 

- You could swap these variables into an .env file and provide an additional ci.env with the values for the automation.
> .env
```
asOfDate={{$input As of Date? $value: 2023-05-30}}
```
> ci.env  => httpyac *.http -e ci
```
asOfDate=2023-05-30
```

- add a custom plugin only enabled in CI mode which overrides the [userInteractionProvider](https://github.com/AnWeber/httpyac/blob/main/src/models/userInteractionProvider.ts#L5)

> .httpyac.js

```javascript
module.exports = {
	configureHooks: function (api) {
              if(process.env.CI){
		  api.userInteractionProvider.showInputPrompt = (_msg, defaultvalue) => defaultvalue;
              }
	}
}
```

**Comment by tarioch** [comment]
Thank you very much, the second one is exactly what I was looking for.
