### ISSUE TITLE
XPath Namespaces

### ISSUE THREAD

**Issue by jods4** [AnWeber/httpyac#493]
It would be nice to add support for XML namespaces in XPath assertions.

Library `xpath` already has support. Its readme describes two ways:

(1) Long form with predicates: https://github.com/goto100/xpath#namespaces
```js
var xml = "<book><title xmlns='myns'>Harry Potter</title></book>";
var doc = new dom().parseFromString(xml, 'text/xml');
var node = xpath.select("//*[local-name(.)='title' and namespace-uri(.)='myns']", doc)[0];
```
This works today in httpyac but is extremely verbose when you have lots of nodes to check.

(2) Registered namespaces mappings https://github.com/goto100/xpath#namespaces-with-easy-mappings
```js
var xml = "<book xmlns:bookml='http://example.com/book'><bookml:title>Harry Potter</bookml:title></book>"
var select = xpath.useNamespaces({"bookml": "http://example.com/book"});
console.log(select('//bookml:title/text()', doc)[0].nodeValue);
```
This is awesome and what namespaced XPath should look like.

### Proposal
It would be nice if we could declare special variables to register xpath namespaces mappings, maybe based on a prefix like `xpath_ns_{prefix} = {xml_namespace}`.
Then the xpath plugin could register those with `xpath.useNamespaces()` before executing asserts.

In practice it could look like this:
```http
@xpath_ns_my = myns

GET https://my-xml-service

?? xpath /my:root/my:answer == 42
```

**Comment by AnWeber** [comment]
The support will be delivered with the next version. There is a small deviation from your proposal. I added a space between @xpath_ns and the key.

```
@xpath_ns my = myns

GET https://my-xml-service

?? xpath /my:root/my:answer == 42
```

**Comment by jods4** [comment]
Great thanks!
I tested this and it worked.

I have some follow-up questions, related to that space after `@xpath_ns`.

My understanding is that this isn't a real variable (e.g. like OAuth config is), but something that is parsed in a new parsing step?

I see that it works when declared in the same file (either globally or at the request level), but can you outsource your namespaces in the env. config (to share them across many files)? If so, what is the right syntax?

Alternatively, I tried to declare namespaces in the same file but to substitue a variable for their value. That doesn't work:
```
@my = myns
@xpath_ns my = {{my}}
```

**Comment by AnWeber** [comment]
You are correct. I did not implement it as a variable, but wrote my own parser for it (similar to [protobuf-loader](https://httpyac.github.io/guide/request.html#protobuf-loader)). You can't put it into an .env file because of that. You can explicitly dump the definition to any *.http file and import it where it is needed. 
What is probably easier, you could also build your own plugin and use the same interface as the parser and thus define the namespaces globally unique in your project.

>.httpyac.js

```js
module.exports = {
	configureHooks: function (api) {
		api.hooks.execute.addInterceptor({
			id: "global_xpath",
			beforeLoop(hookContext) {
				const [context] = hookContext.args;
				context.options.xpath_namespaces = Object.assign({}, context.options.xpath_namespaces, {
					my: "http://test"
				});
				api.log.info(context.options.xpath_namespaces)
				return true;
			}
		});
	}
}
```
