### ISSUE TITLE
getOAuth2Response question

### ISSUE THREAD

**Issue by murphyryan1** [AnWeber/httpyac#499]
Hi there, 

I am trying to upgrade the httpyac package in a project and the method getOAuth2Response has been moved to the plugins but I am not sure how to go about calling it now. 

We were importing the `variables` package and doing

`const response = await varaibles.replacer.getOAuth2Response('implicit', 'oauth2', { variables });`

 but I can't figure out how to do that now that it is in the plugins folder and the plugins folder isn't exported. 

Could we just do this:

![image](https://github.com/AnWeber/httpyac/assets/23325706/8231a377-ec13-4020-b412-745e0c08cce9)

or is there a better way I am not seeing?

Thanks in advance.

**Comment by AnWeber** [comment]
All methods inside plugins are not really public for me. Since I want to eventually support browsers in the future, they must not become public either, since NodeJS logic is included there. I will instead add the method as a separate helper method `$getOAuth2Response` in the javascript execution.
