### ISSUE TITLE
Replacement of potential null value

### ISSUE THREAD

**Issue by nrail-joerg-walter** [AnWeber/httpyac#513]
My version:
```
More Info
Published
1/10/2021, 20:32:54
Last released
7/25/2023, 21:48:23
Last updated
7/26/2023, 11:54:49
Identifier
anweber.vscode-httpyac
```

I have

```
POST /path/to/resources
{
  "model": "{{vehicle.model}}"
}
```

where vehicle is

```
{
"model": null | string
```

this is transformed to

```
{
  "model": "{{vehicle.model}}"
}
```

in the request. How can I build the request so that either the string is used or the null. I want it to result in

```
{
  "model": null
}
```

or 

```
{
  "model": "xyz"
}
```

**Comment by AnWeber** [comment]
You could just pass `vehicle` directly. This will be automatically converted to a JSON object

```
POST /path/to/resources

{{vehicle}}
```
That the null output as in your example does not work directly, just seems like a bug. I still have to look at that

**Comment by AnWeber** [comment]
With the next version, null will also be output as a "null" string.
