### ISSUE TITLE
intellij pre js script cant execute

### ISSUE THREAD

**Issue by gejun123456** [AnWeber/httpyac#534]
from following link  https://www.jetbrains.com/help/idea/exploring-http-syntax.html#per_request_variables

< {%
    request.variables.set("firstname", "John")
%}
GET http://example.org/{{firstname}}

And

< {%
    const signature = crypto.hmac.sha256()
        .withTextSecret(request.environment.get("secret")) // get variable from http-client.private.env.json
        .updateWithText(request.body.tryGetSubstituted())
        .digest().toHex();
    request.variables.set("signature", signature)

    const hash = crypto.sha256()
        .updateWithText(request.body.tryGetSubstituted())
        .digest().toHex();
    request.variables.set("hash", hash)
%}
POST https://httpbin.org/post
X-My-Signature: {{signature}}
X-My-Hash: {{hash}}
Content-Type: application/json

the script not works.

**Comment by AnWeber** [comment]
It was a stupid sequence error. The variable was already used before the script was executed. I have corrected the order. With the next release it works
