### ISSUE TITLE
Repeat mode with diff variables

### ISSUE THREAD

**Issue by pjain11** [AnWeber/httpyac#54]
Is it possible to run the script in repeat mode with diff parameters every time? I'm thinking to use the script for automated functional testing. I wan to see if there is a way to specify diff params in array of something and array[0] params are the ones to use for 1st iteration, array[1] params are the ones to use for 2nd iteration etc. or anything similar..

**Comment by AnWeber** [comment]
Currently not. In principle, the [same request](https://github.com/AnWeber/httpyac/blob/main/src/gotHttpClientFactory.ts#L65) is always executed. It was intended for a load test or thread problems. A renewed variable evaluation is hindering there. Currently this is not elegantly solvable. I will think about it.

**Comment by AnWeber** [comment]
It should be solvable, if all [actions](https://github.com/AnWeber/httpyac/blob/main/src/utils/httpRegionUtils.ts#L125) are executed again.
I will try something like that.

```
# @repeat 10
{{
  ... // load data
  exports.arg = data[$index];
}}
GET https://httpbin.org/anything?arg={{arg}}

```

**Comment by pjain11** [comment]
How do you manage iteration #? value/context of $index between every execution. I'm ok executing all actions again.

**Comment by AnWeber** [comment]
In principle, what I meant was this. A for loop on an array, which offers all elements of the array as variable. A for loop with number of runs and a while loop that terminates with a condition (JS).
![loop](https://user-images.githubusercontent.com/13434739/125633472-513ad0ea-6629-45e3-8918-a2c56cf445b7.gif)

**Comment by AnWeber** [comment]
I updated the prerelease to 2.20.0-beta.1. I don't want to deliver a full-fledged update at the moment, because I have implemented several changes and want to test them in more detail.

**Comment by pjain11** [comment]
This is very helpful. Is it possible to keep the context of loop for more than one request? so my scenario is to call two endpoints with same parameters and compare responses. I'm trying to modernize functional code and want to automate testing for responses.

**Comment by AnWeber** [comment]
If you give the requests a name, I extend it by the index and this is available as variable in the consequence.

```
# @name tasks
# @loop for 3

GET /api/v1/tasks

###

GET /api/v1/tasks/{{tasks0.id}}

```

**Comment by AnWeber** [comment]
With the latest update (v2.20.0) I have now made the feature productive. It is now also supported in the vscode extension.
