### ISSUE TITLE
--bail flag does not work for test in referenced request

### ISSUE THREAD

**Issue by Nick-Palacio** [AnWeber/httpyac#540]
Consider the following files:
- `setupFile.http`
    ```
     # @name json
    GET https://postman-echo.com/get
    {{
        const assert = require('node:assert/strict');
        test('some test', () => {
            assert.fail('some failure');
        });
    }}
    ```
- `test.http`
    ```
    # @import ./setupFile.http
    # @ref json
    # This should never run because json request fails
    POST https://postman-echo.com/post
    ```
- `test2.http`
    `POST https://postman-echo.com/post`

If I run `httpyac send 'test*.http' --all --bail`:
- Expected Behavior:
   - The POST requests in `test.http` and `test2.http` are never run because we get an error after `@json` is run and `@json` is referenced by test.http
- Actual Behavior
   - All requests are run and we see in the end that 2 requests succeeded (`test.http` and `test2.http`) and 1 failed (`setupFile.http`)

**Comment by AnWeber** [comment]
Yes, seems that you are right. The needed Interceptor is only added to [current file](https://github.com/AnWeber/httpyac/blob/main/src/cli/send/send.ts#L163) and Not formal parsed files. I will fix it.

**Comment by Nick-Palacio** [comment]
You are the best @AnWeber! Thank you for all your work on this project.
