### ISSUE TITLE
How to escape special characters

### ISSUE THREAD

**Issue by sdasda7777** [AnWeber/httpyac#550]
Hi, I tried to send plaintext data that contains `###` and `===`, and it obviously that didn't work out, because it gets interpreted by httpyac as control symbols. However to my disappointment, escaping it as `\###` nor `\#\#\#` didn't work, and I'm not really sure what else to try. Is there a way to do this?

```http
POST http://0.0.0.0:8080/endpoint

plaintext data begin
### // this should be in payload content
plaintext data middle
=== // still should be in payload content
plaintext data end
### // real request end
```

**Comment by AnWeber** [comment]
@sdasda7777

- If the payload is Markdown and you specify "content-type `text/markdown`, `#` would be ignored (maybe docs for this feature is missing)

```
POST http://0.0.0.0:8080/endpoint
content-type: text/markdown

plaintext data begin
### // this should be in payload content
plaintext data middle
=== // still should be in payload content
plaintext data end
### // real request end
```
- If content-type `text/markdown` is not possible, you could dump the payload to a file ([docs](https://httpyac.github.io/guide/request.html#imported-request-body)). 

```
POST http://0.0.0.0:8080/endpoint

<@ ./requestBodyImport.json
```

- If you don't want the file explicitly, is to use variables for these characters and thus smuggle the characters past the parser.  

Do any of the approaches work, if not suggestions?

**Comment by sdasda7777** [comment]
Ah, I see, thanks for such a quick reply. This works fine for my purposes, so imo it's solved:

```http
@sep_one = ###
@sep_two = ===

###
POST http://0.0.0.0:8080/endpoint

plaintext data begin
{{sep_one}}
plaintext data middle
{{sep_two}}
plaintext data end
### // real request end

```
