### ISSUE TITLE
Ending a script block with a comment line errors out

### ISSUE THREAD

**Issue by gerukin** [AnWeber/httpyac#56]
Not a problem in real life scenarios but ending a script block with a comment terminates the script's execution with a fatal error.

## Example
```
### Health check
{{BASE_URL}}/checks/health

{{
  console.log('I will be outputted')
  // I have a feeling this will not end well
}}
```
```
prompt$ httpyac --env prod --all ./requests/system/health-check.http 
js:   console.log('I will be outputted')
  // I have a feeling this will not end well
                                                                  

SyntaxError: Unexpected end of input
    at new Script (vm.js:101:7)
    at createScript (vm.js:262:10)
    at Object.runInThisContext (vm.js:310:10)
    at /Users/me/.nvm/versions/node/v14.15.5/lib/node_modules/httpyac/dist/index.js:1:37428
    at Generator.next (<anonymous>)
    at /Users/me/.nvm/versions/node/v14.15.5/lib/node_modules/httpyac/dist/index.js:1:36507
    at new Promise (<anonymous>)
    at s (/Users/me/.nvm/versions/node/v14.15.5/lib/node_modules/httpyac/dist/index.js:1:36252)
    at g (/Users/me/.nvm/versions/node/v14.15.5/lib/node_modules/httpyac/dist/index.js:1:36786)
    at t.JavascriptAction.<anonymous> (/Users/me/.nvm/versions/node/v14.15.5/lib/node_modules/httpyac/dist/index.js:1:38658)
```

**Comment by AnWeber** [comment]
+1 for the comment. :-)

**Comment by AnWeber** [comment]
The cause was that the comment did not end the inserted function correctly. An extra line break solves that problem. I will soon have a look at the way the javascript is executed, maybe I can learn some optimizations from jest or vue/cli.

**Comment by AnWeber** [comment]
With the latest update (v2.20.0) the issue is fixed

**Comment by gerukin** [comment]
Great, thank you!

Note: if I were you I think I would add a comment / TODO to the code to remind myself (and others) of the purpose of this extra line. Looks like something I would forget about and be tempted to _fix_ later. 😇

**Comment by AnWeber** [comment]
Since I'm a fan of GitLens, I often leave out comments like this.
![image](https://user-images.githubusercontent.com/13434739/126103199-3b7179c0-a805-4418-8c0c-37c7f53ded6c.png)
But you're right, a comment would make sense here, since there are two little surprises in those two lines

**Comment by gerukin** [comment]
+1 for GitLens. So many wonderful extensions for vscode in general.. including yours.
