### ISSUE TITLE
Dynimically assigned variables don't expand to the value using the Send Repeat mode

### ISSUE THREAD

**Issue by ptrubini** [AnWeber/httpyac#562]
Hello, 
I have created a http file with a request which is dependent on a login function with this 
```
## @import ../Token/SetToken.http
## @forceRef login
[...]
###
# @name post_endpoint
POST {{baseUrl}}/endpoint HTTP/1.1
Content-Type: application/json
Accept: "*/*"
Authorization: Bearer {{token}}
[Body]]
```
The login method set a token variable like this:
```
@token={{response.parsedBody.access_token}}
```
This is working perfectly fine if the request is just sent once (it takes a new token executing the login function, and then calls the post method with the bearer set), however if you try to use send repeat mode (sequential or parallel) with a count requests > 1, the method fails because the bearer is set like this:
```
POST http://<redacted url>/endpoint
accept-encoding: gzip, deflate, br
accept: "*/*"
authorization: Bearer {{response.parsedBody.access_token}}
content-length: 461
content-type: application/json
cookie: 4078455c9f8bf16322e56c424120b5bb=0aedb7b4a2ecd26aae8a2a3f168e4272
user-agent: httpyac
[Body]
``` 
Please note that the {{baseUrl}}, coming from the environment, is correctly expanded at runtime but the Bearer is not, leaving the value equal to the definition in the login function (so that the rest api will fail).
This is reproducible with the VSCode extension and the httpyac command line utils (same behavior).

Is it a bug or is there a way (or a workaround) to expand the value of the token variable at every request in the loop?

Thank you

**Comment by AnWeber** [comment]
The repeat was active for all requests. As a result, the body of the response is adjusted. However, the variable resolution no longer worked and was not changed. The solution is now, that only requests in the mainContext are repeated. This will be fixed with the next version.
