### ISSUE TITLE
Add option for how httpyac responds to 302 redirects

### ISSUE THREAD

**Issue by jrussellsmyth** [AnWeber/httpyac#563]
Many applications implement Post-Redirect-Get workflows, depending on the incorrect but common implementation in browsers to follow 302 redirect as a GET even when in response to a PUT. While this is technically non-standard/incorrect response, it is how most (if not all) web browsers respond and applications can depend on this. See https://www.theserverside.com/news/1365146/Redirect-After-Post#:~:text=Why%20redirect%20works,the%20following%20methods%3A

It would be nice if this handling of 302 were at least an option.. httpyac is currently spec compliant, but real world works differently.. perhaps @emulate-buggy-302 or something

**Comment by AnWeber** [comment]
I'll take a look at what exactly I need to do. But I totally rely on got's default behavior for the redirect.

**Comment by AnWeber** [comment]
@jrussellsmyth Just once in summary and as a query, if I have understood this correctly. With a POST/ PUT to an address the server will answer with a redirect. This redirect should not be processed as POST, but as a simple GET? So basically this use case, right?

```
POST https://httpbin.org/redirect-to?url=https://httpbin.org/get

{
  "test": "foo"
}
```

This use case can be solved relatively easily by yourself, but I will add a new metadata `# @post-redirect-get` for it, which adds got hook for beforeRedirect

```js
request.options.hooks.beforeRedirect.push((options: NormalizedOptions) => {
          options.method = 'GET';
          options.body = undefined;
        });
```

**Comment by jrussellsmyth** [comment]
> @jrussellsmyth Just once in summary and as a query, if I have understood this correctly. With a POST/ PUT to an address the server will answer with a redirect. This redirect should not be processed as POST, but as a simple GET? So basically this use case, right?
> 
> ```
> POST https://httpbin.org/redirect-to?url=https://httpbin.org/get
> 
> {
>   "test": "foo"
> }
> ```
> 
> This use case can be solved relatively easily by yourself, but I will add a new metadata `# @post-redirect-get` for it, which adds got hook for beforeRedirect
> 
> ```js
> request.options.hooks.beforeRedirect.push((options: NormalizedOptions) => {
>           options.method = 'GET';
>           options.body = undefined;
>         });
> ```

That is correct. i would like to try the workaround, but not quite understanding where i would do that?

**Comment by AnWeber** [comment]
Sorry, I should've just tapped it quickly
```
{{@request
  request.options.hooks.beforeRedirect.push((options) => {
    options.method = 'GET';
    options.body = undefined;
  });
}}

POST https://httpbin.org/redirect-to?url=https://httpbin.org/get

{
  "test": "foo"
}
```

**Comment by jrussellsmyth** [comment]
Yes this does exactly what was needed.. and i now i am much more clear on how to use the events bit! thank you.

**Comment by AnWeber** [comment]
I have released the new metadata `# @post-redirect-get` with v6.8.2.
