### ISSUE TITLE
Short javscript assertion form (?? js ....) should catch and fail on js exceptions rather than error and stop

### ISSUE THREAD

**Issue by jrussellsmyth** [AnWeber/httpyac#572]
when using the ?? assertion form for js tests, any javascript exception should be caught and reported as a failure, rather than halting execution.

this would make the use more consistent with the 

test("test description", ()=>{
}

form of testing, which will not completely halt a test even on bad js, as it will simply report. 

Example assertion that works in long form but not short form

```
###
# This does what we would expect.. reports the problem without halting execution
# ✖ access missing child (TypeError: Cannot read properties of undefined (reading 'child') - file.http:4:35)
GET https://www.google.com
{{
    test('access missing child', ()=>{
      var test = response.missing.child
    })
 
}}

###
# This errors and halts execution
GET https://www.google.com

?? js response.missing.child == "steve"

```

**Comment by AnWeber** [comment]
Hi, yes that makes sense. I overlooked that here the implementations differ. thanks.
