### ISSUE TITLE
RFE: Junit XML Report Test Cases should reveal information about assertions

### ISSUE THREAD

**Issue by mmadson** [AnWeber/httpyac#578]
Howdy @AnWeber the good news is that integration with gitlab is working! I see the test case page and timing information. 🎉 

However, I do think a bit more work is needed:

Given an httpyac http file containing:

```
### Test API Endpoint
POST {{host}}/v1/some-api
Content-Type: application/json

{
    "propertyKey1": "propertyValue1",
    "propertykey2": "propertyValue2"
} 
?? js response?.parsedBody?.responseArray?.length == 30

{{
  const assert = require('assert');
  test('test isFoo count', () => {
    assert.equal(
      response.parsedBody.responseArray.filter(e => e.isFoo).length, 
      10
    );
  });
  test('test isBar count', () => {
    assert.equal(
      response.parsedBody.responseArray.filter(e => e.isBar).length, 
      20
    );
  });
}}
```

Expectation is that the junit xml report would contain 1 test suite representing the overall http file and 3 test cases. One test case for `test isFoo count`, one test case for `test isBar count` and another test case for the total length of the responseArray where the test case name can be set to the condition text itself. Each test case tag should have attributes indicating ideally what line the test case starts on, what request fragment it belongs to and what http filename it appears in. 

Actual: Currently when we view the junit xml for this example in gitlab. Gitlab reports that only a single test was ran and the name of the test is the name of the request `Test Api Endpoint` The assertion count of the test case is not displayed in the UI and  even if we could somehow display the assertion count, when a single assertion fails, there isn't enough information to drill down and figure out which assertion failed. So really what we consider assertions should be promoted to test cases.

**Comment by mmadson** [comment]
Another option that would give us the same details on individual test assertions would be to have a test suite per request and a file could contain multiple test suites.

Another thing to note, if a request does not have any test assertions, it should probably be omitted from the report entirely. Currently I see a "test" for some of my setup auth requests that don't have assertions and that doesn't seem correct from a test report pov.

**Comment by AnWeber** [comment]
@mmadson maybe we should add a [testsuite in a testsuite](https://github.com/testmoapp/junitxml). 

```xml
<testsuite>
    <testsuite name="test.http" ...>
         <testsuite name="GET /foo (line 2)" ...>
             <testcase name="testCase1" classname="Tests.Registration" time="2.113871" />
             ....
          </testsuite>
    </testsuite>
</testsuites>
```

> Actual: Currently when we view the junit xml for this example in gitlab. Gitlab reports that only a single test was ran and ...

I will try to build an example with which I can test the behavior.

> Another thing to note, if a request does not have any test assertions, it should probably be omitted from the report entirely.

Yes agree

**Comment by mmadson** [comment]
There was no mind blown emoji that I could use to react with your comment but I had no idea you could nest test suites. Agree semantically that's a very nice option here. I'm also not sure how gitlab would handle nested test suites, but it's worth a shot. I'll try generating a static xml file with nested test suites to see what it would look like in gitlab first to see if it's even a worthwhile option for us. But agree the schema seems to support it. 🤞

**Comment by AnWeber** [comment]
using this exmple updated code generates this output. One problem is the wrong output, if the assert is generated by `?? status == 201`. Then the line number is not correct. But this is not new, but I just noticed. Otherwise it looks good
```
GET https://httpbin.org/anything
?? status == 200
{{
  const assert = require('assert');
  test("status test", () => {
    assert.equal(response.statusCode, 200);
  })
}}
GET https://httpbin.org/anything
{{
  const assert = require('assert');
  test("status test", () => {
    assert.equal(response.statusCode, 201);
  })
}}
GET https://httpbin.org/anything
?? status == 201
###
# @disabled
GET https://httpbin.org/anything
?? status == 200
GET https://httpbin.org/anything

```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="httpyac" tests="5" errors="0" disabled="1" failues="2" time="1.868">
  <testsuite name="assert.http" tests="5" failures="2" skipped="1" time="1.868" file="/home/andreas/github/httpyac/httpyac.github.io/examples/assert/assert.http">
    <testsuite name="GET https://httpbin.org/anything (line: 1)" tests="2" failures="0" skipped="0" package="assert.http" time="0.581">
      <properties>
        <property name="timestamp" value="2023-11-01T21:08:14.720Z"/>
      </properties>
      <testcase name="status == 200" assertions="1"/>
      <testcase name="status test" assertions="1"/>
    </testsuite>
    <testsuite name="GET https://httpbin.org/anything (line: 9)" tests="1" failures="1" skipped="0" package="assert.http" time="0.401">
      <properties>
        <property name="line" value="8"/>
        <property name="timestamp" value="2023-11-01T21:08:15.302Z"/>
      </properties>
      <testcase name="status test" assertions="1">
        <properties>
          <property name="displayMessage" value="AssertionError [ERR_ASSERTION]: 200 == 201 - /home/andreas/github/httpyac/httpyac.github.io/examples/assert/assert.http:13:12"/>
          <property name="file" value="/home/andreas/github/httpyac/httpyac.github.io/examples/assert/assert.http"/>
          <property name="line" value="13"/>
          <property name="offset" value="12"/>
          <property name="errorType" value="AssertionError [ERR_ASSERTION]"/>
          <property name="message" value="200 == 201"/>
        </properties>
        <failure message="status test" type="AssertionError [ERR_ASSERTION]"/>
        <system-err>{"message":"200 == 201","name":"AssertionError","stack":"AssertionError [ERR_ASSERTION]: 200 == 201\n    at /home/andreas/github/httpyac/httpyac.github.io/examples/assert/assert.http:13:12\n    at Object.test (/home/andreas/github/httpyac/httpyac/dist/index.js:2849:9)\n    at Object.userJS (/home/andreas/github/httpyac/httpyac.github.io/examples/assert/assert.http:12:3)\n    at runScript (/home/andreas/github/httpyac/httpyac/dist/index.js:9084:25)\n    at executeScriptData (/home/andreas/github/httpyac/httpyac/dist/index.js:9321:24)\n    at Object.action (/home/andreas/github/httpyac/httpyac/dist/index.js:9285:44)\n    at n.trigger (/home/andreas/github/httpyac/httpyac/node_modules/hookpoint/dist/index.js:1:2866)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async _HttpRegion.execute (/home/andreas/github/httpyac/httpyac/dist/index.js:3771:22)\n    at async sendHttpRegions (/home/andreas/github/httpyac/httpyac/dist/index.js:12200:12)"}</system-err>
      </testcase>
    </testsuite>
    <testsuite name="GET https://httpbin.org/anything (line: 16)" tests="1" failures="1" skipped="0" package="assert.http" time="0.390">
      <properties>
        <property name="line" value="15"/>
        <property name="timestamp" value="2023-11-01T21:08:15.703Z"/>
      </properties>
      <testcase name="status == 201" assertions="1">
        <properties>
          <property name="displayMessage" value="AssertionError [ERR_ASSERTION]: status (200) == 201 - /home/andreas/github/httpyac/httpyac/dist/index.js:3373:36"/>
          <property name="file" value="/home/andreas/github/httpyac/httpyac/dist/index.js"/>
          <property name="line" value="3373"/>
          <property name="offset" value="36"/>
          <property name="errorType" value="AssertionError [ERR_ASSERTION]"/>
          <property name="message" value="status (200) == 201"/>
        </properties>
        <failure message="status == 201" type="AssertionError [ERR_ASSERTION]"/>
        <system-err>{"message":"status (200) == 201","name":"AssertionError","stack":"AssertionError [ERR_ASSERTION]: status (200) == 201\n    at /home/andreas/github/httpyac/httpyac/dist/index.js:3373:36\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async test (/home/andreas/github/httpyac/httpyac/dist/index.js:2822:9)\n    at async Object.action (/home/andreas/github/httpyac/httpyac/dist/index.js:3362:11)\n    at async n.trigger (/home/andreas/github/httpyac/httpyac/node_modules/hookpoint/dist/index.js:1:2849)\n    at async onResponse (/home/andreas/github/httpyac/httpyac/dist/index.js:1684:7)\n    at async Object.action (/home/andreas/github/httpyac/httpyac/dist/index.js:1578:16)\n    at async n.trigger (/home/andreas/github/httpyac/httpyac/node_modules/hookpoint/dist/index.js:1:2849)\n    at async _HttpRegion.execute (/home/andreas/github/httpyac/httpyac/dist/index.js:3771:22)\n    at async sendHttpRegions (/home/andreas/github/httpyac/httpyac/dist/index.js:12200:12)"}</system-err>
      </testcase>
    </testsuite>
    <testsuite name="GET https://httpbin.org/anything (line: 20)" tests="1" failures="0" skipped="1" package="assert.http" time="0.000">
      <properties>
        <property name="line" value="18"/>
        <property name="timestamp" value="2023-11-01T21:08:16.094Z"/>
      </properties>
      <testcase name="skipped all tests">
        <skipped/>
      </testcase>
    </testsuite>
    <testsuite name="GET https://httpbin.org/anything (line: 22)" tests="0" failures="0" skipped="0" package="assert.http" time="0.495">
      <properties>
        <property name="line" value="21"/>
        <property name="timestamp" value="2023-11-01T21:08:16.094Z"/>
      </properties>
    </testsuite>
  </testsuite>
```

**Comment by mmadson** [comment]
Much closer @AnWeber few more fixes I think we need:

- When the test case does not have a name but is a javascript expression, it looks like we're not escaping the attribute contents correctly. 

Expected:

```xml
            <testcase
                name="response?.parsedBody?.snippetDecisions?.filter(d =&gt; !d.sensitive)?.length == 1"
                assertions="1" />
```

Actual:

```xml
            <testcase
                name="response?.parsedBody?.snippetDecisions?.filter(d => !d.sensitive)?.length == 1"
                assertions="1" />
```

Additionally it seems that not including the time attribute on the test case itself, breaks the duration reporting in gitlab. I realize getting accurate timing information for each assertion is unlikely so I'm not really sure how to solve this problem. Currently I see 0s for all the test durations in gitlab. =/

Also it looks like gitlab can't figure out how to associate a testcase with a testsuite name despite them being nested. I used the example xml from the link you provided earlier and that seemed to work so I believe gitlab uses the `classname` attribute of the testcase tag to populate the testcase's test suite, if we can duplicate the test suite name as the test cases classname attribute that should solve this problem. I think we'll also want to include the filename as the file attribute of the testcase as well so it shows up in the UI.

**Comment by AnWeber** [comment]
I added a new edge docker image to simplify tests in gitlab. It uses latest main: `ghcr.io/anweber/httpyac:edge`

https://github.com/AnWeber/httpyac/pkgs/container/httpyac/143649374?tag=edge

**Comment by mmadson** [comment]
@AnWeber 

tested edge on my gitlab functional test job. 

- test case durations look good even though they are faked
- filename links look good
- test suite names look good
- test case names make sense from the assertion name / assertion condition.

One thing I noticed when testing out the docker container is that httpyac doesn't seem to be on the container's path. My usage of the container looks something like this:

```
functional-test-staging:
  image: ghcr.io/anweber/httpyac:edge
  stage: test
  tags:
    - k8s
  script:
    - cp -f $HTTP_CLIENT_PRIVATE_VARS_FILE http-client.private.env.json
    - /httpyac/bin/httpyac.js send functional-test.http -a -e stg --junit > functional-test.xml
  artifacts:
    when: always
    paths:
      - functional-test.xml
    reports:
      junit: functional-test.xml
```

It'd be super cool if instead of having to know that httpyac.js is located at /httpyac/bin, if /httpyac/bin was included in the container's PATH env var, ideally without the js extension so that my gitlab yaml could look like:

```
functional-test-staging:
  image: ghcr.io/anweber/httpyac:edge
  stage: test
  tags:
    - k8s
  script:
    - cp -f $HTTP_CLIENT_PRIVATE_VARS_FILE http-client.private.env.json
    - httpyac send functional-test.http -a -e stg --junit > functional-test.xml
  artifacts:
    when: always
    paths:
      - functional-test.xml
    reports:
      junit: functional-test.xml
```

Other than that, I think we're good to go!

<img width="752" alt="image" src="https://github.com/AnWeber/httpyac/assets/1190456/f4187a4e-134f-4372-ae57-9d0ac597d30a">

**Comment by AnWeber** [comment]
> It'd be super cool if instead of having to know that httpyac.js is located at /httpyac/bin, if /httpyac/bin was included in the container's PATH env var

should work with the next edge/ release. I added a npm link command to allow global usage of httpyac in docker

**Comment by mmadson** [comment]
Getting an unusual error with both edge image and 6.9.3

```
$ httpyac send functional-test.http -a -e stg --junit > functional-test.xml
[Error: ENOENT: no such file or directory, scandir 'stg'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'stg'
}
```
Seems like something with the env specifier changed? Will dig into the code to see if I can figure it out.

**Comment by AnWeber** [comment]
@mmadson I don't have the error right now. I have tested it with similar command with [this setup structure](https://github.com/httpyac/httpyac.github.io/tree/fc6351903c7efccf9d43be8130eceb48b7c0261e/examples/project/environments)

```sh
 httpyac send test.http -a -e dev --junit > functional-test.xml
```

**Comment by mmadson** [comment]
> @mmadson I don't have the error right now. I have tested it with similar command with [this setup structure](https://github.com/httpyac/httpyac.github.io/tree/fc6351903c7efccf9d43be8130eceb48b7c0261e/examples/project/environments)
> 
> ```shell
>  httpyac send test.http -a -e dev --junit > functional-test.xml
> ```

Is your test running from within the docker container by chance? That's where I'm seeing the error. If I install httpyac, everything seems to work okay but when trying to run from within the container via gitlab that's when I run into this issue.

**Comment by AnWeber** [comment]
No, did not run in docker. But seems also fine
<img width="598" alt="image" src="https://github.com/AnWeber/httpyac/assets/13434739/bb0204ab-b83c-4ed9-b586-f16d7e3856eb">

I took a look at the code that uses the environment and simply used an empty array as [a fallback in the event of an error](https://github.com/AnWeber/httpyac/commit/a1d65c8adbcd8fcfb31ab25d9c1d79301711bf6f).

**Comment by mmadson** [comment]
Sorry for not being precise, when I say run within a container what I mean is that when I define a step in my gitlab ci yaml file such that the image is httpyac:edge or httpyac:some-version-id gitlab pulls the image and starts an instance of the container, then it pulls all the repo files and copies the files into the container owned by the root user and root group. My repo files contains my http functional test file. I believe it copies the files into the cwd of the container which would be the /data dir. Then it executes each command defined in the gitlab yaml file as if you were running from a bash shell within the container. 

So to simulate my error scenario, you'd need to somehow get a sample http file inside the container, connect to the running container's bash shell and then execute httpyac from within the container targeting the sample http file. 

I suspect it's some kind of user or permissions issue, maybe because the file is owned by root and the current user is set to node? Not entirely sure what the root cause of the error is. 

I can easily switch back to not using the httpyac docker image for my gitlab step and instead targeting a regular node image and then using npx to install and run httpyac without issue, but not having to "install" httpyac would be a nice optimization if possible.

**Comment by mmadson** [comment]
please disregard my last few comments on the docker image bug, turns out it was entirely unrelated. My gitlab yaml was defining an environment variable to define which environment to pass to the `-e` flag and it just so happened the env variable I used was `HTTPYAC_ENV` and apparently this is a special reserved env variable that was messing up the execution of my tests. Didn't have anything to do with the docker image. Changing it to SELECTED_ENV fixed everything up. 

As such this is working perfectly:

```
functional-test:
  image: ghcr.io/anweber/httpyac:6.9.3
  stage: test
  tags:
    - k8s
  rules:
    - if: '$RUN_FUNCTIONAL_TEST_STAGING == "true" && $FUNCTIONAL_TEST_PIPELINE == "true"'
      variables:
        SELECTED_ENV: "stg"    
    - if: '$RUN_FUNCTIONAL_TEST_PRODUCTION == "true" && $FUNCTIONAL_TEST_PIPELINE == "true"'
      variables:
        SELECTED_ENV: "prd"
  script:
    - cp -f $HTTP_CLIENT_PRIVATE_VARS_FILE http-client.private.env.json
    - httpyac send functional-test.http -a -e "$SELECTED_ENV" --junit > functional-test.xml
  artifacts:
    when: always
    paths:
      - functional-test.xml
    reports:
      junit: functional-test.xml    
```

Thanks again for all your help with this. Feel free to consider this issue and feature request resolved. =)

**Comment by AnWeber** [comment]
:-) The variables `HTTPYAC_ENV` and `HTTPYAC_PLUGIN` are currently still too well hidden. I am not sure whether I have already included them in the documentation. I added them once at short notice so that I don't always have to copy my .env files into every project.
