### ISSUE TITLE
Why is my request executed twice?

### ISSUE THREAD

**Issue by yangchnet** [AnWeber/httpyac#580]
httpyac.config.js
```js
module.exports = {
    cookieJarEnabled: true
  }
```

test.http
```http
###
# @name create_product
POST /api/v1/product
{
    "name": "foo"
}

{{
    exports.productId = response.parsedBody.data;
}}

###
# @ref create_product
{{
    console.log(productId)
}}
```

When I clicked `send`, the create_product interface was executed twice.The problem seems to be with `@ref` but I don't know how to fix it

**Comment by AnWeber** [comment]
I have the idea of [global region](https://httpyac.github.io/guide/request.html#request-separators), with which you can add instructions in all region of an Http file. A global region is a region without request and without name.
This way you refer to the same request again in the request. I have considered that it is possible and not prevented. The referenced request is executed and then the one that is currently in progress. Consequently 2 requests.

```
###
# @name create_product
# @ref create_product
{{
    console.log(productId)
}}
POST /api/v1/product
{
    "name": "foo"
}

{{
    exports.productId = response.parsedBody.data;
}}
```
