### ISSUE TITLE
gRPC requests returning streams seem to be mishandled

### ISSUE THREAD

**Issue by sdasda7777** [AnWeber/httpyac#596]
Hi, I tried to set up a gRPC request to service that is supposed to return stream:

```protobuf
package mypackage;
service MyService {
  rpc ListStuff (EmptyMessage) returns (stream Stuff) {}
}
message EmptyMessage {}
message Stuff { string stuffId = 1 }
```

with request like this:

```httpyac
GRPC /MyService/ListStuff
```

However when running the file using `httpyac --all requests.http`, I only get short message stating
```
service MyService not found. Similar service mypackage.MyService is used.
```
and nothing else (program immediately terminates successfully). Any asserts (such as `?? status == 0`) seem to be ignored, the request isn't even mentioned in the summary when there are other requests (isn't counted as requests processed, succeeded or failed).

I admit it might be me doing something wrong, but omitting the request in the summary definitely seems like either a bug or a massive footgun.

**Comment by sdasda7777** [comment]
Hi, thanks for the reply. I do import the proto file, and I think that part is correct, because the other requests work as expected:
```httpyac
proto < ./proto/myservice.proto
@host=localhost:3000
```
For my purposes I rewrote the proto file to use `repeated` instead of `stream`, and it works as expected, but it would be nice if the `stream` way worked as well.

**Comment by AnWeber** [comment]
@sdasda7777 I would probably need help with that. I have just successfully tested the call with `grpc.postman-echo.com/HelloService/LotsOfReplies` ([docs](https://httpyac.github.io/guide/request.html#server-streaming-rpc)). The call actually looks identical to your example. Could you please customize it so that it generates the error as you did.

> hello.proto
```proto
syntax = "proto2";
service HelloService {
  rpc LotsOfReplies(HelloRequest) returns (stream HelloResponse);
}
message HelloRequest {
  optional string greeting = 1;
}
message HelloResponse {
  required string reply = 1;
}
```

> stdout
```sh
> httpyac grpcServerStreaming.http --all
21:31:02 - LotsOfReplies:  {
  "reply": "hello world"
}
...
---------------------

GRPC grpc.postman-echo.com/HelloService/LotsOfReplies
Accept: */*
User-Agent: httpyac

{
  "greeting": "world"
}

GRPC 0  - OK
content-type: application/grpc+proto
date: Sat, 02 Dec 2023 20:31:02 GMT

{
  "responses": [
      ...
   ]
}
```

**Comment by sdasda7777** [comment]
Hi, that's strange, I can replicate it with these files. I checked my `httpyac --version` and it's `6.6.7`, is that outdated?

**Comment by sdasda7777** [comment]
It seems to be working on `6.6.10`. Thank you and sorry for wasting your time 😅
