### ISSUE TITLE
Undocumented caching-like behaviour

### ISSUE THREAD

**Issue by audunmo** [AnWeber/httpyac#609]
I'm seeing some strange caching-like behaviour in some of my tests. Can't seem to find it documented anywhere, and it seems to me like it's unintentional

The app that is being tested is a thin wrapper around a third-party user management software. It can only respond to `PATCH` requests, and setting a field in the body to `null` should delete that field from the user in the third-party system

The issue arises when I run these two tests right after one another:
```javascript
###
# @title add subscription level
  // Randomly generated each key-value pair, so that we know the entries are from _this_ run
  const crypto = require("crypto")
  const value = `httpyac-${crypto.randomBytes(20).toString('hex')}`;

  exports.value = value
}}

PATCH {{$host}}/metadata/v1/
...defaultHeaders

{
  "userId": "<SOME_ID>",
  "access": {
    "subscription": "{{value}}"
  }
}

?? status == 200

{{
  const { equal } = require("assert");

  const user = await users.get({id:"<SOME_ID>"})
  test("got right values back: all fields updated", () => {
    equal(user.subscription, value)
  })
}}

###
# @title delete subscription field from user
PATCH {{$host}}/metadata/v1/
...defaultHeaders

{
  "userId": "<SOME_ID>",
  "access": {
    "subscription": null
  }
}

?? status == 200

{{
  const { equal } = require("assert");

  let user = await users.get({id:"<SOME_ID>"})
  user = await users.get({id:"<SOME_ID>"})

  test("subscription field deleted", () => {
    equal(user.subscription, undefined)
  })
}}

```

Doing this, `user.subscription` still retains the value as it was computed by the previous test, resulting in the following error:

```sh
subscription field deleted (AssertionError [ERR_ASSERTION]: 'httpyac-f750382b199e8a48093bf67cd0225fb35803e5d3' == undefined - /Users/audunmo/work/cloud-account-metadata/test/httpyac/delete.http:79:5
```

However, checking application logs, outgoing http responses, and the user management system, I can see that the deletion actually went through. This clued me in to that there may be some caching going on here. 

Interestingly, performing any arbitrary javascript before the request causes the caching to be avoided, and the second test to pass as expected.
```javascript
# @title delete subscription field from user
{{
  const x = 2
}}
PATCH {{$host}}/metadata/v1/
...defaultHeaders

{
  "userId": "<SOME_ID>",
  "access": {
    "subscription": null
  }
}

?? status == 200

{{
  const { equal } = require("assert");

  let user = await users.get({id:"<SOME_ID>"})
  user = await users.get({id:"<SOME_ID>"})

  test("subscription field deleted", () => {
    equal(user.subscription, undefined)
  })
}}
```

So for me, this seems like a bug. I'm _assuming_ that what's happening here is that there's a proxy intended to cache responses from the app that's under testing, and that it's set as a global proxy. This intercepts all requests, and the check that I have outgoing to the third-party service is being "caught in the cross-fire" so to speak.

I don't love my workaround. Is there any other approach to doing this? @no-proxy on the test has no impact. Setting `Cache-Control: no-store` on the either the tests or the third-party client also does nothing

**Comment by AnWeber** [comment]
@audunmo httpyac already caches a few values between requests. This involves the variables that can be reused in the next request. but I think the cause is the logic behind `users.get`. How is this created? 
The best would be a minimal example with e.g. postman-echo.com to reproduce the error. In the current example there are too many unknowns and noise:
- not defined defaultHeaders and host
- missing script start in line 2
- is `@title` needed to produce bug? Is `?? status == 200` needed to produce bug?
- logic of `await users.get` is unknown and why is it called two times in a row in second request?
