### ISSUE TITLE
IntelliJ variables aren't shared between files/environments in VSCode

### ISSUE THREAD

**Issue by le0nik** [AnWeber/httpyac#612]
Hello, and thank you for working on this project!

I am currently using version `6.11.1` of the [VSCode extension](https://marketplace.visualstudio.com/items?itemName=anweber.vscode-httpyac) and I'm encountering an issue with making variables set in one file/environment available in another file/environment. Here's a simplified example:

I run the first request with one file and environment `ENV1`:
```
POST {{url}}
Accept: application/json
Content-Type: application/x-www-form-urlencoded

> {%
    client.global.set("accessToken", response.body.access_token);
%}
```

Then, I run the second request from a different file and environment `ENV2`:
```
POST {{otherUrl}}
Accept: application/json
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{accessToken}}
```

The result of the second request is: `ReferenceError: refreshToken is not defined at Object.userJS`.

However, if the second request is executed in the same file and environment, the `accessToken` variable is available.

I found a similar issue  where it was [mentioned](https://github.com/AnWeber/httpyac/issues/14#issuecomment-826697217) that environment variables should be available for the lifetime of the extension.

Did I misunderstand that statement or has there been a change where sessions/variables are now tied to their specific environments? This feature would be very useful, and it is already functioning in IntelliJ products.

**Comment by AnWeber** [comment]
I interpret a environment as different systems (e.g. prod vs dev). And I never share variables between environments. Intellij Global Store follows this definition ([see](https://github.com/AnWeber/httpyac/blob/main/src/plugins/intellij/intellijGlobalVariableProvider.ts#L6)). Does Intillij share variables between environments?

**Comment by AnWeber** [comment]
will be fixed with next release
