### ISSUE TITLE
the command donot work, only replied help information. 

### ISSUE THREAD

**Issue by heliping** [AnWeber/httpyac#63]
Thanks for the httpyac, the script funciont is amazing, but the command sounds donot work.
it just replied the help info, no error, I cannot catch any info.
`PS C:\hlp\02src\mygo\huaxrobot> httpyac .\tests\apitest\backapi.http --all
send http requests of .http or .rest

usage: httpyac [options...]
--all execute all http requests in a http file
--editor enter a new request and execute it
-e --env list of environemnts
--filter filter requests output (only-failed)
-h --help help
--insecure allow insecure server connections when using ssl
-i --interactive do not exit the program after request, go back to selection
--json use json output
-l --line line of the http requests
-n --name name of the http requests
--no-color disable color support
-o --output output format of response (short, body, headers, response, exchange, none)
--output-failed output format of failed response (short, body, headers, response, exchange, none)
--raw prevent formatting of response body
-r --repeat repeat count for requests
--repeat-mode repeat mode: sequential, parallel (default)
-s --silent log only request
--timeout maximum time allowed for connections
-v --verbose make the operation more talkative
--version version of httpyac
PS C:\hlp\02src\mygo\huaxrobot> `

**Comment by AnWeber** [comment]
The cause is probably that the file is not found. I have unfortunately currently coded that if the file is not found, the help is simply rendered instead of displaying an error message.
If you use the following command, all *.http files below the current directory will be displayed.

```
httpyac **/*.http
```
