### ISSUE TITLE
Property with a hyphen cannot be verified

### ISSUE THREAD

**Issue by rabestro** [AnWeber/httpyac#640]
if a JSON response contains properties with a hyphen, then such properties cannot be checked.

### The sample request

```http
https://piglatin.azurewebsites.net/actuator/info

?? status == 200
?? body java.version startsWith 17
?? body app.source-code endsWith pig-latin-rest
?? body app.source-code contains rabestro
?? body os.name == Linux
```

### Test Results

✓: status == 200
✓: java.version startsWith 17
✖: app.source-code endsWith pig-latin-rest (ReferenceError: code is not defined - Object.userJS (/Users/jegors/Projects/engx-advanced/pig-latin-rest/http-yac/actuator/server-info.http:2:70)
✖: app.source-code contains rabestro (ReferenceError: code is not defined - Object.userJS (/Users/jegors/Projects/engx-advanced/pig-latin-rest/http-yac/actuator/server-info.http:2:70)
✓: os.name == Linux

**Comment by AnWeber** [comment]
The reason for the behavior is how I resolve the path `body app.source-code` for accessing the body. I use Javascript and this is not valid with the hyphen. As a result, the validation fails. Rewrite your test to this notation.
```
https://piglatin.azurewebsites.net/actuator/info

?? status == 200
?? body java.version startsWith 17
?? body app["source-code"] endsWith pig-latin-rest
?? body app["source-code"] contains rabestro
?? body os.name == Linux
```

I don't want to change that behavior directly. An alternative would be to create an extra JSON Path Assert that works similar to [XPath Assert](https://httpyac.github.io/guide/assert.html#xpath-assert).

**Comment by rabestro** [comment]
> ["source-code"]

This is a perfect solution for me. I'm not very familiar with Javascript, and that's the reason why I stumbled on this.
