### ISSUE TITLE
Assertions for numbers don't work

### ISSUE THREAD

**Issue by rabestro** [AnWeber/httpyac#641]
### The request to actuator

```http
https://piglatin.azurewebsites.net/actuator/translation-count

?? status == 200
?? body count isNumber
?? body count >= 0
```

### Test Results

✓: status == 200
✓: count isNumber
✖: count >= 0 (AssertionError [ERR_ASSERTION]: count (29) >= 0 - /Users/jegors/.vscode/extensions/anweber.vscode-httpyac-6.11.4/dist/extension.js:191:46440)

**Comment by rabestro** [comment]
![image](https://github.com/AnWeber/httpyac/assets/52966251/ee0ff1f5-e2b6-4609-bc4d-4d91d9295d68)

**Comment by AnWeber** [comment]
Assertion for value 0 was converted to a false value. v6.11.4 fixes this error
