### ISSUE TITLE
JUnit report doesn't parsed correctly

### ISSUE THREAD

**Issue by rabestro** [AnWeber/httpyac#642]
### httpYac: JUnit report in XML format

https://github.com/rabestro/pig-latin-rest/runs/21941439938

![image](https://github.com/AnWeber/httpyac/assets/52966251/86c01a9b-0e10-4dc4-8a96-c85e97070e1c)

### Bruno: JUnit report in XML format

https://github.com/rabestro/pig-latin-rest/runs/21941579014

![image](https://github.com/AnWeber/httpyac/assets/52966251/e64ae4c0-1389-4fb8-b0e3-c9a5a7b3b68f)

**Comment by AnWeber** [comment]
there was a typo in the report.xml (failues instead of failures). released with v6.11.4
