### ISSUE TITLE
Incorrect output order in CLI output

### ISSUE THREAD

**Issue by vojtech-pejsa-redbit** [AnWeber/httpyac#644]
Hi and thank you for this wonderful tool :slightly_smiling_face:.

I have found small bug with output order when running from cli.

## test.http
```
### test 1

GET https://reqres.in/api/users/2

?? status == 400

### test 2

GET https://reqres.in/api/users/2

?? status == 401
```

## output
```bash
httpyac send test.http --all --output short --output-failed short
```

![obrazek](https://github.com/AnWeber/httpyac/assets/110399091/914f85c7-8d51-4afa-ad96-ffd6f91d007e)

## Affected versions

I replicated this behavior with current version (6.11.4), first version with this output is 6.6.3, version 6.6.2 works fine.

## Related issues

I am not sure if this issue is the same as https://github.com/AnWeber/httpyac/issues/237, but it looks similar.

**Comment by AnWeber** [comment]
thanks for the hint with the version. You were right Commit https://github.com/AnWeber/httpyac/commit/e4f867aec751046744de467f935662c387df40cf was the culprit. I have a hen/egg problem. I only want to issue the request if the tests are successful. However, the tests should appear after the request. I added a special log method to support changing order for the log messages
