### ISSUE TITLE
How to read or send existing sessions or cookies from other domains?

### ISSUE THREAD

**Issue by sir-farfan** [AnWeber/httpyac#645]
At some point, the test sets a session or cookie that I can see in the left panel. As the docs says, it's sent automatically as long as the domain is the same...

Is there a way I can snatch that cookie and send it to other domain?

I saw the [sessionStore](https://httpyac.github.io/plugins/plugin-api.html#sessionstore) thing but I'm not sure it can be used during a request pre-script.

```
{{
    exports.session = require('session');
}}

# @title snatch-cookie
GET https://httpbin.org/get
Cookie: foo={{session.getUserSession("named_cookie_from_testdomain_com")}}
```

I could still grab it by adding the @no-redirect and manually following... but doing so doesn't really adds to the test...

Any alternatives?

**Comment by AnWeber** [comment]
You can require httpyac and get access to my api. Then you should theoretically also be able to append the cookies in CookieJar (see https://github.com/AnWeber/httpyac/blob/main/src/plugins/http/cookieJarInterceptor.ts#L26-L45)
```
@host=https://httpbin.org
###
GET /cookies/set?foo=bar
###
{{
   const {store} = require("httpyac");
   console.info( store.userSessionStore.userSessions.filter(s => s.type === 'Cookie').map(s => s.id));
}}

GET /cookies
```
