### ISSUE TITLE
Feature Request - Conditional @disabled

### ISSUE THREAD

**Issue by jrussellsmyth** [AnWeber/httpyac#652]
it would be very useful to conditionally disable regions via meta code - just for readability and brevity. I know its possible via script

{{
  httpRegion.metaData.disabled = {{boolean condition}}
}}

but it would be even nicer if the @disabled meta could accept a condion

@disabled = {{boolean condition}}

**Comment by AnWeber** [comment]
I have actually implemented it (see [code](https://github.com/AnWeber/httpyac/blob/bd53d7d73e2803044922a3f0abe6232741aeb144/src/plugins/core/execute/disabledInterceptor.ts#L30)). If disabled is not a boolean content in metadata is interepreted as Javascript.. Accessing the variable may be silly, but that could be solved with a global variable. What is the problem?

```
@condition={{true}}
# @disabled this["condition"]
GET https://httpbin.org/json
```

**Comment by jrussellsmyth** [comment]
This pretty much is what we needed, just not in the docs. Thanks!
