### ISSUE TITLE
Possible to do json schema validation for API testing

### ISSUE THREAD

**Issue by humbienri** [AnWeber/httpyac#657]
Hi all,

I'm new here and I am interested in maybe using Httpyac for doing RESTful API testing and migrating away from Postman. I've read through your docs but I am still not convinced that it is possible to use some library, ajv I suppose, for doing json schema validation of API responses. Is it doable?  If so, can you point me to some documentation on the matter?

In advance, thank you for any insights you can share. And, of course, for Httpyac!

**Comment by AnWeber** [comment]
JSON schema validation should be relatively easy. Here is the example. You could also write an httpyac plugin for this, but since I mostly test my own servers, which are created using OpenAPI, I don't have much use for it.
```
GET https://postman-echo.com/get
{{
  const Ajv = require("ajv")

const schema = {
  type: "object",
  properties: {
    args: {type: "object"},
    url: {type: "string"}
  },
  required: ["url"],
  additionalProperties: false
}


test('has invalid json schema', () => {
  const ajv = new Ajv();
  const validate = ajv.compile(schema)
  const valid = validate(response.parsedBody)
  if (!valid) {
    console.error(validate.errors)
    throw new Ajv.ValidationError(validate.errors);
  }
});
}}
```

**Comment by humbienri** [comment]
Thank you very much @AnWeber. Your provided example was great, more than I was expecting so I definitely look forward to trying out.

However, your statement about testing your own servers and lack of use case left me wondering, is this tool, httpyac, meant mostly for your own usage? Not interested in wide-spread adoption? Or, you don't have a separate "test team" writing up automated tests for usage in some CI/CD system?

**Comment by AnWeber** [comment]
> httpyac, meant mostly for your own usage? Not interested in wide-spread adoption? Or, you don't have a separate "test team" writing up automated tests for usage in some CI/CD system?

I do too little advertising for the tool. I should actually advertise the tool more actively to achieve a higher usage rate, but at the moment time with my children is more important to me. I also realized that I shouldn't just integrate all the features directly into the tool. I would like to build up more contributors who are familiar with the core of the program. For that reason, it should be more of an incentive on how you integrate the feature into the tool and create a PR.
