### ISSUE TITLE
Case-sensitve headers

### ISSUE THREAD

**Issue by reed1** [AnWeber/httpyac#660]
Any headers mentioned in http files are transformed to lowercase before sending it to target URL. Some of the Http / API Server recognize the  'Authorization' headers but not 'authorization'. The request fail in this case. Is there a config to let headers to be sent with the same case?

**Comment by AnWeber** [comment]
No. The lowercase transformation happens in NodeJS code. My client dies not change the casing. But the real fault lies with the server. The rquest header are caseinsensitive. See https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

**Comment by reed1** [comment]
Apparently got does this

![image](https://github.com/AnWeber/httpyac/assets/1814324/d0fca389-bc5c-48a9-9847-cf1abe9f1b60)

Let's see if I can fork httpRequestClient.ts to use native fetch or others. I know the server is at fault, but as client, modifying request is the only thing we can do. Thank you for looking into this, closing..

**Comment by AnWeber** [comment]
@reed1 You would simply have to implement [the two methods in a similar way to here](https://github.com/AnWeber/httpyac/blob/main/src/plugins/http/registerHttpPlugin.ts#L16-L17). The entire got functionality is called by these two methods. `createRequestClient ` is responsible to fetch user defined requests. The `exchange` method is only using in httpyac calls, e.g. in the [OAuth2 provider](https://github.com/AnWeber/httpyac/blob/main/src/plugins/oauth2/flow/requestOpenIdInformation.ts#L37).
