### ISSUE TITLE
JUnit report generated incorrectly

### ISSUE THREAD

**Issue by rabestro** [AnWeber/httpyac#673]
Repository: 
https://github.com/rabestro/exercism-azure-ijhttp

### Report by httpYac
https://github.com/rabestro/exercism-azure-ijhttp/actions/runs/8710306329/job/23891955415

![image](https://github.com/AnWeber/httpyac/assets/52966251/9d0f02ef-d5d8-4137-8103-e22785d85dfb)

### Report by JetBrains HTTP Client

https://github.com/rabestro/exercism-azure-ijhttp/actions/runs/8710194524/job/23891565627

![image](https://github.com/AnWeber/httpyac/assets/52966251/96a37f1e-6efd-428f-845d-ac4a61fa0734)

**Comment by AnWeber** [comment]
I actually relied on the scheme on this [page](https://llg.cubic.org/docs/junit/). Unfortunately, it seems that testsuite is not allowed to be inside testsuite as it is with [junit5 itself](https://github.com/junit-team/junit5/blob/main/platform-tests/src/test/resources/jenkins-junit.xsd) or [jest](https://github.com/jest-community/jest-junit/blob/master/__tests__/lib/junit.xsd). Small detail but the format is broken. I have already found 4 different variants of this xsd. after a search.  I will now build the most basic xml valid to all of the xsd.
