### ISSUE TITLE
Feature Request: Tag support

### ISSUE THREAD

**Issue by mmadson** [AnWeber/httpyac#693]
Hi again @AnWeber 

Got another feature request idea and possibly another opportunity for me to contribute!

Thanks to the junit output support, our team is trying out httpyac for our basic functional web api tests on one of our projects. 

One feature, however, that we miss from other testing frameworks -- such as junit -- is the ability to tag tests (or rather http requests in httpyac's case) and then specify the tags to run from the cli. 

For example, say we have 2 http files:

```
# file1.http

 # @tag smoketest
GET https://httpbin.org/json
```

```
# file2.http

 # @tag smoketest
GET https://httpbin.org/json

 # @tag perftest
GET https://httpbin.org/json
```

Then say we want to run the 2 smoke tests in file1 and file2. It would be nice if we could call:

```
httpyac ./tests/* --includeTags smoketest -e dev --junit
```

And of course if we only want to run the single perf test in file2 we could call:

```
httpyac ./tests/* --includeTags perftest -e dev --junit
```

I think this tag info may also be useful in the junit xml reports, but that'd be a stretch goal IMO.

Let me know what you think. If you are open to the idea I can take a stab at the initial implementation.

**Comment by mmadson** [comment]
> I'm not a fan of `--includeTags` and would use `--tag` instead, but otherwise I think the feature makes a lot of sense. I added it into httpyac CLI. I still have to figure out the necessary steps for the testrunner in vscode-httpyac

Incredible, thank you soo much!

**Comment by skirankumars31** [comment]
I totally miss this feature. Glad to learn that its already in the works

**Comment by AnWeber** [comment]
I have now released the tag feature. You can use `# @tag foo, bar` to set multiple tags per httpregion. In CLI it is possible to execute only certain tags with `--tag=foo`. In VSCode you can set a filter based on the tags. However, both require that I have to parse all files and therefore more CPU is needed.

**Comment by mmadson** [comment]
Thanks again @AnWeber , we'll be incorporating this into our test suite shortly.
