### ISSUE TITLE
Spurious "c" environment

### ISSUE THREAD

**Issue by sedubois** [AnWeber/httpyac#700]
My files `http-client.env.json` and `http-client.private.env.json` only contain keys `localhost` and `staging`, but in the environment selector appears a spurious third environment named "c".

![Screenshot 2024-05-29 at 08 48 15](https://github.com/AnWeber/httpyac/assets/4217871/1cc88095-8742-4588-b055-52289b6d9307)

**Comment by AnWeber** [comment]
I search the following places for environments. One of them seems to contain a c.

- `.env` files (e.g c.env or env.c) <= my blind guess if your project has c code in it
- `http-client.env.json` or `http-client.private.env.json`
- local file `.httpyacjs` or `httpyac.config.json`
- `package.json` with property httpyac

**Comment by sedubois** [comment]
@AnWeber The culprit is an `.envrc` file at the root of the repository. When removing that file, the "c" environment disappears. Apparently the check for `.env` files is not specific enough and picks up that file when it shouldn't.

**Comment by AnWeber** [comment]
@sedubois  thx for the hint to `.envrc`. I added a fix to the dotenv provider
