### ISSUE TITLE
Comment Highlighting Missing

### ISSUE THREAD

**Issue by gillesdb** [AnWeber/httpyac#703]
Hi, Thank you for your great work! I recently switched from the REST Client to httpYac and I really like it. However, I noticed that one feature I miss is the highlighting of comments.

In the REST Client extension, the comments are highlighted clearly, but in httpYac, they are not as distinct:

REST Client:
![image](https://github.com/AnWeber/httpyac/assets/6920693/cefab86d-e98a-4680-8ad3-a191e5a8733c)

httpYac:
![image](https://github.com/AnWeber/httpyac/assets/6920693/41c20b18-0e11-4852-9b13-94fc6a281246)

Is this something that can be resolved through the settings? I searched but couldn't find any solution. Could you please take a look at this issue? Thank you in advance!

**Comment by AnWeber** [comment]
Not through the settings. The order of the regex does not fit somehow. I have fixed it the easy way and have not yet looked for the reason why the `request-line` does not close the area correctly. But it works
