### ISSUE TITLE
Slack/Discord channel to ask and answer questions regarding the product

### ISSUE THREAD

**Issue by skirankumars31** [AnWeber/httpyac#704]
It would be nice to have a community in discord or slack to ask and answer usual technical questions. I think it would be great feedback mechanism in addition to the github issues. I appreciate the work done by the team to make this project as good as possible.

Thanks
Kiran

**Comment by AnWeber** [comment]
Okay, convinced. I'll set up a Discord server and set it up. Any suggestions for bots or channels that are needed are also welcome. The invitation link should already work:

https://discord.gg/eTc4MyRh6P

**Comment by skirankumars31** [comment]
Joined the discord httpyac community
