### ISSUE TITLE
Feature Request - Only

### ISSUE THREAD

**Issue by skirankumars31** [AnWeber/httpyac#711]
Hi, 

With disabled metadata we are able to disable the tests we dont want to run. But while developing tests we concentrate on one test. I was wondering if adding a only metadata makes sense here. If a test has a only metadata then only that test is run and others without that are ignored. Cypress and Playwright has similar functionality and i use them a lot and it eases the overload while developing and lets me concentrate on a single test. 

Thanks 
Kiran

**Comment by AnWeber** [comment]
The feature could currently be recreated. You could create a tag `only` (`# @tag only`) and only execute region with tag `only`. 

But I don't think that alone is enough. With jest/vitest I use a `--watch` feature in this context, which then directly restricts the tests accordingly. I think it only makes sense to use it in combination.  However, this may lead to subsequent problems, such as how do I recognize that a new run needs to be performed?

How did you imagine this feature would fit into your workflow?
