### ISSUE TITLE
Default Variable Value

### ISSUE THREAD

**Issue by astorDev** [AnWeber/httpyac#731]
The issue suggests adding support for default variable values (and probably for optional variables, too). For now this code:

```http
GET https://httpbin.org/get?hello={{ name ?? "World" }}
```

gives a `name is not defined` error.  That would be great to still be able to evaluate expression even if it accesses an undefined variable. This seems to be particularly useful when using the CLI.

**Comment by AnWeber** [comment]
try using this notation

```
GET https://httpbin.org/get?hello={{ this.name ?? "World" }}
```

**Comment by astorDev** [comment]
Oh, that worked, thank you!

**Comment by AnWeber** [comment]
`this`, if not explicitly defined, will refernto the global scope. All variables are registered as properties in the global scope. That is why using this works.
