### ISSUE TITLE
How to dynamically change Authentication mode

### ISSUE THREAD

**Issue by vaibhav0461** [AnWeber/httpyac#735]
Hi Team,

We have a requirement where we want to run our httpYac http files with OAurh2.0 client credentials flow. 

For local testing we want to test the APIs using Basic Authentication mode.  Is there a way to switch the authentication mode dynamically. 

Also how can we access environment variables in scripts 

Regards,
Vaibhav

**Comment by AnWeber** [comment]
> Also how can we access environment variables in scripts

all variables (env + generated at runtime) are used the same way. just use the variableName ([example](https://github.com/httpyac/httpyac.github.io/blob/main/examples/configfile/environments_env/test.http))

> For local testing we want to test the APIs using Basic Authentication mode. Is there a way to switch the authentication mode dynamically.

Some ideas: 
- use a variable in your env file which defines the correct Authorziation Header. Variables are replaced before detecting which Authorization Mode is used.

```
// prod.env
@auth=oauth2 client
// dev.env
@auth=oauth2 basic

GET https://httpbin.org/anything
Authorization: {{auth2}}
```

- you could create a custom plugin and switch variables in this plugin and automatically add correct Authorization Header
