### ISSUE TITLE
[gRPC] Is it possible to have environment variables in paths?

### ISSUE THREAD

**Issue by gianlucaparadise** [AnWeber/httpyac#74]
I need to do something like the following:

```
proto < $GOPATH/my-service/my-service.proto
enums: String,

###

GRPC http://localhost:9090/myservice.MyService/GetUser
{
  "userId": "123456",
}
```

How can I achieve this?

**Comment by AnWeber** [comment]
Good idea. I had not thought of that at all.

**Comment by AnWeber** [comment]
With the new version it is now possible to use variables. 

```
@assetsDir=./

proto < {{assetsDir}}hello.proto
includeDirs: ["../request"]

GRPC grpcb.in:9000/hello.HelloService/sayHello
{
  "greeting": "world"
}
```
System environment variables can be used with `process.env.GOPATH`

Thanks for the idea.

**Comment by gianlucaparadise** [comment]
Thank you for the super quick answer!

I'm testing your suggestion, but unfortunately it is not working.

It works when I do the following:

```
```

**Comment by gianlucaparadise** [comment]
Thank you for the super quick answer!

I'm testing your suggestion, but unfortunately it isn't working.
It works when I run the following code:

```
@assetsDir=/Users/user.name/go

proto < {{assetsDir}}/my-service/my-service.proto

###

GRPC http://localhost:9090/myservice.MyService/GetUser
{
  "userId": "123456",
}
```

But it does NOT work when I run this:

```
@assetsDir=process.env.GOPATH

proto < {{assetsDir}}/my-service/my-service.proto

###

GRPC http://localhost:9090/myservice.MyService/GetUser
{
  "userId": "123456",
}
```

I also tried with a pre-script running this:

```
{{
  //pre request script
  console.log(`my GOPATH: ${process.env.GOPATH}`)
  exports.assetsDir = process.env.GOPATH
}}

proto < {{assetsDir}}/my-service/my-service.proto

###

GRPC http://localhost:9090/myservice.MyService/GetUser
{
  "userId": "123456",
}
```

And it still doesn't work. The log is printing `INFO: my GOPATH: undefined`.

Is my code wrong?

**Comment by AnWeber** [comment]
All expression between `{{...}}` are executed as javascript. Because of this following is invalid (`process.env.GOPATH` is interpreted as string)
```
// invalid
@assetsDir=process.env.GOPATH
proto < {{assetsDir}}/my-service/my-service.proto
// valid
proto < {{process.env.GOPATH}}/my-service/my-service.proto
```
Your next example would also be valid, but apparently the [environment](https://nodejs.org/dist/latest-v8.x/docs/api/process.html#process_process_env) variable GOPATH is not defined? I have tested it and should work
![gopath_processenv gif](https://user-images.githubusercontent.com/13434739/135753744-f962b4d1-1504-43ab-9b65-238dced41449.gif)

**Comment by gianlucaparadise** [comment]
It is working with the following piece of code, but only if I run httpyac from the shell:

```
proto < {{process.env.GOPATH}}/my-service/my-service.proto

###

GRPC localhost:9090/myservice.MyService/GetUser
{
  "userId": "123456",
}
```

When I run it within VSCode, I still get `undefined`. Please note that I'm on macOS and I'm using the default zsh shell.
If I run `echo $GOPATH` in my zsh, I correctly get `/Users/user.name/go`.
I also defined the GOPATH env variable for bash so that it also works when I run httpyac from bash.

On the other hand, it never works when I use `process.env.$GOPATH`.

Is something happening with the VSCode extension?

**Comment by AnWeber** [comment]
Also with $GOPATH it works correctly under Windows. I will test it tomorrow with Ubuntu. Can you try the following commands to see if they give the right result.
```
printenv
node -e "console.info(process.env)"
```
If both also output $GOPATH, you can output all variables once in httpyac.
```
{{
console.info(process.env)
}}
```
How VSCode accesses the environment variables under MacOSX or how they are set, I unfortunately don't remember. My last Mac was too long ago. But if bash also has to be configured extra, maybe this one is missing the corresponding configuration ([/etc/launchd.conf?](https://stackoverflow.com/questions/135688/setting-environment-variables-on-os-x)).

**Comment by gianlucaparadise** [comment]
When I run `printenv` and `node -e "console.info(process.env)"` in my shell I get all the environment variables I expected and GOPATH among them.

I also added `console.info(process.env)` to a pre request script and I get different output depending on how I run the request. When I run it via shell, I get the expected environment variables and GOPATH among them. When I run it via VSCode extension, I get the following env variables:

```
{
  "ELECTRON_RUN_AS_NODE": "1",
  "USER": "user.name",
  "COMMAND_MODE": "unix2003",
  "__CFBundleIdentifier": "com.microsoft.VSCode",
  "PATH": "/usr/bin:/bin:/usr/sbin:/sbin",
  "HOME": "/Users/user.name",
  "SHELL": "/bin/zsh",
  "XPC_FLAGS": "0x0",
  "LOGNAME": "user.name",
  "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
  "VSCODE_CWD": "/",
  "VSCODE_NLS_CONFIG": "{\"locale\":\"en-gb\",\"availableLanguages\":{},\"_languagePackSupport\":true}",
  "VSCODE_IPC_HOOK": "/Users/user.name/Library/Application Support/Code/1.60.2-main.sock",
  "VSCODE_PID": "591",
  "PWD": "/Users/user.name",
  "SHLVL": "0",
  "_": "/usr/bin/open",
  "OLDPWD": "/Users/user.name",
  "VSCODE_AMD_ENTRYPOINT": "vs/workbench/services/extensions/node/extensionHostProcess",
  "VSCODE_PIPE_LOGGING": "true",
  "VSCODE_VERBOSE_LOGGING": "true",
  "VSCODE_LOG_NATIVE": "false",
  "VSCODE_HANDLES_UNCAUGHT_ERRORS": "true",
  "VSCODE_LOG_STACK": "false"
}
```

Apparently this is something strictly related to how VSCode executes the extension.

**Comment by AnWeber** [comment]
Can you start VSCode from your zsh Shell using command `code`? I think, if you start it with Spotlight you get not the same env variables as with zsh.

**Comment by gianlucaparadise** [comment]
That's right, the env variables depends on how you launch VSCode. If I launch it using the `code` command, it works.

I found [an issue](https://github.com/microsoft/vscode/issues/15452) related to this behaviour and apparently this is expected. I think I will avoid shell env variables and rely on constants defined within the httpyac environment.

Thank you for the support and the great tool!
