### ISSUE TITLE
[gRPC] Error: The includeDirs option must be an array

### ISSUE THREAD

**Issue by gianlucaparadise** [AnWeber/httpyac#75]
When I try to use the `includeDirs` option of @grpc/proto-loader I get the following error:

```log
ERROR: ExecuteHook: protoImport failed
ERROR: Error - The includeDirs option must be an array
Error: The includeDirs option must be an array
	at Object.IZe [as loadProtosWithOptions] (/Users/user.name/.vscode/extensions/anweber.vscode-httpyac-4.0.3/dist/extension.js:84:29203)
	at KZe (/Users/user.name/.vscode/extensions/anweber.vscode-httpyac-4.0.3/dist/extension.js:84:31987)
	at Eae.process (/Users/user.name/.vscode/extensions/anweber.vscode-httpyac-4.0.3/dist/extension.js:90:126676)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Iq.trigger (/Users/user.name/.vscode/extensions/anweber.vscode-httpyac-4.0.3/dist/extension.js:90:76164)
	at async Vp (/Users/user.name/.vscode/extensions/anweber.vscode-httpyac-4.0.3/dist/extension.js:90:93948)
	at async Lw (/Users/user.name/.vscode/extensions/anweber.vscode-httpyac-4.0.3/dist/extension.js:90:94554)
	at async zst (/Users/user.name/.vscode/extensions/anweber.vscode-httpyac-4.0.3/dist/extension.js:90:101698)
	at async Object.iP (/Users/user.name/.vscode/extensions/anweber.vscode-httpyac-4.0.3/dist/extension.js:90:101567)
```

This is an example of what I'm using:

```
proto < /Users/user.name/go/my-service/my-service.proto
enums: String,
includeDirs: [ "../../proto/third_party/googleapis" ],

###

GRPC http://localhost:9090/myservice.MyService/GetUser
{
  "userId": "123456",
}
```

Is it something wrong with my `.http` file?

**Comment by AnWeber** [comment]
Rather not completely tested. I have always tested it by means of spread notation.

```
{{
exports.options= {
 includeDirs: ...
}
}}
proto < /Users/user.name/go/my-service.proto
...options
```
I'm going to take a look at it.

**Comment by AnWeber** [comment]
I overlooked the conversion of the options. This was passed directly as a string to @grpc/proto-loader. In addition, the first option in the list was also discarded. Now the options are evaluated using [vm](https://nodejs.org/api/vm.html) and converted correctly.

**Comment by AnWeber** [comment]
I have now published the changes with version 4.1.0. Please test again and let me know. Thanks.

**Comment by gianlucaparadise** [comment]
Thank you for the super quick answer!
It is now working if I use absolute paths. Is it possible to make it work with relative paths?

For example:

```
proto < /Users/user.name/go/my-service/my-service.proto
enums: String,
includeDirs: [ "../../proto/third_party/googleapis/google/api/" ],

###

GRPC http://localhost:9090/myservice.MyService/GetUser
{
  "userId": "123456",
}
```

**Comment by AnWeber** [comment]
`Includedirs` is passed directly to [@grpc/proto-loader](https://github.com/AnWeber/httpyac/blob/main/src/parser/protoHttpRegionParser.ts#L86). As I understand the logic in [proto-loader](https://github.com/grpc/grpc-node/blob/master/packages/proto-loader/src/util.ts#L23-L41), absolute path are expected.  What base path it uses when the path is relative, I just didn't understand. I would have the option to customize the path, but how to change the path I don't want to decide: relative to proto file, relative to Http file or relative to execution path.

**Comment by AnWeber** [comment]
issue https://github.com/grpc/grpc-node/issues/1278#issuecomment-592086673 mentions that includeDirs should be absolute paths. Maybe you need to make an issue in @grpc/proto-loader

**Comment by gianlucaparadise** [comment]
Oh sorry, I was expecting the opposite because of [this](https://github.com/grpc/grpc-node/issues/470#issuecomment-410035300) comment. Is it possible to use variables within the `includeDirs` paths?

**Comment by AnWeber** [comment]
I think this is about the [import of other proto definition files](https://developers.google.com/protocol-buffers/docs/proto3#importing_definitions) and not about the values in the includeDirs array.

**Comment by AnWeber** [comment]
I read over the question:-) Yes it is possible, but in this case not by `{{...}}` but in template notation. The options are already executed as javascript.

```js
proto < /Users/user.name/go/my-service/my-service.proto
enums: String,
includeDirs: [ `${assetsDir}proto/third_party/googleapis` ],
```

**Comment by gianlucaparadise** [comment]
That's great! Thank you for the support, I'm loving httpYac!

**Comment by AnWeber** [comment]
thx for using httpyac with Grpc. Good to hear that it is working not only for my use case.
