### ISSUE TITLE
test summary behavior change with 6.15.0 release

### ISSUE THREAD

**Issue by chenrui333** [AnWeber/httpyac#762]
👋 looks like 6.15.0 release has test summary behavior change as below (`0 failed` part got removed somehow and extra `)` in the summary report)

```diff
- 2 requests processed (2 succeeded, 0 failed)
+ 2 requests processed (2 succeeded))
```

is that expected? Thankss!

relates to https://github.com/Homebrew/homebrew-core/pull/179991

**Comment by AnWeber** [comment]
Yes was expected. I added better  skipped and Errorerd Handling to cli. The summary got bloated. Now I only show the actual result status. I would recommend using Exit Code to get failed cli result. Is there a problem with the behavior?

**Comment by chenrui333** [comment]
it has two `))` in the end, which seems a bit off, wdyt?

**Comment by AnWeber** [comment]
Ops. Yeah typo

**Comment by AnWeber** [comment]
thx

**Comment by chenrui333** [comment]
np, I saw it fixed now :)

https://github.com/Homebrew/homebrew-core/pull/182073
