### ISSUE TITLE
.gitignore file and Testing in Visual Studio Code

### ISSUE THREAD

**Issue by davidsoles** [AnWeber/httpyac#786]
Hello,
I've observed that the httpyac plugin in Visual Studio Code displays an 'httpyac Tests' section upon selecting 'Testing'. This section unexpectedly lists all http files within my codebase, even those within directories marked as hidden in the .gitignore file. IMHO it seems more intuitive for the httpyac plugin to exclude files and folders specified in the .gitignore from its listings.

Thanks in advance.

**Comment by AnWeber** [comment]
I use `globby` internally and the exclude would be activated See https://github.com/AnWeber/httpyac/blob/main/src/cli/send/send.ts#L200. I think you need to be at the .gitignore file level for it to work correctly.
