### ISSUE TITLE
RabbitMQ requests

### ISSUE THREAD

**Issue by QuAzI** [AnWeber/httpyac#795]
Hi
Is it possible to work with RabbitMQ queues via httpYac in the same way as https://github.com/novotnyr/rabbitmq-script-idea-plugin ?

**Comment by AnWeber** [comment]
@QuAzI Rather not. The syntax is different. If that is not the problem, there should already be a [basis](https://httpyac.github.io/guide/request.html#amqp-rabbitmq). However, I haven't tested it that extensively since my use case disappeared (kafka rules). So you might have to write me a few bugs.
