### ISSUE TITLE
response body is not returned with the first http request

### ISSUE THREAD

**Issue by JoostW21111** [AnWeber/httpyac#798]
reproduction path:

I have an http file with three http request:
![image](https://github.com/user-attachments/assets/b77177d7-8c99-4484-92ef-4011aa41e8f1)

If i send the first request, i get no response body, only the response from the Bearer token
![image](https://github.com/user-attachments/assets/94ab987f-21ee-4fa2-99f1-f4491ed52243)

If I only make a call on the first http request, and the 2nd and 3rd are commented out, I do get a complete response body

**Comment by AnWeber** [comment]
@JoostW21111 Is the import required for all Http requests. This is currently only used by the syntax for the first request. You are missing a delimiter between import and the first request. 
```
# @import ./utils/CreateSessionToken.http

### <= global  delimiter
...
```

The screenshot is cool, but I prefer an example that I can copy directly into my IDE. Could you create an example that I can run against Postman Echo, or httpbin itself, for example. I could not reproduce the error.

```

# @name session
GET https://postman-echo.com/get

###
# @title test
# @forceRef session
GET https://postman-echo.com/get?bla={{session.headers.host}}

###
# @title test2
# @forceRef session
GET https://postman-echo.com/get?bla={{session.headers.host}}
```

**Comment by JoostW21111** [comment]
@AnWeber 
for the next time, if there is a problem, I will leave out the screenshot.

but with the '### <= global  delimiter' between the import and the first request it works for me.
