### ISSUE TITLE
"httpyac - Console" not found

### ISSUE THREAD

**Issue by stonesthatwhisper** [AnWeber/httpyac#804]
Doc says: Open the OutputChannel by pressing CTRL+K followed by CTRL+H, then select "httpyac - Console".

However "httpyac - Console" does not appear in the list. 

<img width="327" alt="Screenshot 2024-10-05 at 10 46 45 AM" src="https://github.com/user-attachments/assets/033a8c7e-b149-4725-9694-721bc4b13771">

**Comment by AnWeber** [comment]
https://code.visualstudio.com/docs/getstarted/userinterface#_basic-layout

The output channel is at the bottom where the Terminal is in the Basic Layout. Or call command workbench.action.showOutputChannels. The keyboard shortcut seems to be removed from vscode.

<img width="706" alt="{BC70280C-7EF2-4B8A-99C0-4934D5E9698F}" src="https://github.com/user-attachments/assets/2a3252f5-a540-452f-a250-794809286860">
