### ISSUE TITLE
BUG: Setting export.$cancel = true of one test cancels all subsequent tests

### ISSUE THREAD

**Issue by alekdavis** [AnWeber/httpyac#808]
Setting the `exports.$cancel` variable works fine in the VSCode, but when I execute the same tests from CLI, as soon as the first test in the sequence encounters the `exports.$cancel=true` condition, all subsequent test will be skipped as well (even the ones with no dependencies).
 
I created a demo here:

https://github.com/alekdavis/httpyac-extras/blob/main/Tests/Bugs/cli_cancel_bug.http

If you run all test in the file from VSCode, it will execute tests A, C and D, but if you run all tests via CLI, it will only execute test A. I used these command-line options:

```shell
httpyac send -a -o short Tests\Bugs\cli_cancel_bug.http
```
And my output is this:
```text
---------------------

=== Test A ===

GET https://httpbin.org/json
=> 200 (368 ms, 612 B)

1 requests processed (1 succeeded, 0 failed)
```

**Comment by AnWeber** [comment]
when I call up the file, it actually looks correct at first.
![image](https://github.com/user-attachments/assets/6e09da8b-f2b5-4979-964a-283ef5b3fbe4)

Which CLI version are you currently using? We could try using a docker run command to test my app without your environment:

```
docker run -it -v ${PWD}:/data ghcr.io/anweber/httpyac:latest send -a -o short ./Tests/Bugs/cli_cancel_bug.http
```

**Comment by alekdavisintel** [comment]
Ah, cool. One or more of the versions (npm, node, or httpyac) must have been out of date. I should've recorded, but I'm not a user of node or npm outside of httpyac, so I just learned about the commands to check versions and run an update. I updated all three and now it looks good. Thank you.

While we're on this topic, if I update the VSCode extension, would it automatically update the CLI package? Or are they totally independent and I need to make sure to update them individually?

**Comment by AnWeber** [comment]
The versions are independent. I have noticed that someone has set up httpyac in [homebrew](https://formulae.brew.sh/formula/httpyac) so that the updates are automatically managed with homebrew.

**Comment by alekdavis** [comment]
I see, thanks. I assumed that the CLI was a dependency of the VSCode extension and expected a VSCode update to also update the CLI version. We do not use Homebrew (it looks like a MacOS/Linux thing and we're mostly a MSFT shop), but I will keep in mind that we need to monitor the CLI release announcements and make sure we update the CLI periodically.
