### ISSUE TITLE
Module deprecated warning when running CLI with NodeJS v23

### ISSUE THREAD

**Issue by alekdavis** [AnWeber/httpyac#813]
I did not seet this warning before I upgraded NodeJS to the latest version (v23). Now when I run the CLI, I get the warning:

> (node:23596) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> (Use `node --trace-deprecation ...` to show where the warning was created)

![image](https://github.com/user-attachments/assets/c0e4bb6d-6d5b-470a-a3be-7d5d499006bd)

The tests run fine, so it's just a warning but may be worth looking at. There is a possibility that it's just my setup, but I uninstalled and reinstalled the latest version (23.1.0) just in case.

**Comment by AnWeber** [comment]
already addressed last year: https://github.com/lupomontero/psl/issues/315 but tough-cookie seems to have fixed the issue. I will take a look

**Comment by AnWeber** [comment]
I updated tough-cookie, which should remove this warning in the next release.
