### ISSUE TITLE
Scripting - Cannot find console output window

### ISSUE THREAD

**Issue by mikebski** [AnWeber/httpyac#823]
This does not work on my mac, from the docs:

`Open the OutputChannel by pressing CTRL+K followed by CTRL+H, then select httpyac - Console from the select on the right.`

When I try it:

I've tried Control-K, this kills to the end of the line
I've tried Cmd-K Cmd-H, get "The key combination (...) is not a command"

I can't find any menu items to display a list of windows.

I tried CMD-Shift-P and typed 'output channel' and all I see is "Clears all output channel"

How do I *show* the output channel?

**Comment by AnWeber** [comment]
@mikebski hi take a look at the basic layout of vscode. https://code.visualstudio.com/docs/getstarted/userinterface#_basic-layout
There you can find the output panel. In this panel you can switch between different output channels. choose httpyac - console. Command to open this panel is `workbench.action.output.toggleOutput`
