### ISSUE TITLE
Response body formatting is not working

### ISSUE THREAD

**Issue by Kaarel-gj** [AnWeber/httpyac#84]
The JSON response body in response view is not formatted (indented). It seems that fairly short responses are being formatted. But anything trivially longer (eg 50 lines of JSON) remains in a single line.

The response body formatting used to work for even very long responses until today.

Maybe this commit? https://github.com/AnWeber/httpyac/commit/cd4ca0075a639c4963269d02eef4383e02b57124

BTW httpyac is one of my favourite VS Code extensions :) Awesome work!

**Comment by AnWeber** [comment]
I would have claimed that this place is no longer needed, Body should be set by [`setAdditionalBody`](https://github.com/AnWeber/httpyac/blob/main/src/utils/requestUtils.ts#L243) but I have also noticed that the formatting no longer works. Will fix it:-)
