### ISSUE TITLE
httpyac CLI should return non-zero exit status 

### ISSUE THREAD

**Issue by dremekie** [AnWeber/httpyac#95]
When calling a non-existent endpoint, the httpyac-cli client crashed with due to: `RequestError: connect ECONNREFUSED 127.0.0.1:60001`. The exit code was still 0. If it crashes it should be non-zero exist code since `0` means "success". We are integrating the httpyac cli into a build and it is important that the it return an error code (i.e. anything non-zero).

**Comment by AnWeber** [comment]
Yes agree, I thought I already had. Only I'm just unsure about the exact behavior. Should the application immediately run on error or still execute all other requests. Should failed tests also generate an exit code?

**Comment by dremekie** [comment]
@AnWeber I think it should behave exactly the way it does now.

- If the process exits when encountering an error(like my example), it should still exit with any non-zero exit code.
- If a test assertion fails, I think its fine to continue running the other tests.

**Comment by AnWeber** [comment]
I looked at how [newman](https://learning.postman.com/docs/running-collections/using-newman-cli/command-line-integration-with-newman/) was doing. Here an argument `--bail` is used to abort immediately on test error. I have implemented that now as well. Please note that I have already set the [exitcode 20](https://github.com/AnWeber/httpyac/blob/main/src/actions/testMethod.ts#L18) at test error before.
There is also `--suppress-exit-code` to suppress all errors and continue processing. I might implement that in a later step.

**Comment by AnWeber** [comment]
I have provided the update (v4.5.1). Thank you for trusting my tool to be used in your build.

**Comment by dremekie** [comment]
Your update worked perfectly. Thanks very much for the quick update. We're a big fan of httpyac. It is extremely flexible and very useful. Keep up the great work.
