### ISSUE TITLE
Glob pattern in CLI is not working as expected

### ISSUE THREAD

**Issue by dremekie** [AnWeber/httpyac#96]
I'm running: `httpyac --all --output short my-test/**/*.test.http`

With the following files, all works as expected:
- my-test/a.test.http
- my-test/b.test.http
- my-test/my-folder/c.skip.http

```bash
httpyac --all --output short my-test/**/*.test.http
--------------------- my-test/a.test.http  --

---------------------

=== Login from a.test.http ===

POST http://localhost:60000/graphql
=> 200 (183 ms, 541 B)
--------------------- my-test/b.test.http  --

---------------------

=== Login from b.test.http ===

POST http://localhost:60000/graphql
=> 200 (175 ms, 541 B)

2 requests tested (2 succeeded, 0 failed)
```

With the following files, only `c.test.http` runs.
- my-test/a.test.http
- my-test/b.test.http
- my-test/my-folder/c.test.http

```bash
httpyac --all --output short my-test/**/*.test.http

---------------------

=== Login from c.test.http ===

POST http://localhost:60000/graphql
=> 200 (287 ms, 541 B)
```

There's some logic issue somewhere when handling the glob pattern

**Comment by AnWeber** [comment]
I cannot understand this behavior in my case. Under Windows the folder structure works. Possibly extend the output with `--verbose`.
![windows](https://user-images.githubusercontent.com/13434739/139906327-43151db1-2606-4c67-8bb5-71566c896c74.gif)

**Comment by AnWeber** [comment]
maybe test the output once without httpyac. [globby](https://www.npmjs.com/package/globby) is used in [cli.ts](https://github.com/AnWeber/httpyac/blob/main/src/cli/cli.ts#L159).
* `npm init` in new folder
* `npm install globby@11.0.4`
* create index.js with content
```
const globby = require ('globby');
const paths = await globby(['my-test/**/*.test.http']);
console.log(paths);
```
* node index.js

**Comment by dremekie** [comment]
It returns the right result:

```js
[
  'my-test/a.test.http',
  'my-test/b.test.http',
  'my-test/my-folder/c.test.http'
]
```

I tried it again with files that look like this:

```
###
GET https://httpbin.org/json

```

This is the output:

```
httpyac --all --output short my-test/**/*.test.http

---------------------

GET https://httpbin.org/json
=> 200 (97 ms, 607 B)
```

But if I rename `c.test.http`  to `c.ignore.http` (or any filename that would be ignored by the glob pattern), i get the following correct result:

```
 httpyac --all --output short my-test/**/*.test.http
--------------------- my-test/a.test.http  --

---------------------

GET https://httpbin.org/json
=> 200 (99 ms, 607 B)
--------------------- my-test/b.test.http  --

---------------------

GET https://httpbin.org/json
=> 200 (93 ms, 607 B)

2 requests tested (2 succeeded, 0 failed)
```

**Comment by AnWeber** [comment]
Which files are displayed when the command is called without `--all`? The error must already occur before the [send method is called](https://github.com/AnWeber/httpyac/blob/main/src/cli/cli.ts#L41-L56), otherwise this console output is missing. Without `--all` you can limit it even better. I will test it under Linux later.

**Comment by AnWeber** [comment]
Apparently, under Linux the shell intervenes and converts the glob pattern into a real file. With `"` it works fine.
![image](https://user-images.githubusercontent.com/13434739/139925701-cae62e90-cb27-4c59-a6fc-4be3a016b806.png)

```
httpyac --all --output short "my-test/**/*.test.http"
```

**Comment by AnWeber** [comment]
https://medium.com/@jakubsynowiec/you-should-always-quote-your-globs-in-npm-scripts-621887a2a784

**Comment by dremekie** [comment]
@AnWeber it works with quotes. Thanks very much for looking into this and for the medium reference.

**Comment by AnWeber** [comment]
You are welcome. I will also need to overlook some build scrips today:-)
